{
  "hash": "1316d16a12aeb46f104ab7a7dd0e5f1b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"DS202A - W11+1 Summative\"\nauthor: \"62751\"\ndate: \"2026-01-23\"\nformat: html\nself-contained: true\ntoc: true\ntoc-location: left-body\ncode-fold: show\ncode-copy: true\neditor:\n  render-on-save: true\n  preview: true\n---\n\n# Setup\n\nFirst, the required R packages are loaded to support data preparation, corpus construction, text mining, and topic modeling in Parts A and B.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyr)\nlibrary(ggplot2)\nlibrary(tidyverse)\nlibrary(tidytext)\nlibrary(readr)\nlibrary(quanteda)\nlibrary(quanteda.textstats)\nlibrary(topicmodels)\nlibrary(plotly)\n```\n:::\n\n\n# Part A: Similarity and Anomalies in UN General Debate Speeches\n\n## Data Loading and Corpus Construction\n\nThe following code locates and collects all UN General Assembly speech text files by iterating over a session-based folder structure, where `TXT` directory contains subfolders (e.g. `Session 01 - 1946`), each of which stores individual speech text files (e.g. `ARG_01_1946.txt`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbase_path <- \"data/TXT\"\n\nsession_dirs <- list.dirs(\n  path = base_path,\n  recursive = FALSE,\n  full.names = TRUE\n)\n\nlength(session_dirs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 79\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(session_dirs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"data/TXT/Session 01 - 1946\" \"data/TXT/Session 02 - 1947\"\n[3] \"data/TXT/Session 03 - 1948\" \"data/TXT/Session 04 - 1949\"\n[5] \"data/TXT/Session 05 - 1950\" \"data/TXT/Session 06 - 1951\"\n```\n\n\n:::\n\n```{.r .cell-code}\ntxt_files <- unlist(\n  lapply(session_dirs, function(d) {\n    list.files(\n      path = d,\n      pattern = \"\\\\.txt$\",\n      full.names = TRUE\n    )\n  })\n)\n\nlength(txt_files)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10952\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(txt_files)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"data/TXT/Session 01 - 1946/ARG_01_1946.txt\"\n[2] \"data/TXT/Session 01 - 1946/AUS_01_1946.txt\"\n[3] \"data/TXT/Session 01 - 1946/BEL_01_1946.txt\"\n[4] \"data/TXT/Session 01 - 1946/BLR_01_1946.txt\"\n[5] \"data/TXT/Session 01 - 1946/BOL_01_1946.txt\"\n[6] \"data/TXT/Session 01 - 1946/BRA_01_1946.txt\"\n```\n\n\n:::\n:::\n\n\nThe result of the `length()` checks shows that **79** session directories are detected, corresponding exactly to the 79 General Assembly years from 1946 to 2024. In addition, a total of **10,952** speech text files are collected. This is fully consistent with the dataset description, which reports **10,952** speeches from **202** countries, confirming that all expected speech files are correctly identified.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspeech_df <- tibble(\n  file_path = txt_files,\n  text = map_chr(txt_files, read_file)\n)\n\nglimpse(speech_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 10,952\nColumns: 2\n$ file_path <chr> \"data/TXT/Session 01 - 1946/ARG_01_1946.txt\", \"data/TXT/Sess…\n$ text      <chr> \"At the resumption of the first session of the General Assem…\n```\n\n\n:::\n:::\n\n\nEach speech text file is read and combined into a tidy data frame, where each row corresponds to a single UN General Assembly speech. The output of `glimpse()` confirms that the data frame contains **10,952** rows and **two** columns (`file_path` and `text`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspeech_df <- speech_df %>%\n  mutate(\n    folder = basename(dirname(file_path)),\n    session = as.integer(str_extract(folder, \"\\\\d{2}\")),\n    year = as.integer(str_extract(folder, \"\\\\d{4}\")),\n    country = str_extract(basename(file_path), \"^[A-Z]{3}\")\n  )\n```\n:::\n\n\nSession number(`session`), year(`year`), and country code(`country`) are extracted from the folder and file names and added to the data frame as metadata for subsequent analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncorp_un <- corpus(speech_df, text_field = \"text\")\n\ndocvars(corp_un, \"year\") <- speech_df$year\ndocvars(corp_un, \"session\") <- speech_df$session\ndocvars(corp_un, \"country\") <- speech_df$country\n\nsummary(corp_un, n = 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCorpus consisting of 10952 documents, showing 5 documents:\n\n  Text Types Tokens Sentences                                  file_path\n text1  1111   3732       126 data/TXT/Session 01 - 1946/ARG_01_1946.txt\n text2  1105   4893       125 data/TXT/Session 01 - 1946/AUS_01_1946.txt\n text3   798   2744        98 data/TXT/Session 01 - 1946/BEL_01_1946.txt\n text4   937   3347        98 data/TXT/Session 01 - 1946/BLR_01_1946.txt\n text5   598   1687        55 data/TXT/Session 01 - 1946/BOL_01_1946.txt\n            folder session year country\n Session 01 - 1946       1 1946     ARG\n Session 01 - 1946       1 1946     AUS\n Session 01 - 1946       1 1946     BEL\n Session 01 - 1946       1 1946     BLR\n Session 01 - 1946       1 1946     BOL\n```\n\n\n:::\n:::\n\n\nThe texts are converted into a quanteda corpus, with `year`, `session`, and `country` information stored as document-level variables. The corpus `summary` provides a preliminary overview of document length and structure.\n\n## Exploratory Analysis of the Corpus\n\nThis part provides a descriptive overview of the UN General Debate corpus, focusing on variation in **document length** and **lexical diversity** across speeches. These patterns establish important baselines and motivate subsequent similarity and anomaly analyses by highlighting sources of heterogeneity that may influence textual comparisons.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndoc_stats <- summary(corp_un, n = ndoc(corp_un))\n\ndoc_stats <- doc_stats %>%\n  as_tibble() %>%\n  select(\n    document = Text,\n    tokens = Tokens,\n    types = Types,\n    sentences = Sentences\n  )\n\nglimpse(doc_stats)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 10,952\nColumns: 4\n$ document  <chr> \"text1\", \"text2\", \"text3\", \"text4\", \"text5\", \"text6\", \"text7…\n$ tokens    <int> 3732, 4893, 2744, 3347, 1687, 1644, 1644, 1501, 3214, 4194, …\n$ types     <int> 1111, 1105, 798, 937, 598, 568, 555, 596, 946, 1172, 549, 30…\n$ sentences <int> 126, 125, 98, 98, 55, 53, 54, 46, 95, 109, 64, 24, 26, 73, 1…\n```\n\n\n:::\n:::\n\n\nThe corpus summary is converted into a tidy data frame containing basic document-level statistics for all speeches, including the number of `tokens`, unique word `types`, and `sentences`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(doc_stats, aes(x = tokens)) +\n  geom_histogram(bins = 50, fill = \"#4C72B0\", alpha = 0.8) +\n  labs(\n    title = \"Right-Skewed Distribution of UN General Debate Speech Lengths\",\n    x = \"Number of tokens\",\n    y = \"Number of speeches\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](62751_2_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nDocument length exhibits a pronounced **right-skew**, with most speeches clustered at moderate lengths and a small number of extremely long outliers. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(doc_stats, aes(x = sentences, y = tokens)) +\n  geom_point(alpha = 0.4) +\n  labs(\n    title = \"Sentence Count Strongly Predicts Speech Length, with a Small Set of Extreme Outliers\",\n    x = \"Number of sentences\",\n    y = \"Number of tokens\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](62751_2_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n`sentences` and `tokens` are **strongly** correlated, but a small number of speeches deviate substantially from the main cluster. These extreme cases suggest candidates for anomalous speeches driven by exceptional verbosity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndoc_stats_year <- doc_stats %>%\n  mutate(\n    year = docvars(corp_un, \"year\")\n  )\n\nyearly_tokens <- doc_stats_year %>%\n  group_by(year) %>%\n  summarise(\n    avg_tokens = mean(tokens),\n    median_tokens = median(tokens),\n    n_speeches = n()\n  )\n\nhead(yearly_tokens)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n   year avg_tokens median_tokens n_speeches\n  <int>      <dbl>         <dbl>      <int>\n1  1946      2688.          1965         39\n2  1947      3115.          2306         39\n3  1948      3137.          2781         39\n4  1949      2859.          2661         35\n5  1950      3244.          2983         44\n6  1951      3605.          3050         51\n```\n\n\n:::\n:::\n\n\nThe document-level statistics are then aggregated by `year` to compute **average** and **median** speech length, along with the number of speeches delivered each year. This yearly summary enables examination of **temporal trends** in speech length across the General Assembly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(yearly_tokens, aes(x = year, y = avg_tokens)) +\n  geom_line(color = \"#C44E52\") +\n  labs(\n    title = \"Average UN General Debate Speech Length Peaks Around 1960 and Declines Thereafter\",\n    x = \"Year\",\n    y = \"Average number of tokens\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](62751_2_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nThe average length of UN General Assembly speeches rises sharply from the **late 1940s** to around **1960**, where it reaches a clear peak, before stabilizing and then gradually declining from the **late 1980s** onward. This pronounced early increase and peak indicate that speech length varies substantially across historical periods.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndoc_stats_year <- doc_stats_year %>%\n  mutate(\n    ttr = types / tokens\n  )\n\nglimpse(doc_stats_year)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 10,952\nColumns: 6\n$ document  <chr> \"text1\", \"text2\", \"text3\", \"text4\", \"text5\", \"text6\", \"text7…\n$ tokens    <int> 3732, 4893, 2744, 3347, 1687, 1644, 1644, 1501, 3214, 4194, …\n$ types     <int> 1111, 1105, 798, 937, 598, 568, 555, 596, 946, 1172, 549, 30…\n$ sentences <int> 126, 125, 98, 98, 55, 53, 54, 46, 95, 109, 64, 24, 26, 73, 1…\n$ year      <int> 1946, 1946, 1946, 1946, 1946, 1946, 1946, 1946, 1946, 1946, …\n$ ttr       <dbl> 0.2976956, 0.2258328, 0.2908163, 0.2799522, 0.3544754, 0.345…\n```\n\n\n:::\n:::\n\n\n**Type–Token Ratio (TTR)** is computed for each speech as the ratio of `types` to `tokens`, providing a simple measure of **lexical diversity** that is less directly tied to document length than raw token counts. By associating `ttr` with `year`, this representation allows exploration of how lexical diversity varies across speeches and over time.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(doc_stats_year, aes(x = ttr)) +\n  geom_histogram(bins = 50, fill = \"steelblue\", alpha = 0.7) +\n  labs(\n    title = \"Type–Token Ratio Is Approximately Bell-Shaped\",\n    x = \"Type–Token Ratio\",\n    y = \"Number of speeches\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](62751_2_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n\n```{.r .cell-code}\nttr_by_year <- doc_stats_year %>%\n  group_by(year) %>%\n  summarise(\n    avg_ttr = mean(ttr, na.rm = TRUE)\n  )\n```\n:::\n\n\nThe distribution of `ttr` is approximately **bell-shaped**, with most speeches concentrated within a relatively narrow range of lexical diversity. This suggests that while speech length varies substantially, the overall richness of vocabulary used in UN General Debate speeches is more stable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(ttr_by_year, aes(x = year, y = avg_ttr)) +\n  geom_line(color = \"darkred\") +\n  labs(\n    title = \"Average Lexical Diversity Declines Until the 1960s, Then Rises Gradually Thereafter\",\n    x = \"Year\",\n    y = \"Average TTR\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](62751_2_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nNotably, the trough in average `ttr` around **1960** aligns with the peak in average document length observed earlier. This pattern is likely driven by length effects rather than substantive changes in vocabulary usage, highlighting the importance of interpreting lexical diversity measures jointly with document length.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndoc_stats_country <- doc_stats_year %>%\n  mutate(\n    country = docvars(corp_un, \"country\")\n  )\n\ntop_countries <- doc_stats_country %>%\n  count(country, sort = TRUE) %>%\n  slice_head(n = 15) %>%\n  pull(country)\n\ncountry_tokens <- doc_stats_country %>%\n  filter(country %in% top_countries) %>%\n  group_by(country) %>%\n  summarise(avg_tokens = mean(tokens))\n\nggplot(country_tokens, aes(x = reorder(country, avg_tokens), y = avg_tokens)) +\n  geom_col(fill = \"#8172B2\") +\n  coord_flip() +\n  labs(\n    title = \"Average UN General Debate Speech Length Varies Widely Across Countries\",\n    x = \"Country\",\n    y = \"Average number of tokens\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](62751_2_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nThe figure shows substantial cross-country variation in average speech length. Countries such as **India** and **the United States** tend to deliver longer speeches on average, while others cluster at lower token counts. These differences may reflect institutional speaking styles, and this heterogeneity motivates explicitly examining country-level patterns in subsequent analyses.\n\n## Document Similarity Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nsample_idx <- sample(seq_len(ndoc(corp_un)), 500)\ncorp_sim <- corp_un[sample_idx]\n```\n:::\n\n\nBecause pairwise similarity computation scales **quadratically** with the number of documents, computing cosine similarity on the full corpus of over 10,000 speeches would be computationally infeasible. To address this, a random set of **500** speeches was selected from the full corpus, and similarity analysis was conducted on the resulting sub-corpus (`corp_sim`).\n\n\n::: callout-note\n## Why random sampling\n\nRandom sampling was adopted because it minimises prior assumptions in an exploratory similarity analysis where temporal and national structure are objects of investigation rather than design features.\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntoks <- tokens(\n  corp_sim,\n  remove_punct = TRUE,\n  remove_numbers = TRUE\n) %>%\n  tokens_tolower() %>%\n  tokens_remove(stopwords(\"en\"))\n\nhead(toks)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTokens consisting of 6 documents and 5 docvars.\ntext2463 :\n [1] \"special\"         \"pleasure\"        \"extend\"          \"sir\"            \n [5] \"warm\"            \"congratulations\" \"election\"        \"presidency\"     \n [9] \"thirty-first\"    \"session\"         \"general\"         \"assembly\"       \n[ ... and 2,155 more ]\n\ntext2511 :\n [1] \"behalf\"         \"delegation\"     \"tanzania\"       \"like\"          \n [5] \"join\"           \"colleagues\"     \"spoken\"         \"congratulating\"\n [9] \"ambassador\"     \"amerasinghe\"    \"election\"       \"important\"     \n[ ... and 2,888 more ]\n\ntext10419 :\n [1] \"humility\"   \"deep\"       \"respect\"    \"address\"    \"general\"   \n [6] \"assembly\"   \"today\"      \"newly\"      \"elected\"    \"chancellor\"\n[11] \"germany\"    \"proud\"     \n[ ... and 1,147 more ]\n\ntext8718 :\n [1] \"bring\"      \"warm\"       \"greetings\"  \"people\"     \"kiribati\"  \n [6] \"whose\"      \"behalf\"     \"privileged\" \"address\"    \"assembly\"  \n[11] \"like\"       \"take\"      \n[ ... and 1,000 more ]\n\ntext2986 :\n [1] \"speaking\"         \"general\"          \"assembly\"         \"first\"           \n [5] \"time\"             \"assumed\"          \"responsibilities\" \"secretary\"       \n [9] \"state\"            \"external\"         \"affairs\"          \"country\"         \n[ ... and 2,849 more ]\n\ntext1842 :\n [1] \"mr\"          \"president\"   \"first\"       \"speaking\"    \"behalf\"     \n [6] \"sir\"         \"seewoosagur\" \"ramgoolam\"   \"prime\"       \"minister\"   \n[11] \"mauritius\"   \"like\"       \n[ ... and 944 more ]\n```\n\n\n:::\n:::\n\n\nEach sampled speech is converted into a sequence of cleaned tokens. The text is split into individual words, punctuation and numbers are removed, all tokens are lowercased, and common English stopwords are excluded. This preprocessing reduces noise and ensures that subsequent similarity measures are driven by meaningful lexical content.\n\n::: callout-note\n## Tokenisation example (`text2463`)\n\nAfter preprocessing, a formulaic diplomatic opening such as  \n“*It is a special pleasure for me to extend to you, Sir,*”  \nis reduced to meaningful tokens  \n**“special”, “pleasure”, “extend”, “sir”**.\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndfm_sim <- dfm(toks)\nhead(dfm_sim)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDocument-feature matrix of: 6 documents, 25,088 features (96.10% sparse) and 5 docvars.\n           features\ndocs        special pleasure extend sir warm congratulations election\n  text2463        6        1      2   1    3               2        1\n  text2511        4        0      0   0    0               0        1\n  text10419       1        0      0   0    0               0        0\n  text8718        1        0      0   0    1               0        0\n  text2986        3        0      0   0    0               0        0\n  text1842        0        0      0   2    0               0        2\n           features\ndocs        presidency thirty-first session\n  text2463           1            1       7\n  text2511           0            1      11\n  text10419          1            0       0\n  text8718           1            0       4\n  text2986           1            0       4\n  text1842           1            0       3\n[ reached max_nfeat ... 25,078 more features ]\n```\n\n\n:::\n:::\n\n\nThe tokenized texts are converted into a **document–feature matrix (DFM)**, \nwhich represents each speech as a vector of term frequencies and enables quantitative similarity comparisons.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndfm_tfidf <- dfm_tfidf(dfm_sim)\nhead(dfm_tfidf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDocument-feature matrix of: 6 documents, 25,088 features (96.10% sparse) and 5 docvars.\n           features\ndocs          special  pleasure    extend       sir      warm congratulations\n  text2463  1.1792573 0.7399286 0.8922339 0.7077439 2.3240722       0.9421666\n  text2511  0.7861715 0         0         0         0               0        \n  text10419 0.1965429 0         0         0         0               0        \n  text8718  0.1965429 0         0         0         0.7746907       0        \n  text2986  0.5896287 0         0         0         0               0        \n  text1842  0         0         0         1.4154879 0               0        \n           features\ndocs         election presidency thirty-first   session\n  text2463  0.1674911  0.4271284      1.79588 0.4869228\n  text2511  0.1674911  0              1.79588 0.7651645\n  text10419 0          0.4271284      0       0        \n  text8718  0          0.4271284      0       0.2782416\n  text2986  0          0.4271284      0       0.2782416\n  text1842  0.3349822  0.4271284      0       0.2086812\n[ reached max_nfeat ... 25,078 more features ]\n```\n\n\n:::\n:::\n\n\nThe DFM is weighted using **TF–IDF** to downweight terms that are common across many speeches and highlight words that are more distinctive of individual documents, improving the interpretability of similarity measures.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsim_mat <- textstat_simil(\n  dfm_tfidf,\n  margin = \"documents\",\n  method = \"cosine\"\n)\n```\n:::\n\n\n\n\n**Cosine similarity** is applied to TF–IDF–weighted vectors to compare speeches based on shared lexical patterns rather than document length, which is appropriate given the substantial variation in speech length identified in the exploratory analysis.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsim_df <- as.matrix(sim_mat) %>%\n  as_tibble(rownames = \"doc1\") %>%\n  pivot_longer(\n    -doc1,\n    names_to = \"doc2\",\n    values_to = \"similarity\"\n  ) %>%\n  filter(doc1 < doc2)\n\nglimpse(sim_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 124,750\nColumns: 3\n$ doc1       <chr> \"text2463\", \"text2463\", \"text2463\", \"text2463\", \"text2463\",…\n$ doc2       <chr> \"text2511\", \"text8718\", \"text2986\", \"text9334\", \"text3371\",…\n$ similarity <dbl> 0.16882934, 0.05055062, 0.08088302, 0.04989024, 0.03820269,…\n```\n\n\n:::\n:::\n\nThe similarity matrix is reshaped into a tidy long format, where each row corresponds to a unique pair of distinct speeches (`doc1` and `doc2`) and their **cosine similarity score**. By retaining only one ordering of each symmetric pair (`doc1 < doc2`), the 500-speech subsample yields **124,750** pairwise comparisons (500 choose 2), avoiding double-counting.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndoc_meta <- tibble(\n  document = docnames(corp_sim),\n  year = docvars(corp_sim, \"year\"),\n  country = docvars(corp_sim, \"country\")\n)\n\nsim_df <- sim_df %>%\n  left_join(doc_meta, by = c(\"doc1\" = \"document\")) %>%\n  rename(year_1 = year, country_1 = country) %>%\n  left_join(doc_meta, by = c(\"doc2\" = \"document\")) %>%\n  rename(year_2 = year, country_2 = country)\n\nglimpse(sim_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 124,750\nColumns: 7\n$ doc1       <chr> \"text2463\", \"text2463\", \"text2463\", \"text2463\", \"text2463\",…\n$ doc2       <chr> \"text2511\", \"text8718\", \"text2986\", \"text9334\", \"text3371\",…\n$ similarity <dbl> 0.16882934, 0.05055062, 0.08088302, 0.04989024, 0.03820269,…\n$ year_1     <int> 1976, 1976, 1976, 1976, 1976, 1976, 1976, 1976, 1976, 1976,…\n$ country_1  <chr> \"MAR\", \"MAR\", \"MAR\", \"MAR\", \"MAR\", \"MAR\", \"MAR\", \"MAR\", \"MA…\n$ year_2     <int> 1976, 2013, 1980, 2016, 1982, 1992, 2003, 2019, 1978, 1994,…\n$ country_2  <chr> \"TZA\", \"KIR\", \"DOM\", \"NIC\", \"TTO\", \"BEN\", \"CHL\", \"BRN\", \"NL…\n```\n\n\n:::\n:::\n\n\nDocument-level metadata (`year` and `country`) are merged onto each pairwise similarity score, \nallowing similarity patterns to be examined in relation to shared temporal and national context.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(sim_df$similarity)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n0.003451 0.034790 0.047692 0.054764 0.065965 0.739565 \n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(sim_df, aes(x = similarity)) +\n  geom_histogram(bins = 50, fill = \"#4C72B0\", alpha = 0.8) +\n  labs(\n    title = \"Most UN General Debate Speeches Are Only Weakly Similar to Each Other\",\n    x = \"Cosine similarity\",\n    y = \"Number of document pairs\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](62751_2_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\nThe distribution of cosine similarity scores is highly **right-skewed**, with most document pairs exhibiting very low similarity. The median similarity is approximately **0.048**, indicating that the majority of UN General Debate speeches share relatively little distinctive vocabulary once common diplomatic language is downweighted. However, the long right tail suggests the presence of strongly aligned speeches, likely reflecting shared temporal context, common agenda-setting issues, or repeated institutional language within specific periods or countries.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop_similar <- sim_df %>%\n  arrange(desc(similarity)) %>%\n  slice_head(n = 10)\n\ntop_similar\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 7\n   doc1      doc2     similarity year_1 country_1 year_2 country_2\n   <chr>     <chr>         <dbl>  <int> <chr>      <int> <chr>    \n 1 text6541  text8835      0.740   2002 BFA         2014 BFA      \n 2 text5884  text6801      0.735   1998 KAZ         2003 KAZ      \n 3 text5884  text7367      0.734   1998 KAZ         2006 KAZ      \n 4 text6801  text7367      0.731   2003 KAZ         2006 KAZ      \n 5 text6083  text6263      0.712   1999 MCO         2000 MCO      \n 6 text3318  text3358      0.680   1982 LAO         1982 SDN      \n 7 text5588  text7816      0.651   1996 SLB         2008 SLB      \n 8 text10531 text6868      0.650   2022 SMR         2003 SMR      \n 9 text3127  text9638      0.649   1981 CRI         2018 CRI      \n10 text5370  text6083      0.637   1995 MCO         1999 MCO      \n```\n\n\n:::\n:::\n\n\nThe most similar document pairs are overwhelmingly speeches delivered by the **same country** across different years. These high similarity scores suggest strong continuity in national diplomatic language, where recurring themes, policy priorities, and formulaic expressions persist over time. Only **one** of the top ten pairs involves **different countries**, indicating that temporal consistency within national discourse generally outweighs cross-national similarity in shaping high cosine similarity values.\n\n:::callout-note\n\n## A Rare Cross-National Similarity in 1982 (LAO–SDN)\n\nBoth speeches emphasise international issues that were salient in the 1982 General Assembly, including Middle East–related conflicts and broader themes of sovereignty and international justice. The observed similarity likely reflects shared engagement with contemporaneous multilateral agendas.\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsim_df <- sim_df %>%\n  mutate(\n    same_year = year_1 == year_2,\n    same_country = country_1 == country_2\n  )\n```\n:::\n\n\nEach pairwise similarity score is labelled according to whether the two speeches were delivered in the same year and/or by the same country, enabling systematic comparison of temporal and national effects on textual similarity.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsim_df %>%\n  group_by(same_country) %>%\n  summarise(\n    avg_similarity = mean(similarity),\n    median_similarity = median(similarity)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  same_country avg_similarity median_similarity\n  <lgl>                 <dbl>             <dbl>\n1 FALSE                0.0538            0.0475\n2 TRUE                 0.238             0.208 \n```\n\n\n:::\n\n```{.r .cell-code}\nsim_df %>%\n  count(same_country)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  same_country      n\n  <lgl>         <int>\n1 FALSE        124074\n2 TRUE            676\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(sim_df, aes(x = same_country, y = similarity)) +\n  geom_boxplot(fill = \"#55A868\") +\n  labs(\n    title = \"Speeches by the Same Country Are Far More Similar Than Those Across Countries\",\n    x = \"Same country\",\n    y = \"Cosine similarity\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](62751_2_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\nThe box plot shows a pronounced difference in cosine similarity between speech pairs from the **same country** and those from **different countries**. Speeches delivered by the **same country** exhibit substantially **higher similarity**, with a median similarity of **0.21** compared to approximately **0.048** for cross-country pairs. It is important to note, however, that same-country pairs constitute a relatively small fraction of all document pairs in the sampled corpus (**676** out of **124,750**). \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsim_df %>%\n  group_by(same_year) %>%\n  summarise(\n    avg_similarity = mean(similarity),\n    median_similarity = median(similarity)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  same_year avg_similarity median_similarity\n  <lgl>              <dbl>             <dbl>\n1 FALSE             0.0543            0.0475\n2 TRUE              0.0843            0.0734\n```\n\n\n:::\n\n```{.r .cell-code}\nsim_df %>%\n  count(same_year)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  same_year      n\n  <lgl>      <int>\n1 FALSE     122955\n2 TRUE        1795\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(sim_df, aes(x = same_year, y = similarity)) +\n  geom_boxplot(fill = \"#DD8452\") +\n  labs(\n    title = \"Speeches Delivered in the Same Year Are More Similar Than Those from Different Years\",\n    x = \"Same year\",\n    y = \"Cosine similarity\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](62751_2_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\nThe box plot compares cosine similarity scores for speech pairs delivered in the **same year** versus **different years**. Speeches from the same year exhibit higher similarity on average and in the median (median = **0.073**) than speeches from different years (median = **0.048**). However, it is again worth noting that same-year pairs account for only **1,795** out of **124,750** document pairs in the sampled corpus. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop_pair <- top_similar %>%\n  slice(1) %>%\n  select(doc1, doc2)\n\ntop_pair\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  doc1     doc2    \n  <chr>    <chr>   \n1 text6541 text8835\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndfm_pair <- dfm_tfidf[c(top_pair$doc1, top_pair$doc2), ]\ndfm_pair\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDocument-feature matrix of: 2 documents, 25,088 features (97.61% sparse) and 5 docvars.\n          features\ndocs         special pleasure extend sir warm congratulations  election\n  text6541 0.5896287        0      0   0    0               0 0.3349822\n  text8835 0.3930858        0      0   0    0               0 0.1674911\n          features\ndocs       presidency thirty-first   session\n  text6541          0            0 0.2782416\n  text8835          0            0 0        \n[ reached max_nfeat ... 25,078 more features ]\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npair_tidy <- tidy(dfm_pair)\n\ncommon_terms <- pair_tidy %>%\n  group_by(term) %>%\n  filter(n() == 2) %>%       \n  summarise(\n    avg_tfidf = mean(count),\n    .groups = \"drop\"\n  ) %>%\n  arrange(desc(avg_tfidf)) %>%\n  slice_head(n = 10)\n\ncommon_terms\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 2\n   term        avg_tfidf\n   <chr>           <dbl>\n 1 burkina         32.3 \n 2 faso            30.5 \n 3 welcomes         3.15\n 4 taiwan           3.02\n 5 african          3.02\n 6 ouagadougou      2.78\n 7 blaise           2.22\n 8 reaffirms        1.84\n 9 china            1.80\n10 quest            1.79\n```\n\n\n:::\n:::\n\n\nExamining the most similar document pair reveals that high cosine similarity is driven not by generic diplomatic language, but by the repeated use of highly **specific**, **country-related terms**. Shared high-weight TF–IDF terms include country identifiers (**burkina**, **faso**), domestic references (**ouagadougou**, **blaise**), and stable diplomatic alignments (**china**, **taiwan**). This suggests that similarity in UN General Debate speeches reflects continuity in national self-representation and foreign policy positioning across years.\n\n## Detecting Anomalous Speeches\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlength_stats <- doc_stats_country %>%\n  mutate(\n    z_tokens = (tokens - mean(tokens)) / sd(tokens)\n  )\n\nstructural_anomalies <- length_stats %>%\n  arrange(desc(abs(z_tokens))) %>%   \n  slice_head(n = 10) %>%\n  select(\n    document, country, year,\n    tokens, z_tokens, types, sentences, ttr\n  )\n\nstructural_anomalies\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 8\n   document country  year tokens z_tokens types sentences   ttr\n   <chr>    <chr>   <int>  <int>    <dbl> <int>     <int> <dbl>\n 1 text744  IND      1960  24490    12.9   3191       943 0.130\n 2 text728  CUB      1960  24290    12.8   3456      1064 0.142\n 3 text237  RUS      1951  21158    10.9   3108       743 0.147\n 4 text901  GIN      1962  20843    10.7   3432       661 0.165\n 5 text397  IND      1955  20159    10.3   2747       799 0.136\n 6 text774  RUS      1960  19719     9.99  3321       841 0.168\n 7 text665  IND      1959  19503     9.86  2872       731 0.147\n 8 text355  IND      1954  19155     9.65  2786       758 0.145\n 9 text618  RUS      1958  18447     9.22  2869       634 0.156\n10 text312  IND      1953  17872     8.87  2808       683 0.157\n```\n\n\n:::\n:::\n\n\nThe table lists the ten most extreme structural anomalies, defined solely by **speech length**. All selected speeches have exceptionally high positive z-scores, indicating that they are far longer than the corpus average. These anomalies are concentrated in the **1950s** and **early 1960s**, particularly among speeches by **India**, **the Soviet Union**, and **Cuba**, which aligns with the peak in average document length observed around **1960** in the exploratory analysis.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncountry_counts <- doc_meta %>%\n  count(country, name = \"n_country_docs\")\n\nyear_counts <- doc_meta %>%\n  count(year, name = \"n_year_docs\")\n\navg_similarity_by_doc <- sim_df %>%\n  pivot_longer(\n    cols = c(doc1, doc2),\n    names_to = \"role\",\n    values_to = \"document\"\n  ) %>%\n  group_by(document) %>%\n  summarise(\n    avg_similarity = mean(similarity),\n    .groups = \"drop\"\n  ) %>%\n  left_join(doc_meta, by = \"document\")\n\nsemantic_isolation_anomalies <- avg_similarity_by_doc %>%\n  arrange(avg_similarity) %>%\n  slice_head(n = 10) %>%\n  left_join(country_counts, by = \"country\") %>%\n  left_join(year_counts, by = \"year\")\n\nsemantic_isolation_anomalies\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 6\n   document  avg_similarity  year country n_country_docs n_year_docs\n   <chr>              <dbl> <int> <chr>            <int>       <int>\n 1 text10821         0.0229  2024 GEO                  2          11\n 2 text7684          0.0257  2008 BIH                  2          11\n 3 text6263          0.0264  2000 MCO                  3           9\n 4 text9506          0.0281  2017 LTU                  4          11\n 5 text8571          0.0285  2012 PLW                  2          11\n 6 text5603          0.0285  1996 TKM                  1          12\n 7 text5194          0.0286  1994 LVA                  2           4\n 8 text4469          0.0287  1990 DDR                  2           5\n 9 text7633          0.0290  2007 SVN                  2          10\n10 text9985          0.0291  2019 YEM                  2           7\n```\n\n\n:::\n:::\n\n\nAlthough these speeches exhibit very low average similarity, the contextual counts indicate that several cases are based on sparse within-country comparisons. In particular, many anomalies come from countries with **only one** or **two** sampled speeches, suggesting that **semantic isolation** partly reflects **limited national context** rather than purely idiosyncratic content. For this reason, these cases are interpreted as candidate semantic anomalies, with conclusions conditioned on sampling coverage.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(avg_similarity_by_doc, aes(x = avg_similarity)) +\n  geom_histogram(bins = 50, fill = \"#4C72B0\", alpha = 0.8) +\n  labs(\n    title = \"Most Speeches Exhibit Moderate Similarity, with a Small Set of Semantically Isolated Outliers\",\n    x = \"Average cosine similarity to other speeches\",\n    y = \"Number of speeches\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](62751_2_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\nThe distribution of average cosine similarity is broadly unimodal, with most speeches concentrated around intermediate similarity values, but with noticeable local variation across the range. A small left tail of observations exhibits notably low average similarity, indicating semantic isolation relative to the rest of the corpus.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncountry_context_similarity <- sim_df %>%\n  filter(same_country) %>%\n  pivot_longer(\n    cols = c(doc1, doc2),\n    names_to = \"role\",\n    values_to = \"document\"\n  ) %>%\n  group_by(document) %>%\n  summarise(\n    avg_similarity_country = mean(similarity),\n    .groups = \"drop\"\n  ) %>%\n  left_join(doc_meta, by = \"document\")\n\ncountry_context_anomalies <- country_context_similarity %>%\n  arrange(avg_similarity_country) %>%\n  slice_head(n = 10)\n\ncountry_context_anomalies\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   document avg_similarity_country  year country\n   <chr>                     <dbl> <int> <chr>  \n 1 text7632                 0.0179  2007 SVK    \n 2 text9761                 0.0179  2018 SVK    \n 3 text5194                 0.0406  1994 LVA    \n 4 text7385                 0.0406  2006 LVA    \n 5 text682                  0.0498  1959 MYS    \n 6 text2470                 0.0529  1976 MNG    \n 7 text2154                 0.0559  1974 CHN    \n 8 text9506                 0.0576  2017 LTU    \n 9 text8185                 0.0609  2010 PHL    \n10 text5565                 0.0720  1996 NLD    \n```\n\n\n:::\n:::\n\n\n\nThis table identifies speeches that are unusual relative to their own country’s **typical discourse**, as indicated by low average cosine similarity to other speeches from the same country. In several cases, multiple speeches from the same country share identical scores, reflecting the small number of within-country comparisons available in the random subsample. For example, the two Slovak speeches ranked highest appear isolated because only two Slovak speeches were sampled, and their low similarity reflects divergence between those two texts. These cases are therefore treated as candidate within-country anomalies and interpreted with caution.\n\n\n::: callout-note\n## Country-focused Anomaly Analysis\n\nA more robust way to assess within-country anomalies would be to restrict the analysis to a single country with sufficient temporal coverage and examine deviations relative to that country’s own historical discourse. The present analysis instead relies on a random subsample of speeches, which allows broad comparison across countries but limits the reliability of within-country similarity measures. \n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(country_context_similarity, aes(x = avg_similarity_country)) +\n  geom_histogram(bins = 40, fill = \"#55A868\", alpha = 0.8) +\n  labs(\n    title = \"Most Speeches Cluster Around Moderate Within-Country Similarity, with Deviations at Both Extremes\",\n    x = \"Average similarity within same country\",\n    y = \"Number of speeches\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](62751_2_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\nMost speeches exhibit moderate within-country similarity, while a smaller number show either very low or very high values. Low-similarity cases indicate potential deviations from a country’s usual discourse, whereas high-similarity cases reflect strong rhetorical continuity. These patterns highlight meaningful within-country variation, though estimates remain sensitive to sample size.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nyear_context_similarity <- sim_df %>%\n  filter(same_year) %>%\n  pivot_longer(\n    cols = c(doc1, doc2),\n    names_to = \"role\",\n    values_to = \"document\"\n  ) %>%\n  group_by(document) %>%\n  summarise(\n    avg_similarity_year = mean(similarity),\n    .groups = \"drop\"\n  ) %>%\n  left_join(doc_meta, by = \"document\")\n\nyear_context_anomalies <- year_context_similarity %>%\n  arrange(avg_similarity_year) %>%\n  slice_head(n = 10) %>%\n  left_join(\n    length_stats %>% \n      select(document, tokens, z_tokens),\n    by = \"document\"\n  ) %>%\n  select(\n    document, country, year,\n    avg_similarity_year,\n    tokens, z_tokens\n  )\n\nyear_context_anomalies\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 6\n   document  country  year avg_similarity_year tokens z_tokens\n   <chr>     <chr>   <int>               <dbl>  <int>    <dbl>\n 1 text9506  LTU      2017              0.0202    588   -1.58 \n 2 text9985  YEM      2019              0.0233   2259   -0.569\n 3 text7516  CYP      2007              0.0251   2072   -0.682\n 4 text10821 GEO      2024              0.0266   1348   -1.12 \n 5 text7684  BIH      2008              0.0266   1638   -0.945\n 6 text8571  PLW      2012              0.0267   2200   -0.605\n 7 text8983  SVN      2014              0.0285    767   -1.47 \n 8 text8508  HUN      2012              0.0289   1426   -1.07 \n 9 text6263  MCO      2000              0.0334   1989   -0.732\n10 text8536  LTU      2012              0.0338    778   -1.46 \n```\n\n\n:::\n:::\n\n\nThese speeches exhibit unusually low similarity to other speeches delivered in the **same year**, indicating potential deviations from contemporaneous diplomatic discourse. Importantly, their relatively moderate or short lengths suggest that this pattern is not driven by structural verbosity. The partial **overlap** with global semantic anomalies points to robust year-specific outliers, although interpretation should remain cautious given variation in annual sample sizes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(year_context_similarity, aes(x = avg_similarity_year)) +\n  geom_histogram(bins = 40, fill = \"#DD8452\", alpha = 0.8) +\n  labs(\n    title = \"Within-Year Similarity Shows Wide Dispersion, with a Clear Lower Tail\",\n    x = \"Average similarity within same year\",\n    y = \"Number of speeches\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](62751_2_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n\nThe distribution shows substantial dispersion in within-year similarity, indicating that speeches delivered in the same year vary widely in their semantic alignment. While most speeches cluster at moderate similarity levels, a clear lower tail is present, providing a natural basis for identifying year-specific contextual anomalies.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanomaly_matrix <- tibble(\n  document = unique(c(\n    structural_anomalies$document,\n    semantic_isolation_anomalies$document,\n    country_context_anomalies$document,\n    year_context_anomalies$document\n  ))\n) %>%\n  mutate(\n    structural = document %in% structural_anomalies$document,\n    semantic   = document %in% semantic_isolation_anomalies$document,\n    country_ct = document %in% country_context_anomalies$document,\n    year_ct    = document %in% year_context_anomalies$document\n  )\n\nanomaly_matrix_long <- anomaly_matrix %>%\n  pivot_longer(\n    cols = -document,\n    names_to = \"type\",\n    values_to = \"flag\"\n  )\n\nggplot(anomaly_matrix_long,\n       aes(x = type, y = document, fill = flag)) +\n  geom_tile(color = \"white\") +\n  scale_fill_manual(\n    values = c(\"TRUE\" = \"#D55E00\", \"FALSE\" = \"grey90\"),\n    name = \"Anomaly\"\n  ) +\n  labs(\n    title = \"Limited Overlap Across Different Types of Anomalies\",\n    x = \"Anomaly type\",\n    y = \"Document\"\n  ) +\n  theme_minimal() +\n  theme(\n    axis.text.y = element_blank(),\n    axis.ticks.y = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![](62751_2_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n:::\n\n \nThis figure summarises the **overlap** between different types of anomalies at the document level. Most speeches are flagged as anomalous under only **one** criterion, indicating that structural, semantic, and contextual anomalies capture largely **distinct** dimensions of deviation. This supports the analytical separation of anomaly types adopted in this section.\n\n\n## Discussion\n\nPart A used **similarity** and **anomaly** perspectives to characterise both typical and exceptional patterns in UN General Debate speeches. Rather than treating these as separate exercises, the analysis shows that each perspective captures a distinct but complementary dimension of diplomatic discourse.\n\n**Similarity analysis** reveals that national continuity is the primary source of textual alignment. Speeches by the same country remain lexically close across years, indicating stable rhetorical identities that outweigh shared temporal context. High similarity is driven by repeated, country-specific and policy-relevant language rather than generic diplomatic formulas.\n\nBy contrast, **anomaly detection** highlights moments of deviation that are not visible from similarity alone. Structural anomalies reflect historically specific periods of heightened verbosity, while semantic and contextual anomalies capture speeches that diverge from contemporaneous or national discourse despite being structurally typical. The limited overlap between anomaly types demonstrates that deviation is multidimensional.\n\nTaken together, these findings suggest that UN General Debate discourse is simultaneously conservative and adaptive. National rhetorical styles exhibit strong continuity, yet departures emerge along multiple dimensions depending on historical context and reference frame. This underscores the value of combining similarity-based and anomaly-based approaches.\n\n# Part B: How Have the Dominant Thematic Frames of the UN General Debate Evolved Over Time?\n\n## Research Question and Motivation\nThe UN General Debate provides a record of how states publicly frame global issues in a multilateral forum. Since each speech reflects national priorities, taken together, they reveal how the **international agenda** has evolved over time.\n\nThis study asks: \n\n> *How have the dominant thematic frames of UN General Debate speeches changed across decades, and to what extent do these shifts differ across countries?* \n\n\nThe focus is on long-run patterns in **thematic composition**. To address this question, the analysis relies on **unsupervised learning** methods that allow thematic structures to emerge inductively from the data.\n\n\n:::callout-note\n\n## Why Unsupervised Learning\n\n*Supervised learning* would require historically stable labels for speech themes, which are unavailable for UN General Debate speeches spanning nearly eight decades and would risk anachronistic interpretations. *Unsupervised learning* instead allows **latent thematic structure** to emerge from word co-occurrence patterns, enabling analysis of long-run changes in the semantic organisation of multilateral discourse.\n\n:::\n\n\n## Sampling Strategy\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(456)\n\nspeech_sample <- speech_df %>%\n  mutate(decade = floor(year / 10) * 10) %>%\n  group_by(decade) %>%\n  sample_n(\n    size = min(200, n()),  \n    replace = FALSE\n  ) %>%\n  ungroup()\n\ncorp_rq <- corpus(speech_sample, text_field = \"text\")\n\ndocvars(corp_rq, \"year\")    <- speech_sample$year\ndocvars(corp_rq, \"country\") <- speech_sample$country\n\nspeech_sample %>%\n  summarise(\n    n_docs = n(),\n    min_year = min(year),\n    max_year = max(year),\n    n_decades = n_distinct(decade)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  n_docs min_year max_year n_decades\n   <int>    <int>    <int>     <int>\n1   1752     1946     2024         9\n```\n\n\n:::\n:::\n\n\nTo ensure balanced temporal coverage, speeches were randomly sampled at the **decade level**, with up to **200** speeches drawn from each decade. The resulting corpus consists of **1,752** speeches spanning nine decades from 1946 to 2024, providing a **temporally balanced** subset for the subsequent research question analysis.\n\n## Topic Modeling \n\n\n::: {.cell}\n\n```{.r .cell-code}\ntoks_rq <- tokens(\n  corp_rq,\n  remove_punct   = TRUE,\n  remove_numbers = TRUE\n) %>%\n  tokens_tolower() %>%\n  tokens_remove(stopwords(\"en\"))\n\ndfm_rq <- dfm(toks_rq)\n\ndfm_rq <- dfm_trim(\n  dfm_rq,\n  min_termfreq = 20,\n  max_docfreq  = 0.5,\n  docfreq_type = \"prop\"\n)\n\ndfm_rq\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDocument-feature matrix of: 1,752 documents, 8,878 features (93.09% sparse) and 6 docvars.\n       features\ndocs    representatives firm determined step along path peace-loving never lost\n  text1               1    1          1    2     1    1            1     1    2\n  text2               2    0          2    0     1    0            0     2    0\n  text3               1    1          1    0     0    0            2     0    0\n  text4               0    1          0    0     0    0            0     1    1\n  text5               0    1          0    0     0    0            1     2    0\n  text6               3    1          0    0     0    0            0     1    1\n       features\ndocs    sight\n  text1     1\n  text2     0\n  text3     0\n  text4     0\n  text5     0\n  text6     1\n[ reached max_ndoc ... 1,746 more documents, reached max_nfeat ... 8,868 more features ]\n```\n\n\n:::\n:::\n\n\nThe document–feature matrix contains **1,752** documents and **8,878** unique terms, with a sparsity of approximately **93%**. Prior to topic modeling, the feature space was reduced by trimming extremely rare terms (appearing fewer than **20 times** in the corpus) and highly ubiquitous terms (appearing in more than **50%** of documents). This step helps remove idiosyncratic noise and near-stopwords.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndtm_rq <- convert(dfm_rq, to = \"topicmodels\")\n\nset.seed(789)\n\nlda_rq <- LDA(\n  dtm_rq,\n  k = 8,\n  method = \"Gibbs\",\n  control = list(\n    seed   = 789,\n    burnin = 100,\n    iter   = 500,\n    thin   = 20\n  )\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop_terms <- terms(lda_rq, 10)\ntop_terms\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Topic 1      Topic 2        Topic 3        Topic 4       Topic 5      \n [1,] \"america\"    \"co-operation\" \"african\"      \"arab\"        \"climate\"    \n [2,] \"latin\"      \"might\"        \"co-operation\" \"israel\"      \"challenges\" \n [3,] \"american\"   \"committee\"    \"struggle\"     \"palestine\"   \"sustainable\"\n [4,] \"democracy\"  \"commission\"   \"southern\"     \"resolutions\" \"goals\"      \n [5,] \"central\"    \"opinion\"      \"namibia\"      \"palestinian\" \"commitment\" \n [6,] \"solidarity\" \"permanent\"    \"apartheid\"    \"aggression\"  \"address\"    \n [7,] \"per\"        \"veto\"         \"regime\"       \"lebanon\"     \"poverty\"    \n [8,] \"cent\"       \"field\"        \"cyprus\"       \"refugees\"    \"reform\"     \n [9,] \"century\"    \"purposes\"     \"liberation\"   \"iraq\"        \"health\"     \n[10,] \"society\"    \"questions\"    \"colonial\"     \"territories\" \"terrorism\"  \n      Topic 6 Topic 7         Topic 8     \n [1,] \"say\"   \"issues\"        \"soviet\"    \n [2,] \"let\"   \"comprehensive\" \"union\"     \n [3,] \"said\"  \"dialogue\"      \"europe\"    \n [4,] \"know\"  \"environment\"   \"china\"     \n [5,] \"think\" \"treaty\"        \"western\"   \n [6,] \"want\"  \"context\"       \"atomic\"    \n [7,] \"words\" \"european\"      \"proposals\" \n [8,] \"shall\" \"positive\"      \"aggression\"\n [9,] \"less\"  \"activities\"    \"germany\"   \n[10,] \"never\" \"convention\"    \"armaments\" \n```\n\n\n:::\n:::\n\n\n\nTable: **Dominant Thematic Frames Identified in UN General Debate Speeches**\n\n| Topic | Interpreted Theme | Representative Top Terms |\n|------:|------------------|--------------------------|\n| 1 | Democracy and Regional Solidarity | america, american, democracy, latin, solidarity |\n| 2 | Multilateral Institutions and Procedures | co-operation, committee, commission, veto, permanent |\n| 3 | African Decolonisation and Apartheid | african, namibia, apartheid, liberation, colonial |\n| 4 | Middle East Conflict | arab, israel, palestine, palestinian, refugees |\n| 5 | Climate Change and Sustainable Development | climate, sustainable, poverty, health, reform |\n| 6 | Arms Control and Conflict Resolution | arms, treaty, settlement, aggression, cyprus |\n| 7 | Legal and Environmental Governance | treaty, convention, dialogue, environment, comprehensive |\n| 8 | Cold War and Great Power Rivalry | soviet, union, china, europe, armaments |\n\nThe table summarises the eight latent topics identified using **Latent Dirichlet Allocation (LDA)** applied to the decade-stratified subsample of UN General Debate speeches. Topics were estimated using **Gibbs sampling**, with the number of topics fixed at **k = 8**. For each topic, the interpretation is based on the top ten highest-probability terms. These word clusters capture coherent thematic frames such as *Cold War rivalry*, *decolonisation*, *Middle East conflict*, and *climate governance*.\n\n::: callout-note\n## Why LDA\n\nLDA was selected over hard clustering methods because it models documents as probabilistic mixtures. This fits diplomatic speeches well, as they typically address multiple overlapping themes simultaneously.\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheta_mat <- posterior(lda_rq)$topics\n\ntheta_rq <- as_tibble(theta_mat) %>%\n  mutate(\n    year   = docvars(corp_rq, \"year\"),\n    decade = floor(year / 10) * 10\n  )\n\nhead(theta_rq)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 10\n     `1`   `2`    `3`    `4`    `5`   `6`    `7`    `8`  year decade\n   <dbl> <dbl>  <dbl>  <dbl>  <dbl> <dbl>  <dbl>  <dbl> <int>  <dbl>\n1 0.127  0.420 0.0895 0.0484 0.0227 0.180 0.0432 0.0689  1946   1940\n2 0.0399 0.447 0.0172 0.0210 0.0203 0.405 0.0153 0.0348  1946   1940\n3 0.0384 0.412 0.0508 0.0550 0.0508 0.258 0.0508 0.0840  1946   1940\n4 0.0316 0.302 0.0258 0.0420 0.0177 0.249 0.0548 0.277   1949   1940\n5 0.0511 0.554 0.0267 0.0286 0.0305 0.171 0.0511 0.0868  1948   1940\n6 0.266  0.354 0.0255 0.0620 0.0428 0.154 0.0543 0.0409  1948   1940\n```\n\n\n:::\n:::\n\n\nThe `head()` output reports the document–topic distributions inferred by the LDA model. Each row corresponds to a single General Debate speech, and each of the eight numeric columns represents the **posterior** probability that the speech is generated from a given topic(sum to one within each document). The variables `year` and `decade` are added to facilitate analysis of **temporal variation** in topic prevalence in subsequent analyses.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheta_only <- as_tibble(theta_mat) \n\npca_theta <- prcomp(\n  theta_only,\n  center = TRUE,\n  scale. = TRUE\n)\n\npca_df <- as_tibble(pca_theta$x) %>%\n  mutate(\n    year   = theta_rq$year,\n    decade = theta_rq$decade\n  )\n\nhead(pca_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 10\n    PC1    PC2    PC3    PC4    PC5      PC6    PC7       PC8  year decade\n  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>    <dbl>  <dbl>     <dbl> <int>  <dbl>\n1 -2.05 -0.534 -0.485 -0.239 -0.853 -0.582    0.852 -9.99e-16  1946   1940\n2 -3.15 -1.47   0.547 -0.572 -2.12   0.885    0.268 -9.18e-16  1946   1940\n3 -2.25 -0.727  0.532 -0.101 -1.41  -0.00734  0.652 -5.65e-16  1946   1940\n4 -2.38 -0.608  1.12   0.988 -0.246  0.0777  -0.117  9.25e-16  1949   1940\n5 -2.47 -0.891  0.131  0.300 -1.65  -1.12     1.39  -2.37e-15  1948   1940\n6 -1.58 -1.20  -1.32  -0.845 -0.130 -1.11     0.122 -1.20e-15  1948   1940\n```\n\n\n:::\n:::\n\n\n**Principal Component Analysis (PCA)** was applied to document-level topic proportion vectors to summarise the main axes of variation in relative thematic composition across speeches, providing a low-dimensional representation.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscree_df <- tibble(\n  PC = seq_along(pca_theta$sdev),\n  variance = (pca_theta$sdev^2) / sum(pca_theta$sdev^2)\n)\n\nggplot(scree_df, aes(x = PC, y = variance)) +\n  geom_line() +\n  geom_point() +\n  labs(\n    title = \"Variance Concentrated in the First Two Principal Components\",\n    x = \"Principal Component\",\n    y = \"Proportion of Variance Explained\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](62751_2_files/figure-html/unnamed-chunk-43-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(pca_theta)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nImportance of components:\n                          PC1    PC2    PC3    PC4    PC5     PC6     PC7\nStandard deviation     1.4519 1.1632 1.0946 1.0334 0.9588 0.88416 0.75617\nProportion of Variance 0.2635 0.1691 0.1498 0.1335 0.1149 0.09772 0.07148\nCumulative Proportion  0.2635 0.4326 0.5824 0.7159 0.8308 0.92852 1.00000\n                             PC8\nStandard deviation     2.232e-15\nProportion of Variance 0.000e+00\nCumulative Proportion  1.000e+00\n```\n\n\n:::\n:::\n\n\nThe first two principal components jointly account for approximately **43%** of the total variance, capturing the dominant dimensions of thematic variation across speeches. For this reason, subsequent visualisations and analyses focus primarily on **PC1** and **PC2**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npca_loadings <- as_tibble(\n  pca_theta$rotation,\n  rownames = \"topic\"\n) %>%\n  select(topic, PC1, PC2)\n\npca_loadings\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 3\n  topic     PC1     PC2\n  <chr>   <dbl>   <dbl>\n1 1     -0.0595 -0.261 \n2 2     -0.498  -0.115 \n3 3     -0.0197  0.687 \n4 4      0.0432  0.409 \n5 5      0.500  -0.447 \n6 6     -0.432  -0.226 \n7 7      0.452   0.154 \n8 8     -0.324   0.0641\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npca_loadings %>%\n  select(topic, PC1, PC2) %>%\n  pivot_longer(\n    cols = starts_with(\"PC\"),\n    names_to = \"PC\",\n    values_to = \"loading\"\n  ) %>%\n  ggplot(aes(x = topic, y = loading, fill = loading > 0)) +\n  geom_col(show.legend = FALSE) +\n  coord_flip() +\n  facet_wrap(~ PC, scales = \"free_x\") +\n  labs(\n    title = \"Thematic Dimensions of UN Discourse: Governance vs Security and Geopolitical Conflict\",\n    x = \"Topic\",\n    y = \"Loading\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](62751_2_files/figure-html/unnamed-chunk-46-1.png){width=672}\n:::\n:::\n\n\nThe PCA loadings show that **PC1** contrasts **governance** and **sustainability** themes (Topics 5 and 7) with **institution** and **security** focused discourse (Topics 2 and 6), while **PC2** reflects region specific **geopolitical issues**, notably African decolonisation and the Middle East conflict (Topics 3 and 4). Together, these components define an interpretable low dimensional space.\n\n\n## Temporal Evolution of Dominant Topics\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntopic_by_decade <- theta_rq %>%\n  pivot_longer(\n    cols = `1`:`8`,\n    names_to = \"topic\",\n    values_to = \"prob\"\n  ) %>%\n  group_by(decade, topic) %>%\n  summarise(\n    avg_prob = mean(prob),\n    .groups = \"drop\"\n  )\n\nhead(topic_by_decade)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  decade topic avg_prob\n   <dbl> <chr>    <dbl>\n1   1940 1       0.0877\n2   1940 2       0.398 \n3   1940 3       0.0387\n4   1940 4       0.0651\n5   1940 5       0.0300\n6   1940 6       0.172 \n```\n\n\n:::\n:::\n\n\nThese values represent the **mean topic prevalence** for **each decade**, computed by averaging posterior topic probabilities across documents. This aggregation allows systematic comparison of the relative prominence of thematic frames over time.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(pca_df, aes(x = PC1, y = PC2, color = factor(decade))) +\n  geom_point(alpha = 0.6, size = 1.5) +\n  labs(\n    title = \"Long-Run Reconfiguration of UN Discourse in Thematic Space\",\n    x = \"Principal Component 1\",\n    y = \"Principal Component 2\",\n    color = \"Decade\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](62751_2_files/figure-html/unnamed-chunk-48-1.png){width=672}\n:::\n:::\n\n\nThis figure plots individual speeches in the two-dimensional PCA space, with colours indicating decades. Speeches from the same decade tend to cluster in similar regions of the PCA space, indicating that each period is characterised by a broadly shared thematic profile.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npca_decade <- pca_df %>%\n  group_by(decade) %>%\n  summarise(\n    PC1 = mean(PC1),\n    PC2 = mean(PC2),\n    .groups = \"drop\"\n  )\n\nggplot(pca_decade, aes(x = PC1, y = PC2, label = decade)) +\n  geom_point(size = 4, color = \"steelblue\") +\n  geom_path(group = 1, color = \"grey70\") +\n  geom_text(vjust = -0.8) +\n  labs(\n    title = \"Decade-level Thematic Shifts in PCA Space\",\n    x = \"Principal Component 1\",\n    y = \"Principal Component 2\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](62751_2_files/figure-html/unnamed-chunk-49-1.png){width=672}\n:::\n:::\n\n\nThe **decade-level averages** trace a clear temporal trajectory in the PCA space. \n\nAlong **PC1**, decades move steadily from lower to higher values over time, reflecting a long-run shift from early postwar concerns with multilateral institutions and Cold War rivalry toward development, governance, and sustainability.\n\n**PC2** rises from the 1940s and peaks in the 1970s and 1980s, reflecting the prominence of decolonisation, regional conflicts, and legal and normative agendas, before declining from the 1990s onward as these themes become less salient relative to other global priorities.　\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(topic_by_decade,\n       aes(x = decade, y = avg_prob, color = topic)) +\n  geom_line(linewidth = 1) +\n  geom_point(size = 2) +\n  labs(\n    title = \"Decade-level Evolution of Topic Prevalence\",\n    x = \"Decade\",\n    y = \"Average Topic Proportion\",\n    color = \"Topic\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](62751_2_files/figure-html/unnamed-chunk-50-1.png){width=672}\n:::\n:::\n\n\nThis figure highlights clear differences in the temporal dynamics of individual topics. \n\nClimate Change and Sustainable Development (**Topic 5**) shows a largely monotonic increase, indicating a sustained and growing salience of environmental and development concerns over time. In contrast, Multilateral Institutions and Procedures (**Topic 2**) exhibits a steady decline, suggesting a gradual reduction in emphasis on institutional and procedural discourse such as committees, commissions, and veto politics.\n\nAfrican Decolonisation and Apartheid (**Topic 3**) follows a distinct mid-period trajectory, rising sharply and peaking around the 1970s before declining thereafter. By comparison, Democracy and Regional Solidarity (**Topic 1**) remains relatively stable across decades, showing less pronounced variation than other thematic frames.\n\nNotably, these topic-level trends are consistent with the patterns observed in the PCA-based figures above.\n\n\n## Clustering Country–Decade Thematic Profiles\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntopic_country_decade <- theta_rq %>%\n  mutate(country = docvars(corp_rq, \"country\")) %>%\n  pivot_longer(\n    cols = `1`:`8`,\n    names_to = \"topic\",\n    values_to = \"prob\"\n  ) %>%\n  group_by(country, decade, topic) %>%\n  summarise(\n    avg_prob = mean(prob),\n    .groups = \"drop\"\n  )\n\nhead(topic_country_decade, 8)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 4\n  country decade topic avg_prob\n  <chr>    <dbl> <chr>    <dbl>\n1 AFG       1950 1       0.0557\n2 AFG       1950 2       0.389 \n3 AFG       1950 3       0.0845\n4 AFG       1950 4       0.0893\n5 AFG       1950 5       0.0348\n6 AFG       1950 6       0.207 \n7 AFG       1950 7       0.0933\n8 AFG       1950 8       0.0462\n```\n\n\n:::\n:::\n\n\nThis table reports average topic proportions by **country–decade**, summarising each country’s typical thematic profile in a given period.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncountry_decade_mat <- topic_country_decade %>%\n  pivot_wider(\n    names_from  = topic,\n    values_from = avg_prob\n  ) %>%\n  drop_na() %>%                 \n  arrange(decade, country) %>%\n  unite(\"unit\", country, decade, sep = \"_\") %>%\n  column_to_rownames(\"unit\")\n\ndim(country_decade_mat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 961   8\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(country_decade_mat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  1         2          3          4          5          6\nARG_1940 0.12116688 0.5619998 0.01987398 0.02854402 0.01802273 0.15380355\nAUS_1940 0.03299045 0.6221589 0.01676403 0.01902802 0.01523661 0.16337592\nBEL_1940 0.07786416 0.4704803 0.02060892 0.02232905 0.01595832 0.16648440\nBLR_1940 0.04381392 0.2413049 0.02703796 0.03432295 0.02003333 0.07145426\nBOL_1940 0.16928814 0.4097270 0.04102789 0.03500115 0.02433340 0.22632947\nBRA_1940 0.11719832 0.5327894 0.03740835 0.04316965 0.03320593 0.13763751\n                  7          8\nARG_1940 0.02149871 0.07509030\nAUS_1940 0.05330111 0.07714494\nBEL_1940 0.04743793 0.17883697\nBLR_1940 0.02581671 0.53621593\nBOL_1940 0.03344445 0.06084851\nBRA_1940 0.05096703 0.04762382\n```\n\n\n:::\n:::\n\n\nThe country–decade matrix was constructed by reshaping the aggregated data into a **wide format**, where each row corresponds to a unique country–decade unit and each column represents the average prevalence of a topic. This step converts document-level topic information into a structured feature matrix suitable for subsequent dimensionality reduction and clustering analyses.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npca_cd <- prcomp(\n  country_decade_mat,\n  center = TRUE,\n  scale. = TRUE\n)\n\nsummary(pca_cd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nImportance of components:\n                          PC1    PC2    PC3    PC4    PC5     PC6     PC7\nStandard deviation     1.4657 1.1728 1.0853 1.0368 0.9531 0.87628 0.73976\nProportion of Variance 0.2685 0.1719 0.1472 0.1344 0.1135 0.09598 0.06841\nCumulative Proportion  0.2685 0.4405 0.5877 0.7221 0.8356 0.93159 1.00000\n                             PC8\nStandard deviation     1.365e-15\nProportion of Variance 0.000e+00\nCumulative Proportion  1.000e+00\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscree_cd <- tibble(\n  PC = seq_along(pca_cd$sdev),\n  variance = (pca_cd$sdev^2) / sum(pca_cd$sdev^2)\n)\n\nggplot(scree_cd, aes(x = PC, y = variance)) +\n  geom_line() +\n  geom_point() +\n  labs(\n    title = \"Scree Plot of PCA on Country–Decade Topic Profiles\",\n    x = \"Principal Component\",\n    y = \"Proportion of Variance Explained\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](62751_2_files/figure-html/unnamed-chunk-54-1.png){width=672}\n:::\n:::\n\n\nThe scree plot indicates that the first two principal components together explain around **44%** of the total variance. Subsequent components contribute progressively smaller increments, with no clear additional elbow beyond PC2. Focusing on **PC1** and **PC2** in the subsequent clustering and visual analyses is therefore well justified.\n\n\n::: callout-note\n\n## Similarity Across PCA Analyses\n\nCompared with the PCA applied to document-level topic proportions, the scree plot for country–decade profiles exhibits an almost identical shape. This suggests that the dominant structure of thematic variation is robust and remains stable across different levels of aggregation.\n\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npca_cd_df <- as_tibble(pca_cd$x[, 1:2], rownames = \"unit\") %>%\n  separate(unit, into = c(\"country\", \"decade\"), sep = \"_\") %>%\n  mutate(decade = as.integer(decade))\n\nhead(pca_cd_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  country decade   PC1    PC2\n  <chr>    <int> <dbl>  <dbl>\n1 ARG       1940 -2.98 -1.38 \n2 AUS       1940 -3.12 -1.09 \n3 BEL       1940 -2.84 -0.967\n4 BLR       1940 -2.50  0.261\n5 BOL       1940 -2.61 -1.54 \n6 BRA       1940 -2.56 -1.11 \n```\n\n\n:::\n:::\n\n\nEach country–decade unit is represented by its coordinates on **PC1** and **PC2**. This table reports these PC1 and PC2 scores, linking each thematic position in the reduced space to a specific country and decade.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndist_cd <- dist(pca_cd_df %>% select(PC1, PC2), method = \"euclidean\")\nhc_cd <- hclust(dist_cd, method = \"ward.D2\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npca_cd_df$cluster <- factor(cutree(hc_cd, k = 4))\ntable(pca_cd_df$cluster, pca_cd_df$decade)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   \n    1940 1950 1960 1970 1980 1990 2000 2010 2020\n  1   49   73   86   29    8    1    0    1    1\n  2    1    0    2   12   28   88   67   40   20\n  3    0    2   10   68   72   17    4    5    0\n  4    0    0    1    1    5   16   56   88  110\n```\n\n\n:::\n:::\n\n\n**Hierarchical clustering** based on the first two PCA dimensions yields four clusters of country–decade thematic profiles. Early decades are mainly associated with Clusters 1 and 3, while later decades shift toward Clusters 2 and 4. Although this pattern is strongly structured by time, some countries fall into different clusters than others in the same decade, indicating meaningful cross-national variation alongside the dominant temporal trend.\n\n:::callout-note\n\n## Why Hierarchical Clustering\n\nHierarchical clustering was chosen to determine the cluster count (k) inductively from the dendrogram, rather than fixing it beforehand. \n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npca_cd_df <- pca_cd_df %>%\n  mutate(\n    hover_text = paste0(\n      \"Country: \", country,\n      \"<br>Decade: \", decade\n    )\n  )\n\np <- ggplot(\n  pca_cd_df,\n  aes(\n    x = PC1,\n    y = PC2,\n    color = cluster,\n    text = hover_text\n  )\n) +\n  geom_point(size = 2, alpha = 0.8) +\n  labs(\n    title = \"Country–Decade Thematic Clusters in PCA Space\",\n    x = \"Principal Component 1\",\n    y = \"Principal Component 2\",\n    color = \"Cluster\"\n  ) +\n  theme_minimal()\n\n\nggplotly(p, tooltip = \"text\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-fb6a3cc871d1113188bc\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-fb6a3cc871d1113188bc\">{\"x\":{\"data\":[{\"x\":[-2.9806110691233756,-3.1199291483185903,-2.8358211050601754,-2.5049844371334018,-2.614183543309879,-2.5585971286951898,-2.5919505422066873,-2.2048778965419147,-2.3892690613084526,-2.8177775414709991,-2.6556199453424512,-1.9334437845213155,-2.0511203360465418,-2.3980990048743265,-2.1871411952601272,-2.9745558903471183,-2.8175875313737651,-3.0308211433950594,-2.3819067990940113,-1.698385917314456,-2.8404039271546022,-2.4298512590006345,-1.8564261843371381,-1.5482295843433513,-2.0769489537156849,-2.0373212424577112,-2.5406066362781399,-2.5383073880223459,-2.5765527007287856,-2.736278393702881,-2.4318482604518792,-2.8958987967394529,-2.6857789958212561,-2.4240432564330376,-2.7582471656051446,-2.4951839375234326,-2.6429633778374617,-1.1528001610361751,-2.6668305095358025,-2.6164936797898335,-2.2854566429928904,-1.7715152803226513,-2.1899486733682196,-2.5480402187175426,-1.9704384599796594,-2.2669129464754745,-2.6024374777849406,-2.6648774799099071,-2.5983350848763491,-2.0950252277897801,-2.1659331655120115,-2.2258928241588518,-2.936146631695062,-1.9557180727048653,-2.6633165745572667,-2.2416206207120775,-2.4332121626540291,-1.6731442115954476,-2.0795966307744007,-2.9907882614755206,-2.2055305901728475,-2.3661317409344278,-2.5196294081220763,-2.2439151039186163,-1.9582578467900049,-1.543908893757326,-1.7440462322562278,-1.7894914803581121,-1.8144878081723117,-2.4241985309760028,-2.7446255849882566,-2.1907608869081625,-2.5401063067746326,-2.0547383497143619,-1.7127329825724615,-2.2063809443730094,-2.0610861673660326,-2.0417485625406488,-2.6312541861661383,-1.9126560298291322,-2.3206992924550298,-1.5621599300350604,-2.9456381720871154,-1.7663659362398747,-2.2529686438483623,-1.3699320046854668,-1.4506150146452417,-2.1773177559096863,-2.4401712985525714,-2.5219372053923794,-2.2123239064893694,-1.4198807186278442,-1.4255734286214894,-2.5886244737218727,-2.3500446807619779,-1.6885213268486405,-2.3753002161091596,-1.3538760474975231,-2.0020896672792765,-2.8025915898054925,-2.0786963467069994,-2.2230134191647628,-2.3667838846534317,-2.2081280276326014,-2.4421923903823202,-1.9703779733548494,-2.1448242122950854,-2.446363057120621,-1.4986990787381134,-1.4984022561504156,-2.2107786239070508,-2.9041111826882773,-1.6803813046007734,-2.2173992456495162,-1.9947753784959539,-2.304848409222044,-2.3393835294815477,-2.3046992479021031,-1.9890129997352612,-2.1929656182583153,-2.471740307428274,-2.4343577663516536,-1.919764851202433,-2.1035753075260883,-2.1579911809050496,-1.8820679073798636,-1.5313780481390664,-2.0298369928981943,-2.2163049238350161,-2.0473271965769073,-1.6041865251742444,-1.5691686463597905,-1.8005368938352238,-1.6360182227123752,-1.8288192085084747,-1.9069094054245086,-1.7713681220591315,-2.1832151275744831,-1.8329695266447932,-1.8109488241449629,-2.1304572298688056,-1.5868752335524032,-1.9735683993096276,-1.9813417521685508,-1.8825199254389704,-2.0688047695452356,-2.2692948062822236,-1.5459433899712407,-2.6000173802971243,-1.3612168985255844,-1.9872309506963211,-1.8295747740738297,-1.1825209260679608,-1.9700367110537462,-2.1132830828058027,-2.3546468612083702,-2.241465475200374,-1.4286661645083529,-1.6654813786298461,-1.9623374865807621,-1.3707841241254195,-1.7569938154506981,-1.7196855243967666,-2.4338264048897718,-2.1811163041795258,-1.6547781147446974,-1.3750812925091114,-1.8347762836042782,-2.1349414420457329,-1.7218133636603179,-1.9660461847884863,-1.2005763018382547,-1.5287242075856056,-1.5040003335612486,-1.7555554871411996,-2.7181641194240798,-1.7435891384781712,-2.9370910174703631,-2.741772865221217,-1.7619020774323004,-1.5083011571910108,-2.5400370539133328,-2.0627301516654168,-2.024072488838383,-1.2765285419643495,-1.9955709604266818,-2.407348350944039,-2.0060454356093516,-2.2625423604347961,-1.837376564527069,-1.2648431700584368,-1.429909660441012,-2.1457762789396684,-1.416357075690583,-1.6733577905141361,-1.9479254763017546,-1.6085540431706149,-1.7285982903782136,-2.0166891576732402,-2.3003843721392392,-1.8471121050105261,-1.4416715708282528,-1.8742606811178864,-2.1994663793385758,-2.0003897626242173,-1.9914575064066489,-2.1882915376645244,-1.8813440833320132,-0.97063233832741613,-1.2300318797414007,-1.5714146253403061,-0.67599784961113474,-0.71834758467897053,-2.0082329410009505,-1.4008753990029437,-1.020479180776567,-1.2021971119954979,-1.0456587735485559,-1.4584730890001323,-0.98253408133727793,-0.8772488782638046,-1.4958796416434927,-0.91216622294114846,-1.3237830859255528,-1.3467220820641932,-1.4828002905517836,-1.4934459924892556,-1.4505781561468463,-1.0335096758265399,-1.7929402258649429,-1.1201088205891969,-1.5065342978187124,-1.4751252297366184,-1.4322770029659166,-0.91251117646897828,-0.81725534143677314,-1.8809030031154588,-0.70256806120146875,-0.98496724692405946,-1.0348894258232038,-0.63135492272077232,-1.2562095428551561,-1.3518657292257377,-0.89676928622628105,-1.1595737095338281,-0.65010637520929127,-1.0797355568142477,-1.9329678207596315],\"y\":[-1.376471224787492,-1.0927753879663866,-0.96729329774383932,0.26133056482719808,-1.5388211453585672,-1.1064484982030658,-1.1817469969195793,-1.0265945996918835,-0.42747861727283804,-1.2611922658170884,-0.76337578764470582,-1.1819479225714853,-0.95909246940387594,-1.0129099970787412,-0.28234806615321928,-0.73727410584941988,-0.96048494556277642,-1.0908922755273216,-0.26976922482251997,-0.89194484411117636,-1.1540849292423392,-0.5793876250925506,0.16361716635043824,0.074087885388676389,-0.41380056837702928,-0.83426643226006092,-1.4299025681994222,-1.0191045971238766,-1.4224474965770464,-0.92495839365650179,-0.9271914718701264,-1.5735239080083294,-0.82866911500298768,-1.2193990077827359,-1.4078697275067233,-0.35589067413493392,0.24327469983187849,0.10923017080247506,-0.98988204116034206,-1.2119694302999549,-0.36432685145246801,-0.16905147353136496,-0.61139341686176829,0.12688287818207072,-0.99337721427096282,-0.5658958445191592,-0.921455289771415,-0.043841236056990154,-1.0108115682779648,-0.44549168036951475,0.25175986859345134,-1.4012480941048135,-1.3024544238693758,-0.5829750934828335,-1.0167428059232342,0.72107810329157618,0.66237471258141067,-1.5967971040415123,-1.2865873918189066,-1.5890069304740231,-1.4093019815255861,-1.3433240620514151,-1.1482705146744523,0.68144652381368587,-1.6075299618679013,-0.19439480647331819,-1.6010354178657566,-1.1303337337906425,-0.2693922239708621,-0.51621353484749632,-0.92165919616111802,0.29156962097696432,-0.010810949995266739,-0.63805690194802711,-1.6258497605692079,-2.1852735983267957,0.11022690900864926,-0.56891035735433837,-1.1997920074405248,-1.1762405866791148,-1.0101133991558322,0.57492837936866503,-1.3024006738365299,-0.46328270333823102,-0.661826016352691,0.80808137795080526,-0.051739470980844783,-0.066115651499278505,-0.95540244917937023,-0.89761529671443518,-0.94383442586406907,0.91717869571096877,0.4972079875585837,-1.1840495823429116,-1.0356283446965846,-0.9323330712848853,-0.97963245947354904,0.085709549530496004,-1.1570407153050839,-1.2751866647614964,-0.56742825005369957,-1.3760630477979123,-1.2292424637901109,0.21567265450151193,-0.99616361772397588,-0.61164864672477548,0.54266942362895643,0.49301148096745673,0.31354705771346791,-0.41783572969320343,-0.78457544805899049,-0.62589995029179779,0.19750143174741966,-1.1076817823607057,0.82294250762904908,-0.46559093010272584,0.311649545186229,-1.4623352090018429,-0.45004183139832016,-1.0387748080873094,0.022169570158656796,-0.66447543121811969,0.18061714287181754,1.084114895082537,-0.49258607835205509,-0.1262066754904059,0.88649707366868413,-0.68439858964294698,-0.70477319991645948,0.23543072678494795,-1.603630314584926,-0.99442883566203022,0.41638606286596919,-0.82771873186878109,-1.4675706340139656,0.052845611423403653,-0.4165712351435033,-0.7567535561858888,0.45473022778978139,-1.2864118333431767,0.88828972250582672,-0.69721802066664573,-0.14713803564853364,-0.99916610473160983,-0.083399270170697662,-1.3828712695298617,-0.79427463596447101,0.88829219803146464,-1.2628633891521321,0.96798178216678854,-0.17341847758020354,-1.3393617574514176,-0.81188937988325205,-1.7168670918035907,0.0097606668714273724,-0.16928350127681119,-0.76790404600413398,0.12901341066405789,-0.14569949574252544,-0.68892425192175888,-0.19576733391989212,-0.053599389614964132,-0.13987247597796576,0.37624953625175689,0.13137787983227647,0.11405630547450109,0.74352693838004147,0.18799015178688416,0.31704884960011709,-0.61380324399840003,-1.2430115065501977,-0.34151526368311041,0.29740372336842769,0.38715745331175588,-0.14229354160347413,-1.0711927328586108,0.7081247702243747,-1.0131248082877211,-0.95008095987381225,-0.54507181900350654,0.59352705457546961,-1.2720783711868999,-0.71195560347991449,-1.3809667155578444,-0.46510397749239374,0.31334291180612445,-1.0950230538646903,-0.56110609210129736,0.36981748527669539,0.19134720072181538,0.48388576046616505,0.81382925896937675,-0.54693816743126145,-0.20174188326040579,0.83071682480619047,-1.4757650124414945,-0.25737007010122109,-0.62734175324019548,0.66848420160322908,-1.0443914576557487,-1.2519587260244893,0.92236205935635984,0.99337954000069184,-2.0936958412584818,-0.17534578147424151,0.46196488031750288,-0.53253755526416757,1.1026588023241453,-0.016713829912979362,0.11559896631117722,0.76470144798511963,-0.49563055773494752,-0.56436520765087805,0.052681394626807626,0.74260988131429928,0.01675848372428157,-0.39734935801416549,0.023237841251155047,-1.2954452841542561,-0.50874150275382191,-1.183830415667628,0.14189401941881882,0.15647021539584288,0.11349936359794988,-0.10494603911746893,0.14579407377482659,0.37554105209454336,0.72452712525958562,-0.47842104286564124,0.40755005942228151,-1.1885780290433683,-1.4198181947381443,0.62265384580853067,0.64498993073355115,-0.24641729529782133,-0.7042698182378474,-1.7890925185295561,-0.80481050914942875,-0.010433398587591554,0.031818776683478607,-0.61324247120745035,0.24407986544595728,0.30402010450640377,0.0072868788365035376,-1.2105254715653981,-0.5603519197479303,0.21506862224531187,-1.5907835096642804],\"text\":[\"Country: ARG<br>Decade: 1940\",\"Country: AUS<br>Decade: 1940\",\"Country: BEL<br>Decade: 1940\",\"Country: BLR<br>Decade: 1940\",\"Country: BOL<br>Decade: 1940\",\"Country: BRA<br>Decade: 1940\",\"Country: CAN<br>Decade: 1940\",\"Country: CHL<br>Decade: 1940\",\"Country: CHN<br>Decade: 1940\",\"Country: COL<br>Decade: 1940\",\"Country: CSK<br>Decade: 1940\",\"Country: CUB<br>Decade: 1940\",\"Country: DOM<br>Decade: 1940\",\"Country: ECU<br>Decade: 1940\",\"Country: EGY<br>Decade: 1940\",\"Country: ETH<br>Decade: 1940\",\"Country: FRA<br>Decade: 1940\",\"Country: GBR<br>Decade: 1940\",\"Country: GRC<br>Decade: 1940\",\"Country: HTI<br>Decade: 1940\",\"Country: IND<br>Decade: 1940\",\"Country: IRN<br>Decade: 1940\",\"Country: IRQ<br>Decade: 1940\",\"Country: ISR<br>Decade: 1940\",\"Country: LBN<br>Decade: 1940\",\"Country: LBR<br>Decade: 1940\",\"Country: LUX<br>Decade: 1940\",\"Country: MEX<br>Decade: 1940\",\"Country: MMR<br>Decade: 1940\",\"Country: NLD<br>Decade: 1940\",\"Country: NOR<br>Decade: 1940\",\"Country: NZL<br>Decade: 1940\",\"Country: PAK<br>Decade: 1940\",\"Country: PER<br>Decade: 1940\",\"Country: PHL<br>Decade: 1940\",\"Country: POL<br>Decade: 1940\",\"Country: RUS<br>Decade: 1940\",\"Country: SAU<br>Decade: 1940\",\"Country: SLV<br>Decade: 1940\",\"Country: SWE<br>Decade: 1940\",\"Country: SYR<br>Decade: 1940\",\"Country: THA<br>Decade: 1940\",\"Country: TUR<br>Decade: 1940\",\"Country: UKR<br>Decade: 1940\",\"Country: URY<br>Decade: 1940\",\"Country: USA<br>Decade: 1940\",\"Country: VEN<br>Decade: 1940\",\"Country: YUG<br>Decade: 1940\",\"Country: ZAF<br>Decade: 1940\",\"Country: AFG<br>Decade: 1950\",\"Country: ALB<br>Decade: 1950\",\"Country: ARG<br>Decade: 1950\",\"Country: AUS<br>Decade: 1950\",\"Country: AUT<br>Decade: 1950\",\"Country: BEL<br>Decade: 1950\",\"Country: BGR<br>Decade: 1950\",\"Country: BLR<br>Decade: 1950\",\"Country: BOL<br>Decade: 1950\",\"Country: BRA<br>Decade: 1950\",\"Country: CAN<br>Decade: 1950\",\"Country: CHL<br>Decade: 1950\",\"Country: COL<br>Decade: 1950\",\"Country: CRI<br>Decade: 1950\",\"Country: CSK<br>Decade: 1950\",\"Country: CUB<br>Decade: 1950\",\"Country: DNK<br>Decade: 1950\",\"Country: DOM<br>Decade: 1950\",\"Country: ECU<br>Decade: 1950\",\"Country: EGY<br>Decade: 1950\",\"Country: FRA<br>Decade: 1950\",\"Country: GBR<br>Decade: 1950\",\"Country: GHA<br>Decade: 1950\",\"Country: GRC<br>Decade: 1950\",\"Country: GTM<br>Decade: 1950\",\"Country: HND<br>Decade: 1950\",\"Country: HTI<br>Decade: 1950\",\"Country: HUN<br>Decade: 1950\",\"Country: IDN<br>Decade: 1950\",\"Country: IND<br>Decade: 1950\",\"Country: IRL<br>Decade: 1950\",\"Country: IRN<br>Decade: 1950\",\"Country: IRQ<br>Decade: 1950\",\"Country: ISL<br>Decade: 1950\",\"Country: ISR<br>Decade: 1950\",\"Country: ITA<br>Decade: 1950\",\"Country: JOR<br>Decade: 1950\",\"Country: JPN<br>Decade: 1950\",\"Country: KHM<br>Decade: 1950\",\"Country: LAO<br>Decade: 1950\",\"Country: LBN<br>Decade: 1950\",\"Country: LBR<br>Decade: 1950\",\"Country: LBY<br>Decade: 1950\",\"Country: MAR<br>Decade: 1950\",\"Country: MEX<br>Decade: 1950\",\"Country: MMR<br>Decade: 1950\",\"Country: MYS<br>Decade: 1950\",\"Country: NLD<br>Decade: 1950\",\"Country: NOR<br>Decade: 1950\",\"Country: NPL<br>Decade: 1950\",\"Country: NZL<br>Decade: 1950\",\"Country: PAK<br>Decade: 1950\",\"Country: PAN<br>Decade: 1950\",\"Country: PHL<br>Decade: 1950\",\"Country: POL<br>Decade: 1950\",\"Country: PRT<br>Decade: 1950\",\"Country: PRY<br>Decade: 1950\",\"Country: ROU<br>Decade: 1950\",\"Country: RUS<br>Decade: 1950\",\"Country: SAU<br>Decade: 1950\",\"Country: SDN<br>Decade: 1950\",\"Country: SLV<br>Decade: 1950\",\"Country: SWE<br>Decade: 1950\",\"Country: SYR<br>Decade: 1950\",\"Country: THA<br>Decade: 1950\",\"Country: TUN<br>Decade: 1950\",\"Country: TUR<br>Decade: 1950\",\"Country: UKR<br>Decade: 1950\",\"Country: URY<br>Decade: 1950\",\"Country: USA<br>Decade: 1950\",\"Country: VEN<br>Decade: 1950\",\"Country: YUG<br>Decade: 1950\",\"Country: ZAF<br>Decade: 1950\",\"Country: AFG<br>Decade: 1960\",\"Country: ALB<br>Decade: 1960\",\"Country: AUS<br>Decade: 1960\",\"Country: AUT<br>Decade: 1960\",\"Country: BDI<br>Decade: 1960\",\"Country: BEL<br>Decade: 1960\",\"Country: BEN<br>Decade: 1960\",\"Country: BFA<br>Decade: 1960\",\"Country: BOL<br>Decade: 1960\",\"Country: BRA<br>Decade: 1960\",\"Country: CAF<br>Decade: 1960\",\"Country: CAN<br>Decade: 1960\",\"Country: CHL<br>Decade: 1960\",\"Country: CHN<br>Decade: 1960\",\"Country: CIV<br>Decade: 1960\",\"Country: CMR<br>Decade: 1960\",\"Country: COD<br>Decade: 1960\",\"Country: CRI<br>Decade: 1960\",\"Country: CSK<br>Decade: 1960\",\"Country: CUB<br>Decade: 1960\",\"Country: CYP<br>Decade: 1960\",\"Country: ECU<br>Decade: 1960\",\"Country: EGY<br>Decade: 1960\",\"Country: ESP<br>Decade: 1960\",\"Country: FRA<br>Decade: 1960\",\"Country: GAB<br>Decade: 1960\",\"Country: GBR<br>Decade: 1960\",\"Country: GHA<br>Decade: 1960\",\"Country: GRC<br>Decade: 1960\",\"Country: GTM<br>Decade: 1960\",\"Country: HND<br>Decade: 1960\",\"Country: HTI<br>Decade: 1960\",\"Country: HUN<br>Decade: 1960\",\"Country: IDN<br>Decade: 1960\",\"Country: IND<br>Decade: 1960\",\"Country: IRN<br>Decade: 1960\",\"Country: ISL<br>Decade: 1960\",\"Country: ISR<br>Decade: 1960\",\"Country: ITA<br>Decade: 1960\",\"Country: JOR<br>Decade: 1960\",\"Country: JPN<br>Decade: 1960\",\"Country: KHM<br>Decade: 1960\",\"Country: LAO<br>Decade: 1960\",\"Country: LBN<br>Decade: 1960\",\"Country: LBR<br>Decade: 1960\",\"Country: LKA<br>Decade: 1960\",\"Country: MAR<br>Decade: 1960\",\"Country: MDG<br>Decade: 1960\",\"Country: MEX<br>Decade: 1960\",\"Country: MLT<br>Decade: 1960\",\"Country: MMR<br>Decade: 1960\",\"Country: MUS<br>Decade: 1960\",\"Country: MWI<br>Decade: 1960\",\"Country: MYS<br>Decade: 1960\",\"Country: NER<br>Decade: 1960\",\"Country: NGA<br>Decade: 1960\",\"Country: NIC<br>Decade: 1960\",\"Country: NLD<br>Decade: 1960\",\"Country: NPL<br>Decade: 1960\",\"Country: NZL<br>Decade: 1960\",\"Country: PAK<br>Decade: 1960\",\"Country: PER<br>Decade: 1960\",\"Country: PHL<br>Decade: 1960\",\"Country: POL<br>Decade: 1960\",\"Country: PRT<br>Decade: 1960\",\"Country: PRY<br>Decade: 1960\",\"Country: RUS<br>Decade: 1960\",\"Country: RWA<br>Decade: 1960\",\"Country: SAU<br>Decade: 1960\",\"Country: SDN<br>Decade: 1960\",\"Country: SEN<br>Decade: 1960\",\"Country: SGP<br>Decade: 1960\",\"Country: SLE<br>Decade: 1960\",\"Country: SLV<br>Decade: 1960\",\"Country: SWE<br>Decade: 1960\",\"Country: TCD<br>Decade: 1960\",\"Country: TGO<br>Decade: 1960\",\"Country: THA<br>Decade: 1960\",\"Country: TTO<br>Decade: 1960\",\"Country: TUR<br>Decade: 1960\",\"Country: UKR<br>Decade: 1960\",\"Country: URY<br>Decade: 1960\",\"Country: USA<br>Decade: 1960\",\"Country: YUG<br>Decade: 1960\",\"Country: ZAF<br>Decade: 1960\",\"Country: ZMB<br>Decade: 1960\",\"Country: ARG<br>Decade: 1970\",\"Country: BEL<br>Decade: 1970\",\"Country: BEN<br>Decade: 1970\",\"Country: BOL<br>Decade: 1970\",\"Country: CHL<br>Decade: 1970\",\"Country: COD<br>Decade: 1970\",\"Country: COG<br>Decade: 1970\",\"Country: ESP<br>Decade: 1970\",\"Country: FRA<br>Decade: 1970\",\"Country: GBR<br>Decade: 1970\",\"Country: GRD<br>Decade: 1970\",\"Country: GTM<br>Decade: 1970\",\"Country: HND<br>Decade: 1970\",\"Country: IND<br>Decade: 1970\",\"Country: ISL<br>Decade: 1970\",\"Country: ISR<br>Decade: 1970\",\"Country: JAM<br>Decade: 1970\",\"Country: LUX<br>Decade: 1970\",\"Country: MDG<br>Decade: 1970\",\"Country: NER<br>Decade: 1970\",\"Country: PER<br>Decade: 1970\",\"Country: PRT<br>Decade: 1970\",\"Country: PRY<br>Decade: 1970\",\"Country: SGP<br>Decade: 1970\",\"Country: TUN<br>Decade: 1970\",\"Country: UGA<br>Decade: 1970\",\"Country: URY<br>Decade: 1970\",\"Country: USA<br>Decade: 1970\",\"Country: VEN<br>Decade: 1970\",\"Country: ECU<br>Decade: 1980\",\"Country: ISL<br>Decade: 1980\",\"Country: PAN<br>Decade: 1980\",\"Country: PER<br>Decade: 1980\",\"Country: POL<br>Decade: 1980\",\"Country: RUS<br>Decade: 1980\",\"Country: SGP<br>Decade: 1980\",\"Country: USA<br>Decade: 1980\",\"Country: SLB<br>Decade: 1990\",\"Country: ISR<br>Decade: 2010\",\"Country: HUN<br>Decade: 2020\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(248,118,109,1)\",\"opacity\":0.80000000000000004,\"size\":7.559055118110237,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(248,118,109,1)\"}},\"hoveron\":\"points\",\"name\":\"1\",\"legendgroup\":\"1\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[-0.65853777229039723,-0.75598901746217984,-0.50743496546938849,-0.44902999867291898,-0.67209733192836452,-1.0820041055412557,-0.28172529745977315,-0.48992560927459305,-0.40774739077200428,-0.8844391141988992,-1.1550822344000151,-0.38667209635339228,-0.5401089983871894,-0.74392170843024175,0.70317305814564346,-0.5510881877087126,-0.50218069368743778,-0.75229588989580309,-0.50848325977651576,0.15354484852278474,-0.41734450430253134,-0.93216028951977903,0.34067746203069904,-0.015385817235918541,1.014167778148185,-0.127525472637183,-0.54385510233637102,1.0551432254005213,0.87036344817754652,1.0839603219044973,0.03140667827300965,-0.21397842257457209,0.062390331354999266,-0.6141840819363964,0.45415136352475971,1.242845060353742,-0.80457645192946459,-0.64346545856794468,1.1393000463551639,1.020048125658042,-0.42285949561020358,0.047484124084017879,-0.14897158075179376,1.0793339908535766,0.5941529304287978,0.99803143641700764,1.5930580703146715,1.064228145391829,0.29810063756290228,1.5863931474322295,-0.23447254584835997,1.2257657824952828,1.457968167426555,0.96335902131715445,0.91062045971511907,0.63895579970493244,1.5955888390200204,1.1463719829265424,0.5910070183845445,1.0129145034525568,1.1446516722693436,1.1261835458595535,-0.016812857873570185,0.082856206342797806,1.1867397236265314,-0.13955362171749094,0.38611660303284911,0.40878727115441854,1.4019340503839328,0.67373317582418157,0.9292500964636744,0.98994063223059892,2.0399927938558022,1.2959577818083501,0.73615482094775309,1.0248531461751034,1.423513239782773,0.3015758170504787,0.85148324992495483,0.87570690192819944,1.3486953656915566,1.7431502057623989,1.2723790236062955,-0.69057304470974512,1.998471254401605,1.1816740493583962,2.0479603317430204,1.2762919319218824,2.2275500885484676,1.7379895513882382,2.2323509106035764,1.2853112677682939,1.7760577811621348,0.2296491821768758,0.33074153297545383,1.6898990312582474,0.82378683669721442,0.49057545559880938,1.4563088422455444,1.6323386944371179,1.5345080953480219,0.81681129820426934,0.82848435825056033,1.6676461443758346,1.0796383287925642,1.5635129208510532,0.42518193497564755,2.0517065677415292,1.1165083488348102,0.64525242258302984,0.94702495914277507,1.7865530393075331,0.53540899070214532,0.84644447803677125,0.8606370320909178,1.1006287783208031,1.2650834717583039,0.69005813553602957,1.483341335730205,0.73878946678121515,0.82444738351397417,1.7609726554947831,1.9738980410475713,1.6446218267624844,1.4228200864102225,1.2377886596085956,0.78984978740671574,1.0246925832509575,0.30235065083057416,1.9637384083776566,1.5659372253760939,1.2299288520258247,0.98033025345337133,1.9695765143629576,0.66516912548130436,1.4640011044751835,0.74011607543585844,1.6256426153133843,1.1982958227153913,1.6944053710779672,1.782771058355878,0.47411539945356745,2.1124750762603153,1.0605823722863612,0.93788504858089394,-0.12160608325070645,1.1202992476660907,1.7089306128304094,1.435828781396048,1.2763483455070654,0.78027469397778471,1.6584378485191287,1.0820991384742238,1.3643362244263288,1.7495379653525518,0.60243756044913233,1.2222898675087466,1.5287895219129986,-0.029052653313922674,1.4028578395154732,2.2573091671366168,1.4657827811067494,0.33008129994404095,1.566482488225925,1.5245973593251894,1.0901507136521373,1.1587866665091313,1.7927506772396566,0.59527818496102503,1.977100319913647,2.5343435761434727,1.4132193268051527,1.3288403025424786,1.7938332052378081,1.0551005637918718,1.6509242570347531,1.3953216448926988,1.1701540507001165,-0.36705816806783509,0.66333751121494533,0.69630365162020302,1.0792554483393189,1.0887429131069044,0.71699664523625828,1.3369900352272917,1.4565741324999293,1.8025825483456543,1.4022943342337779,2.1670940954737694,1.7315503240787185,2.0940715257016853,1.6007339257055044,1.6259346851707983,0.21212088951557001,1.6367260088335069,1.3787013587652228,1.5928340885025114,-0.0061929302750688186,1.606641908632533,1.4476493185831976,1.5808380737072745,2.2144450167270158,1.6545212898563073,0.73672229338630113,0.75839767795178015,1.2080376440418974,0.34888725498258039,0.97782310717963405,0.66938782601617919,0.67385202136295264,1.9169794064772674,0.79491553214667565,0.43591531703878006,1.8461138662734393,2.4298643358069199,1.5370115911332876,1.8956218051201075,1.0938462744259145,1.1569405136641175,1.6412278095918118,1.1913561557001675,1.7610338411948729,1.8626356491869596,1.4483616311607097,1.3771228407254565,-0.49225350985096689,1.4918812691159982,1.0590965814145894,1.3061226410235718,1.049285683307982,1.0881375502743031,1.7866782135987356,0.49298226448046267,0.69428294987150707,0.75057638757906842,1.7943910222683443,0.42430288686013135,1.2923931488039229,1.9584975486873846,1.0243439166391823,0.37141030300418187,1.5299624743669642,1.101251937034432,0.36424879443276714,1.7146674284423407,0.26850055959404445,-0.61277118985566237,1.4249558922391374,1.7805256439902617,1.4983873108149484,-0.15555575566659058,1.6966211980679724,0.59986350954584777,1.1332089793535762,1.1474903674081753,2.239527497203337,2.113460199158347,1.3263835400914659],\"y\":[0.85363528258706289,0.42914655431508753,0.26825371591506575,0.27447861801302537,-0.042300496585017888,0.50812961467553897,0.71460299412694961,0.59076187579425421,0.57903863083152685,0.90847856913876879,0.66646705201601997,0.35297294460129741,0.1294631538904169,0.087579158157299858,0.79421753172418574,0.58621888380757026,0.19022930581389574,0.56628155718010653,0.30764139998014817,0.16058711149308724,-0.044570705657541454,0.63662875876809333,-0.28116831321792868,0.36841804608280077,1.656876381737509,0.63129461756414751,-0.12895351602051286,1.9911638350233707,0.62499875311004427,1.6262590539895807,0.40159187118235157,0.38930057873840873,-0.096191227012144803,-0.26686844599709686,0.6493404011904127,1.3836943011069978,0.69431218426313479,0.86160489176819333,1.8830161513976758,0.66205248355794122,-0.31168610821950554,0.046900721222594921,0.50961500430115458,-0.10579883333437749,0.15796336549100315,0.73818916888142916,0.47875977782245144,1.0848173920954509,0.0081179348865858016,0.94223909761086533,0.26161738134475943,1.6864717328375649,0.19660671664741916,0.66794129906973276,-0.19181090646516061,-0.68518503756893934,-0.16734911561460442,0.62704484757958379,0.40405287719154409,-0.30626783699425192,-0.05373248045486987,0.9352757687224772,-0.020836456019362928,0.27091544874512435,0.81891487939826435,-0.21701875745458124,0.3029176266784841,0.26680144959082647,1.0207132798765746,0.7964937981323339,1.6783160298856294,0.15106762388908285,0.82622928578394084,-0.035685434370021696,0.68543409637711961,1.0467178096916767,1.0405834958696976,0.28963527310087295,0.68342099793074629,0.068731556606973818,0.78216681501182928,1.4003775331505992,1.3141455597596878,0.49865563610320424,0.34918983139735388,1.5108902311108381,0.95150740574322223,0.95351779220896959,1.2621778361512479,1.0602097322974113,1.3159272020765775,2.0140068677998246,0.46497480715956807,-0.33335840400711736,0.34139370871465757,0.20497599829386295,0.26259567315236854,-0.19672853685669692,0.40619986850886625,1.158792470472328,0.41369598491478016,0.29290755483091685,0.2119604827754149,0.56793259020594766,0.54289439505283255,1.0627737575634839,0.098320352262896982,0.3288887588324923,-0.097811963187504736,-0.21583148697625179,0.003337819244960957,1.855441907998699,0.63310271933362805,0.37094671577357463,0.30743119795386042,0.99333356786532934,1.9879147685814935,0.36788365644812898,0.42700914554086628,0.44546059612879302,0.46303290963335925,0.55345497199659754,0.81240476671161288,1.7072701713213889,1.0144498069905385,1.4131923758585008,0.073136910131930147,1.4213764570954159,0.22893820056448169,1.441884933190881,1.36771454959088,0.52805713512995467,0.16886452704993415,0.2506750645436473,-0.097349754823518792,0.29971518776875261,-0.18041198674545977,0.48163705710399396,1.3030872429654068,0.53964046776733798,0.063457166591753419,-0.15260985179136996,0.42895087823680839,-0.096269843334814253,0.78021362616785306,0.26994479896537582,0.010678322090459219,-0.079279383659764002,1.0055115496788365,1.0989801887482578,-0.36239255861208453,0.16168925588240085,-0.068988503495480191,1.0965708477409681,0.49153596736889571,-0.23236358442804492,0.94513634753535403,1.2320081781287806,-0.0052977865745534028,-0.12023442310912157,0.84695336644652552,0.31852784767817027,-0.4476292272513514,0.067650745889961297,0.9767730667444593,1.1778452920723053,0.27519804596675362,0.11779438096620258,-0.56104305792804365,1.3642650938226315,0.54994384493527715,0.76265576897719134,-0.07912389761036237,-0.11832371740223487,1.0284869833213592,0.28229097832348593,0.12993804915864132,1.3040678854734264,-0.16330271723858522,-0.53530586519198275,0.010902460304695289,1.095773197292959,-0.29398040494086014,-0.1124580494218848,0.074820942619708883,0.52655453764622817,0.5794426955197044,0.39168529205486158,0.27917616617396968,0.26505878462229565,0.62530544259677179,1.1327176074988092,0.60378460413739909,-0.29792801858924534,0.97082290955208494,0.82882140995882969,0.1854526043712636,0.12274689123292419,-0.0049601988001834801,-0.12699260943149268,1.2411050006555842,0.74729178698617926,0.24037593778486288,-0.57641944658922584,0.1299939932223122,0.34684350882652026,-0.18228867008230584,0.22611590512198099,-0.20128715686468901,-0.5095979844353995,-0.12350517319530809,-0.56216257953638527,0.050467392960459517,-0.084884921939884325,0.51390427605332389,0.15101528203376693,0.09229229344418835,0.58252589210346384,0.35443337773668321,0.044460742065868808,-0.16951491936057869,0.58328719302313159,0.052140838288609027,0.14744752513114284,0.12011904191861734,-0.40279927727361303,0.0022911663003733415,-0.15741046893752791,0.79657694511248955,0.5221736066091196,-0.238886869473696,0.50001149576335424,-0.090445445322644438,-0.0083563874482013058,-0.3881001882897312,0.082370918190455694,-0.53452027936676172,-0.22239350758318999,0.036395452929042581,-0.26399424544005984,-0.65386962016260541,-0.036504881847899275,-0.14583151844234188,-0.62368595093408619,0.37026604717819001,0.45016541043470631,-0.0081150946494399374,0.50184718552325669,-0.042506971515029149,0.35297513499171279,0.065773032038532436,0.18831060548431824,-0.65085950505776291,0.096549100883591699,1.121092462059206,0.4546758924055444,0.11634651238447509,-0.23122230513255171],\"text\":[\"Country: DNK<br>Decade: 1940\",\"Country: DNK<br>Decade: 1960\",\"Country: JAM<br>Decade: 1960\",\"Country: AUS<br>Decade: 1970\",\"Country: CAN<br>Decade: 1970\",\"Country: CUB<br>Decade: 1970\",\"Country: FJI<br>Decade: 1970\",\"Country: HTI<br>Decade: 1970\",\"Country: IRL<br>Decade: 1970\",\"Country: ITA<br>Decade: 1970\",\"Country: LKA<br>Decade: 1970\",\"Country: NLD<br>Decade: 1970\",\"Country: PHL<br>Decade: 1970\",\"Country: SLV<br>Decade: 1970\",\"Country: TTO<br>Decade: 1970\",\"Country: ARG<br>Decade: 1980\",\"Country: AUS<br>Decade: 1980\",\"Country: BEL<br>Decade: 1980\",\"Country: BFA<br>Decade: 1980\",\"Country: BLZ<br>Decade: 1980\",\"Country: CHL<br>Decade: 1980\",\"Country: CUB<br>Decade: 1980\",\"Country: DOM<br>Decade: 1980\",\"Country: ESP<br>Decade: 1980\",\"Country: FIN<br>Decade: 1980\",\"Country: GBR<br>Decade: 1980\",\"Country: HND<br>Decade: 1980\",\"Country: IRL<br>Decade: 1980\",\"Country: JAM<br>Decade: 1980\",\"Country: JPN<br>Decade: 1980\",\"Country: KNA<br>Decade: 1980\",\"Country: LCA<br>Decade: 1980\",\"Country: MEX<br>Decade: 1980\",\"Country: NIC<br>Decade: 1980\",\"Country: NLD<br>Decade: 1980\",\"Country: NOR<br>Decade: 1980\",\"Country: PHL<br>Decade: 1980\",\"Country: SYC<br>Decade: 1980\",\"Country: THA<br>Decade: 1980\",\"Country: TTO<br>Decade: 1980\",\"Country: URY<br>Decade: 1980\",\"Country: VEN<br>Decade: 1980\",\"Country: WSM<br>Decade: 1980\",\"Country: ARG<br>Decade: 1990\",\"Country: ARM<br>Decade: 1990\",\"Country: AUT<br>Decade: 1990\",\"Country: AZE<br>Decade: 1990\",\"Country: BDI<br>Decade: 1990\",\"Country: BEL<br>Decade: 1990\",\"Country: BGD<br>Decade: 1990\",\"Country: BGR<br>Decade: 1990\",\"Country: BHR<br>Decade: 1990\",\"Country: BHS<br>Decade: 1990\",\"Country: BLR<br>Decade: 1990\",\"Country: BOL<br>Decade: 1990\",\"Country: BRA<br>Decade: 1990\",\"Country: BRB<br>Decade: 1990\",\"Country: BTN<br>Decade: 1990\",\"Country: CAF<br>Decade: 1990\",\"Country: CAN<br>Decade: 1990\",\"Country: CHL<br>Decade: 1990\",\"Country: CHN<br>Decade: 1990\",\"Country: COG<br>Decade: 1990\",\"Country: CSK<br>Decade: 1990\",\"Country: CZE<br>Decade: 1990\",\"Country: DEU<br>Decade: 1990\",\"Country: DJI<br>Decade: 1990\",\"Country: DMA<br>Decade: 1990\",\"Country: DNK<br>Decade: 1990\",\"Country: DZA<br>Decade: 1990\",\"Country: EGY<br>Decade: 1990\",\"Country: ERI<br>Decade: 1990\",\"Country: EST<br>Decade: 1990\",\"Country: FSM<br>Decade: 1990\",\"Country: GAB<br>Decade: 1990\",\"Country: GHA<br>Decade: 1990\",\"Country: GMB<br>Decade: 1990\",\"Country: GNQ<br>Decade: 1990\",\"Country: GRC<br>Decade: 1990\",\"Country: GRD<br>Decade: 1990\",\"Country: HUN<br>Decade: 1990\",\"Country: IDN<br>Decade: 1990\",\"Country: IRN<br>Decade: 1990\",\"Country: IRQ<br>Decade: 1990\",\"Country: JAM<br>Decade: 1990\",\"Country: JOR<br>Decade: 1990\",\"Country: JPN<br>Decade: 1990\",\"Country: KAZ<br>Decade: 1990\",\"Country: KEN<br>Decade: 1990\",\"Country: KGZ<br>Decade: 1990\",\"Country: KOR<br>Decade: 1990\",\"Country: KWT<br>Decade: 1990\",\"Country: LBR<br>Decade: 1990\",\"Country: LCA<br>Decade: 1990\",\"Country: LSO<br>Decade: 1990\",\"Country: LTU<br>Decade: 1990\",\"Country: LVA<br>Decade: 1990\",\"Country: MCO<br>Decade: 1990\",\"Country: MDV<br>Decade: 1990\",\"Country: MKD<br>Decade: 1990\",\"Country: MLI<br>Decade: 1990\",\"Country: MLT<br>Decade: 1990\",\"Country: MMR<br>Decade: 1990\",\"Country: MUS<br>Decade: 1990\",\"Country: MYS<br>Decade: 1990\",\"Country: NER<br>Decade: 1990\",\"Country: NGA<br>Decade: 1990\",\"Country: NOR<br>Decade: 1990\",\"Country: NZL<br>Decade: 1990\",\"Country: PAN<br>Decade: 1990\",\"Country: PHL<br>Decade: 1990\",\"Country: PNG<br>Decade: 1990\",\"Country: POL<br>Decade: 1990\",\"Country: ROU<br>Decade: 1990\",\"Country: RUS<br>Decade: 1990\",\"Country: RWA<br>Decade: 1990\",\"Country: SAU<br>Decade: 1990\",\"Country: SEN<br>Decade: 1990\",\"Country: SUR<br>Decade: 1990\",\"Country: SWE<br>Decade: 1990\",\"Country: TGO<br>Decade: 1990\",\"Country: THA<br>Decade: 1990\",\"Country: TJK<br>Decade: 1990\",\"Country: TUN<br>Decade: 1990\",\"Country: UGA<br>Decade: 1990\",\"Country: UZB<br>Decade: 1990\",\"Country: VCT<br>Decade: 1990\",\"Country: VNM<br>Decade: 1990\",\"Country: YUG<br>Decade: 1990\",\"Country: ZAF<br>Decade: 1990\",\"Country: ZMB<br>Decade: 1990\",\"Country: AFG<br>Decade: 2000\",\"Country: AGO<br>Decade: 2000\",\"Country: ALB<br>Decade: 2000\",\"Country: ARG<br>Decade: 2000\",\"Country: AZE<br>Decade: 2000\",\"Country: BEL<br>Decade: 2000\",\"Country: BGR<br>Decade: 2000\",\"Country: BHR<br>Decade: 2000\",\"Country: BIH<br>Decade: 2000\",\"Country: BTN<br>Decade: 2000\",\"Country: CAF<br>Decade: 2000\",\"Country: CHN<br>Decade: 2000\",\"Country: CIV<br>Decade: 2000\",\"Country: COG<br>Decade: 2000\",\"Country: COM<br>Decade: 2000\",\"Country: DJI<br>Decade: 2000\",\"Country: DNK<br>Decade: 2000\",\"Country: DZA<br>Decade: 2000\",\"Country: EGY<br>Decade: 2000\",\"Country: FRA<br>Decade: 2000\",\"Country: GAB<br>Decade: 2000\",\"Country: GEO<br>Decade: 2000\",\"Country: GIN<br>Decade: 2000\",\"Country: HUN<br>Decade: 2000\",\"Country: IDN<br>Decade: 2000\",\"Country: IRN<br>Decade: 2000\",\"Country: IRQ<br>Decade: 2000\",\"Country: ISR<br>Decade: 2000\",\"Country: ITA<br>Decade: 2000\",\"Country: JPN<br>Decade: 2000\",\"Country: KAZ<br>Decade: 2000\",\"Country: KEN<br>Decade: 2000\",\"Country: KGZ<br>Decade: 2000\",\"Country: LAO<br>Decade: 2000\",\"Country: LBN<br>Decade: 2000\",\"Country: LBR<br>Decade: 2000\",\"Country: LSO<br>Decade: 2000\",\"Country: LUX<br>Decade: 2000\",\"Country: MAR<br>Decade: 2000\",\"Country: MDA<br>Decade: 2000\",\"Country: MDG<br>Decade: 2000\",\"Country: MKD<br>Decade: 2000\",\"Country: MLT<br>Decade: 2000\",\"Country: MRT<br>Decade: 2000\",\"Country: MUS<br>Decade: 2000\",\"Country: NZL<br>Decade: 2000\",\"Country: OMN<br>Decade: 2000\",\"Country: PAK<br>Decade: 2000\",\"Country: POL<br>Decade: 2000\",\"Country: PRT<br>Decade: 2000\",\"Country: QAT<br>Decade: 2000\",\"Country: ROU<br>Decade: 2000\",\"Country: SLE<br>Decade: 2000\",\"Country: SMR<br>Decade: 2000\",\"Country: SOM<br>Decade: 2000\",\"Country: SVK<br>Decade: 2000\",\"Country: SVN<br>Decade: 2000\",\"Country: TGO<br>Decade: 2000\",\"Country: THA<br>Decade: 2000\",\"Country: TKM<br>Decade: 2000\",\"Country: TUN<br>Decade: 2000\",\"Country: UZB<br>Decade: 2000\",\"Country: VAT<br>Decade: 2000\",\"Country: VNM<br>Decade: 2000\",\"Country: YEM<br>Decade: 2000\",\"Country: YUG<br>Decade: 2000\",\"Country: ZWE<br>Decade: 2000\",\"Country: AGO<br>Decade: 2010\",\"Country: AZE<br>Decade: 2010\",\"Country: BHR<br>Decade: 2010\",\"Country: BIH<br>Decade: 2010\",\"Country: CAF<br>Decade: 2010\",\"Country: CHE<br>Decade: 2010\",\"Country: COM<br>Decade: 2010\",\"Country: CYP<br>Decade: 2010\",\"Country: DEU<br>Decade: 2010\",\"Country: DZA<br>Decade: 2010\",\"Country: GNB<br>Decade: 2010\",\"Country: GNQ<br>Decade: 2010\",\"Country: IDN<br>Decade: 2010\",\"Country: ISL<br>Decade: 2010\",\"Country: JOR<br>Decade: 2010\",\"Country: JPN<br>Decade: 2010\",\"Country: KAZ<br>Decade: 2010\",\"Country: KHM<br>Decade: 2010\",\"Country: KOR<br>Decade: 2010\",\"Country: LBN<br>Decade: 2010\",\"Country: LBY<br>Decade: 2010\",\"Country: LKA<br>Decade: 2010\",\"Country: LUX<br>Decade: 2010\",\"Country: MDA<br>Decade: 2010\",\"Country: MLI<br>Decade: 2010\",\"Country: MOZ<br>Decade: 2010\",\"Country: MRT<br>Decade: 2010\",\"Country: MYS<br>Decade: 2010\",\"Country: NAM<br>Decade: 2010\",\"Country: NLD<br>Decade: 2010\",\"Country: OMN<br>Decade: 2010\",\"Country: SDN<br>Decade: 2010\",\"Country: SRB<br>Decade: 2010\",\"Country: TKM<br>Decade: 2010\",\"Country: TUN<br>Decade: 2010\",\"Country: TUR<br>Decade: 2010\",\"Country: UKR<br>Decade: 2010\",\"Country: UZB<br>Decade: 2010\",\"Country: VNM<br>Decade: 2010\",\"Country: ZAF<br>Decade: 2010\",\"Country: ARE<br>Decade: 2020\",\"Country: ARM<br>Decade: 2020\",\"Country: BLR<br>Decade: 2020\",\"Country: CAF<br>Decade: 2020\",\"Country: CHN<br>Decade: 2020\",\"Country: CUB<br>Decade: 2020\",\"Country: EGY<br>Decade: 2020\",\"Country: IRN<br>Decade: 2020\",\"Country: ISR<br>Decade: 2020\",\"Country: MAR<br>Decade: 2020\",\"Country: OMN<br>Decade: 2020\",\"Country: PAK<br>Decade: 2020\",\"Country: RUS<br>Decade: 2020\",\"Country: SDN<br>Decade: 2020\",\"Country: SRB<br>Decade: 2020\",\"Country: STP<br>Decade: 2020\",\"Country: SYR<br>Decade: 2020\",\"Country: TKM<br>Decade: 2020\",\"Country: TUN<br>Decade: 2020\",\"Country: TUR<br>Decade: 2020\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(124,174,0,1)\",\"opacity\":0.80000000000000004,\"size\":7.559055118110237,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(124,174,0,1)\"}},\"hoveron\":\"points\",\"name\":\"2\",\"legendgroup\":\"2\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[-1.7416189632656076,-0.93472423321589959,-1.6843425002625438,-1.473813290016931,-1.1104398615166822,-1.0786626853456351,-1.3257672414369985,-1.1378778225068344,-1.6268012737958815,-1.2747495813839835,-0.84520968422098852,-0.76703855923226627,-0.76640032161988136,-1.1745917042586733,-1.6243534307522129,-0.84128344458127968,-0.43447426032292885,-1.3231008539855116,-1.1147588617199122,-0.28217030907977753,-1.0879626305832915,-0.90263642712429026,-1.3037787745845497,-0.41518595670271274,-0.59421674806947422,-0.97309038070643705,-0.97412364230298232,-0.96811956575338076,-1.1737439744943918,-0.88693386444785083,0.46124010892436917,-0.61331365986163755,-0.58914348248272075,0.12927908726325948,-0.98829029293901371,-1.0772664513339205,-0.90996261333898854,-0.46237948433435538,-1.1584750481781634,-0.46107464260887476,0.10605480936199736,-0.75225699672769208,-1.3302936191496622,-0.57184382905311559,-1.3700763880930424,-0.82181758559831453,-0.60207208331811124,-0.51754822117244914,-0.78996656906596618,-1.1177901358375286,-0.48246999701344268,-0.66083712796376004,-0.90821125869530195,-1.4258758085083445,-0.53639635672530639,0.018699817868607912,-0.6984932474962634,-0.35195806276122343,-0.66621253383150658,-0.17153636284329365,-0.57583458659458109,-0.097033162501503456,-0.68830281203293353,-1.3482515071726671,-0.39491460795945788,-0.8787212381085151,-0.014639757291410423,-1.1080498288155189,-0.64045358246956574,-0.1375466139422902,-1.4371572669525461,-0.60198855458439837,-1.1330303315415873,-0.65105323447079633,-1.2692615759143602,-1.2768569751682399,-1.281253098191139,-0.38682832963534564,-0.51445980841125949,-1.1033401978512256,0.48202629115302431,0.15729612951095368,-0.83948826369920138,-0.37971466973946677,0.6015138787229608,-0.63120389940379196,0.12804798083458871,0.60830859343798616,-1.108437291377824,0.2129754816094247,-0.92844059450428196,-0.036734864483245359,0.1394756502050763,-0.1095257527844174,-1.3087026976144616,0.16792645636876496,0.66022112917554177,0.83685270582956983,0.37011449508997413,0.67829173506397578,0.63878064890100217,0.042267251408287444,0.61428567313111238,-0.17345713917766267,-1.3733127567943717,-0.060476822641802132,-0.63276286375263469,0.62869021553562809,0.36893977385322535,-0.27387954337086995,-0.10412150124305025,0.37595029221957921,-1.3097159930222322,0.30314513110929925,-0.57011642005007435,0.092723148496930391,-0.57816667825459345,0.91174526881195395,0.43497871941834115,-0.6602929240163754,0.70008012479770976,-0.82461945607813836,-0.48203678837676278,-0.39844934526224823,0.12236018444244347,0.39800530051435307,-0.28629330695089816,0.16666734890637841,0.26721998002357444,0.42698307195785451,-0.04652119195135087,-0.030616118412286297,-0.057966146024525003,-0.068046959042801711,0.12186466318963196,0.20618120496615444,-0.14566578772421551,-0.054652097771657991,-0.089109355868890641,0.57805101324251906,0.47699867912836941,-0.0092069298080204188,-1.112110694756516,-0.2256534395876218,0.94707694044748048,-0.59415904598732183,0.3177231389045157,-0.44839927099475996,-0.038936719657313101,0.036499249121302861,-0.36848786070351858,-0.35091383401662596,-0.025347561639839634,-0.14503129163867354,0.141474371455167,-0.26447085460921127,0.57158981050730573,0.57251576862950726,0.43844553735147768,0.6733101099077714,0.25682389994680949,0.70598292223930281,0.65333500303354142,0.72272197389702986,0.78205859225603758,0.30966442104575381,0.18554933504377324,0.52316041208850383,0.63738025738561199,0.2426168148008582,0.85400343378530186,0.20688745042319143,0.55709515405457621,0.14420801744566247,-0.30584691322043828,0.56483572692278794,0.66079448730315304,0.7816406522822954],\"y\":[1.3491017984578417,1.4216971076858087,1.3274863203377465,1.3887769973310249,1.3474457685124497,1.3728058243477292,1.7139737751739799,0.97102933075463016,1.5380964739296934,1.1658832575860845,1.3460154373860993,2.0581466524852248,2.0661099732674977,2.440419173451382,2.1320424610068458,1.6945835079405505,1.1839723512020122,1.5295498508512626,1.1428650331039605,1.98238718282932,2.4091460612463944,2.2398137611545965,2.4664139571447361,2.1831022860019877,2.1819056165222439,2.4705666086615774,2.1211219589180983,1.9836483472888442,1.3280960815614218,1.8324398644211632,1.2661108920254553,1.845204830211987,2.1854750107767011,0.94008872993686543,1.3093362493279688,1.8246454139105988,1.8239386093920051,1.3142840166993268,2.105408253385237,1.9177900986456498,0.74689992928353266,2.4373814602149571,2.2032772533737335,1.7514582513456214,2.2315132686064407,1.3434311236507621,1.275744466986652,2.7984082519254962,1.8013641202738893,2.5402156036335781,1.3088555611648018,2.3885197372925839,2.5806350914056231,1.7197804088365576,1.3130439679471275,2.6275183579601116,1.9479581587903234,1.0314608506629781,1.4949344550020789,1.3390725955956748,1.6626624480537524,2.458538315741861,1.7535213880256879,1.5589978584494719,2.2499751257878837,1.3463577818120931,1.9579841711080241,2.2855329620778062,1.3863075281027859,1.6057794033136503,2.1218203691962456,2.1470761922067005,1.9837006690791235,1.2687226583971771,2.2010352750548954,1.8266301446704236,2.0764451521396241,2.8874831345290941,3.1031092335703763,2.3721160287282403,2.2515314595296108,2.3720251607496383,1.7700074157413648,1.4901165359770527,1.8658354757360804,2.135944157654416,2.1480267018974928,0.90666027089092116,1.5308983600229935,1.5985395091451395,1.3617331895941851,1.7247673679124214,2.0574381840433196,2.249766681570974,1.3882223590363587,2.2807670730945908,2.5089979027583191,1.82857671577162,2.624594224319396,2.2475055450155943,1.414103805093579,2.2790981854565717,1.5421363159794781,1.2407274116777913,1.2754148997294981,0.99932172689223409,2.0368271815106169,2.5546463950808187,1.6036314804451848,2.525889869077838,0.99718148991634714,2.4034474746816792,2.628104912770489,2.4812300362723225,1.5402044038595488,1.3677234377900429,1.953937073880589,2.0643562568996896,1.5584585337714953,1.0998578726267516,2.0272889032772357,2.3791657592620572,2.2442691133140888,2.4219634635389786,1.6780512369757656,1.7949941782446555,1.6673935242802218,1.4185674272194693,2.4563579406397977,2.2535779140215353,0.90891380160576696,1.9629234177056272,1.7531034753202632,1.929859082431179,2.3325049363805679,1.3656069267906401,1.921577573418737,1.2543707557218564,2.2660688653943226,1.2442438156681943,1.2637423177131144,2.5820097012340928,0.89580496615698602,1.7479082747882275,2.3181561570882914,1.415590374796913,1.968260735629825,2.481048752088745,2.9348261276829333,1.8639976038080206,1.6273644180325009,2.0809531881163106,1.2879901306941344,1.5942570449787516,0.81726466618083859,1.3139706249175858,1.0500387169365748,1.6272600047792209,2.2984561880689052,1.3746746182449538,1.1976813046599912,1.9398475764096075,0.95269902009517837,1.0842343298229327,1.5217075501227111,1.9620118223779783,0.8093217115543917,1.4457054826012796,1.2614780647283457,1.1751052586952597,0.97963772297982032,1.3175735263673531,1.7173101067212111,1.2921884364584888,1.5104455999852138,1.0167455392182001,1.1952736725501196,1.1606652761184166],\"text\":[\"Country: GIN<br>Decade: 1950\",\"Country: YEM<br>Decade: 1950\",\"Country: BGR<br>Decade: 1960\",\"Country: GIN<br>Decade: 1960\",\"Country: GMB<br>Decade: 1960\",\"Country: IRQ<br>Decade: 1960\",\"Country: KEN<br>Decade: 1960\",\"Country: KWT<br>Decade: 1960\",\"Country: MNG<br>Decade: 1960\",\"Country: SYR<br>Decade: 1960\",\"Country: YEM<br>Decade: 1960\",\"Country: YMD<br>Decade: 1960\",\"Country: AFG<br>Decade: 1970\",\"Country: AGO<br>Decade: 1970\",\"Country: ALB<br>Decade: 1970\",\"Country: ARE<br>Decade: 1970\",\"Country: AUT<br>Decade: 1970\",\"Country: BDI<br>Decade: 1970\",\"Country: BFA<br>Decade: 1970\",\"Country: BGD<br>Decade: 1970\",\"Country: BGR<br>Decade: 1970\",\"Country: BHR<br>Decade: 1970\",\"Country: BLR<br>Decade: 1970\",\"Country: BTN<br>Decade: 1970\",\"Country: BWA<br>Decade: 1970\",\"Country: CHN<br>Decade: 1970\",\"Country: CIV<br>Decade: 1970\",\"Country: CMR<br>Decade: 1970\",\"Country: COM<br>Decade: 1970\",\"Country: CSK<br>Decade: 1970\",\"Country: DNK<br>Decade: 1970\",\"Country: EGY<br>Decade: 1970\",\"Country: ETH<br>Decade: 1970\",\"Country: FIN<br>Decade: 1970\",\"Country: GHA<br>Decade: 1970\",\"Country: GRC<br>Decade: 1970\",\"Country: IDN<br>Decade: 1970\",\"Country: IRN<br>Decade: 1970\",\"Country: IRQ<br>Decade: 1970\",\"Country: JOR<br>Decade: 1970\",\"Country: JPN<br>Decade: 1970\",\"Country: KEN<br>Decade: 1970\",\"Country: KHM<br>Decade: 1970\",\"Country: KWT<br>Decade: 1970\",\"Country: LAO<br>Decade: 1970\",\"Country: LBN<br>Decade: 1970\",\"Country: LBR<br>Decade: 1970\",\"Country: LBY<br>Decade: 1970\",\"Country: LSO<br>Decade: 1970\",\"Country: MAR<br>Decade: 1970\",\"Country: MMR<br>Decade: 1970\",\"Country: MNG<br>Decade: 1970\",\"Country: MOZ<br>Decade: 1970\",\"Country: MRT<br>Decade: 1970\",\"Country: MUS<br>Decade: 1970\",\"Country: MYS<br>Decade: 1970\",\"Country: NGA<br>Decade: 1970\",\"Country: NOR<br>Decade: 1970\",\"Country: PAK<br>Decade: 1970\",\"Country: PNG<br>Decade: 1970\",\"Country: POL<br>Decade: 1970\",\"Country: QAT<br>Decade: 1970\",\"Country: ROU<br>Decade: 1970\",\"Country: RUS<br>Decade: 1970\",\"Country: RWA<br>Decade: 1970\",\"Country: SAU<br>Decade: 1970\",\"Country: SDN<br>Decade: 1970\",\"Country: SEN<br>Decade: 1970\",\"Country: SLE<br>Decade: 1970\",\"Country: SWE<br>Decade: 1970\",\"Country: SYC<br>Decade: 1970\",\"Country: SYR<br>Decade: 1970\",\"Country: TCD<br>Decade: 1970\",\"Country: THA<br>Decade: 1970\",\"Country: TUR<br>Decade: 1970\",\"Country: TZA<br>Decade: 1970\",\"Country: UKR<br>Decade: 1970\",\"Country: YEM<br>Decade: 1970\",\"Country: YMD<br>Decade: 1970\",\"Country: ZMB<br>Decade: 1970\",\"Country: AFG<br>Decade: 1980\",\"Country: AGO<br>Decade: 1980\",\"Country: ALB<br>Decade: 1980\",\"Country: BDI<br>Decade: 1980\",\"Country: BGD<br>Decade: 1980\",\"Country: BGR<br>Decade: 1980\",\"Country: BHR<br>Decade: 1980\",\"Country: BHS<br>Decade: 1980\",\"Country: BLR<br>Decade: 1980\",\"Country: BTN<br>Decade: 1980\",\"Country: BWA<br>Decade: 1980\",\"Country: CAF<br>Decade: 1980\",\"Country: CHN<br>Decade: 1980\",\"Country: CMR<br>Decade: 1980\",\"Country: COG<br>Decade: 1980\",\"Country: CYP<br>Decade: 1980\",\"Country: DJI<br>Decade: 1980\",\"Country: DNK<br>Decade: 1980\",\"Country: EGY<br>Decade: 1980\",\"Country: ETH<br>Decade: 1980\",\"Country: FJI<br>Decade: 1980\",\"Country: GIN<br>Decade: 1980\",\"Country: GMB<br>Decade: 1980\",\"Country: GNQ<br>Decade: 1980\",\"Country: GRC<br>Decade: 1980\",\"Country: GUY<br>Decade: 1980\",\"Country: HUN<br>Decade: 1980\",\"Country: IDN<br>Decade: 1980\",\"Country: IND<br>Decade: 1980\",\"Country: IRQ<br>Decade: 1980\",\"Country: ISR<br>Decade: 1980\",\"Country: KEN<br>Decade: 1980\",\"Country: KHM<br>Decade: 1980\",\"Country: KWT<br>Decade: 1980\",\"Country: LBN<br>Decade: 1980\",\"Country: LBR<br>Decade: 1980\",\"Country: LBY<br>Decade: 1980\",\"Country: LKA<br>Decade: 1980\",\"Country: LUX<br>Decade: 1980\",\"Country: MLI<br>Decade: 1980\",\"Country: MMR<br>Decade: 1980\",\"Country: MNG<br>Decade: 1980\",\"Country: MOZ<br>Decade: 1980\",\"Country: MRT<br>Decade: 1980\",\"Country: MWI<br>Decade: 1980\",\"Country: MYS<br>Decade: 1980\",\"Country: NER<br>Decade: 1980\",\"Country: NPL<br>Decade: 1980\",\"Country: OMN<br>Decade: 1980\",\"Country: PAK<br>Decade: 1980\",\"Country: PNG<br>Decade: 1980\",\"Country: PRT<br>Decade: 1980\",\"Country: ROU<br>Decade: 1980\",\"Country: RWA<br>Decade: 1980\",\"Country: SAU<br>Decade: 1980\",\"Country: SDN<br>Decade: 1980\",\"Country: SEN<br>Decade: 1980\",\"Country: SLE<br>Decade: 1980\",\"Country: SUR<br>Decade: 1980\",\"Country: SWE<br>Decade: 1980\",\"Country: SWZ<br>Decade: 1980\",\"Country: SYR<br>Decade: 1980\",\"Country: TGO<br>Decade: 1980\",\"Country: TUN<br>Decade: 1980\",\"Country: TUR<br>Decade: 1980\",\"Country: TZA<br>Decade: 1980\",\"Country: UGA<br>Decade: 1980\",\"Country: VNM<br>Decade: 1980\",\"Country: YEM<br>Decade: 1980\",\"Country: YUG<br>Decade: 1980\",\"Country: ZAF<br>Decade: 1980\",\"Country: ZWE<br>Decade: 1980\",\"Country: AFG<br>Decade: 1990\",\"Country: AGO<br>Decade: 1990\",\"Country: BWA<br>Decade: 1990\",\"Country: COD<br>Decade: 1990\",\"Country: GIN<br>Decade: 1990\",\"Country: GNB<br>Decade: 1990\",\"Country: KHM<br>Decade: 1990\",\"Country: LAO<br>Decade: 1990\",\"Country: LBN<br>Decade: 1990\",\"Country: LBY<br>Decade: 1990\",\"Country: LUX<br>Decade: 1990\",\"Country: MDA<br>Decade: 1990\",\"Country: PRT<br>Decade: 1990\",\"Country: SYR<br>Decade: 1990\",\"Country: WSM<br>Decade: 1990\",\"Country: YEM<br>Decade: 1990\",\"Country: ZWE<br>Decade: 1990\",\"Country: CYP<br>Decade: 2000\",\"Country: GNB<br>Decade: 2000\",\"Country: LBY<br>Decade: 2000\",\"Country: SYR<br>Decade: 2000\",\"Country: IRN<br>Decade: 2010\",\"Country: PSE<br>Decade: 2010\",\"Country: QAT<br>Decade: 2010\",\"Country: SYR<br>Decade: 2010\",\"Country: YEM<br>Decade: 2010\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(0,191,196,1)\",\"opacity\":0.80000000000000004,\"size\":7.559055118110237,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,191,196,1)\"}},\"hoveron\":\"points\",\"name\":\"3\",\"legendgroup\":\"3\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[-1.4388184281705974,-0.76927892496802341,-0.23355071808652769,-0.30809429216091017,-0.36953714019127276,-0.45311086593491967,-0.05296595056991095,-0.37737063931382775,0.11841196143270057,0.62135593128686639,0.51182552456212049,0.27832533488695493,-0.59936737893430858,0.91434589600598237,-0.27608251200472989,1.2136289907950297,1.3915222599166279,-0.1434338668445862,-0.40438038490366979,0.035353666529862944,-0.34527851700774864,1.9266113474176336,-0.34965600538701097,0.27619428832191723,1.7124987057809704,1.9171917698845118,1.8085493108088448,2.0793150110708107,-0.56454184814682384,0.11827928500846434,1.6236561517320851,-0.20668428341620756,0.53751036131999785,0.88266617926555302,0.04497167099948178,1.3972558075009354,0.77823596130069139,1.6781402789772244,0.21995355472330949,2.1378875746120545,0.91895646722200197,0.21026643402116263,-1.1285663897679281,0.71566827035601832,-0.26130852385736592,1.6774852718766537,0.57553011723538872,0.85337797048906394,0.8369205908409757,1.6921632662319237,1.907270886647443,1.7201727382177978,1.202954471991706,2.2951701956450923,1.4782892749179743,1.5181591230926452,1.7180627897062783,1.637673624491419,2.0588694557208886,1.2336559047018132,0.88623892435211959,-0.070746970700945128,0.76950582505233356,1.9718557726158177,0.693434527708778,1.1132375270532788,0.27563958274933881,1.9342990073342761,1.6067075317455886,1.1252675959004266,1.7607088827911717,2.1298202951623897,1.5446020453698408,0.24142555552613948,0.1405338189490406,1.5533602730097356,-0.63378796561514705,1.3652102744775003,1.5375292308448929,-1.0672040906351083,1.1644575133370791,0.29801585689223886,1.1235265311220792,1.7824246950309617,0.11833406082726212,1.4454826230976396,1.856885459782456,1.6488576280873402,2.1134446622779151,0.13019027022106169,0.72794967172394398,-0.48904622751860588,0.70221959938196654,-0.4780723782791616,2.1810482028876295,1.0576931856393457,1.3939342437558713,1.9450325646551863,0.44527891037423611,1.7527478233364602,1.0741943801963076,-0.031284529600116961,-0.5450741982729469,0.30310504751134487,2.0265834653520871,0.44778672219397131,0.45872315439043421,1.020864129305411,0.56651168415955933,1.2327133338964538,0.56546217278619493,0.0085283486778122246,0.35175705295576348,1.6593662410195149,0.8031636865351649,0.14977542126386426,1.5224749101465176,1.5142772945268337,0.90437849705687889,1.1754789841304472,0.4964208394995443,1.719025720356397,1.0981735193144386,1.5154023894290645,1.9914871530279552,1.9933161438983438,1.5877402333752493,2.279128037063392,1.9218593162229285,0.75550160436418279,2.0768172273459116,0.37521074388348574,1.8378228186256127,-0.42405139540930559,1.36192450734851,0.74444657808652637,1.8171376306878726,1.7169076020270115,1.7756228406031389,0.96848137873849305,1.3599760103259539,2.1352002129221783,1.2408149627940381,0.32319125744214999,1.0923672364187307,1.8228267547776797,1.8056311237740414,1.1361472387319458,0.25879500072198564,2.3698821143519324,0.7637637265807995,1.496497825286049,1.2634209504588629,0.99702955929108361,1.5260847670042716,1.7171318605980395,1.4491032862623021,1.849730734418974,2.0388381085993399,1.5435132348955263,2.4767704529216332,2.1702908603961761,-0.032171421627027449,-0.1471119966660896,0.71293651514287937,-0.48337101584730413,1.7571220986588876,1.490058752303568,1.0876114823329819,0.29923736204546586,-0.17617008199283971,1.976536654626077,1.694464993944198,1.8791786136215263,1.4075883554606619,1.9260457170733698,2.1815927057482662,1.0443012510265535,1.6144430264836347,-0.75142053439167256,0.59672917175257789,0.075090691540769847,1.644527449290123,1.2057431518581285,0.15886395039354562,1.2661774515898427,-0.079248462800959388,0.95652342148225467,-0.33216119162680935,1.2011797020274861,1.7175834917632657,1.5765895543953254,1.1330400622819867,0.89950194991953836,1.124216728025045,1.0469789805689924,1.7024189463307251,0.4712802287081454,0.7661536521281116,1.3372871721283845,-0.70207008868039356,2.2983753111453136,0.3951808248282298,2.0993383731272504,1.5321435251973616,2.0517408056746662,0.54961399794013521,0.76422014254190451,0.24230789810602379,1.865800699741287,1.3710288408774269,0.16523873888911461,1.1142099742925928,2.4483249112185717,2.0782160608750768,2.0137016941158645,1.7509803809729942,1.7159684466546226,1.5302969309542904,1.5484512360245981,1.3389118537826894,2.2179434553903028,0.71858945685395215,2.0431648035511478,1.3921916864097921,1.1205389086175952,1.7407551219252859,1.3141426277126582,1.2450395190627341,2.1690900937698552,1.3960080212604409,0.55911567669446527,1.7365458181587874,1.9511336957904442,1.2521321084906678,1.9035707577474512,2.4513885820546624,0.96726433519703625,1.0733189210062242,1.1010831265105279,2.7417611384369183,0.58141999122359911,0.14110087876960095,2.1428475228371235,1.7285860967638393,0.28340248134835455,1.0976818436339406,1.9161830030814777,0.81583884668512474,1.7101392613136022,1.7675913792752953,2.1151651088664081,1.9728230040961006,1.9429887610521257,2.4685547363294682,-1.3267185960678893,2.4880909831640237,2.0521508769981409,1.9820695784714328,0.15748969937885535,0.90382359679862545,2.529522373726389,1.7876577774724733,1.7494232833887464,2.1486955434925514,2.0059488476353526,1.2867765353476517,2.2557199137990196,1.2573301627056801,0.22340924359786316,-0.084594007891126505,0.79344194183658878,0.9433951573883147,0.13907512259592011,2.3985699483963003,2.1566700845049764,2.1781469449892255],\"y\":[-2.0004371886915764,-1.6511145975381103,-0.57499332638486234,-1.0502188647445996,-0.48130213221033363,-0.95963852187830989,-0.94645783707309683,-1.4740099279145704,-0.56905168606588974,-0.9126084200381116,-1.2811104142765124,-0.82618610207532328,-0.94067746022217724,-0.67374196686715071,-0.86916230416293061,-0.78219711134268588,-0.62431763061529078,-1.0317087327157659,-0.89949010297111742,-0.45706224018022418,-1.9489611051976536,-0.31153639381300036,-1.4129508856693977,-1.4441760940560859,-0.30579359855852778,-0.40820141595292309,-0.34198849662897313,-0.68108311737623162,-1.8292947522582619,-1.7012491248147805,-0.83397728420679418,-1.0599883783227901,-1.1132470519452269,-0.80999586582626426,-1.4429315145639674,-0.5952016332398703,-1.3938095447293848,-0.49771025796733609,-1.1688378177867682,-0.70703508122832726,-1.0017508961380941,-1.1853408310089919,-1.7005465126578767,-0.90289568274500143,-1.8062345916258622,-0.72587879071822148,-1.0413336300619092,-1.0765848283532127,-0.67131717681706293,-0.27423396796448657,-0.43126574639021847,-0.79289582838256523,-1.1540030593590005,-0.178780345295669,-0.34609677680992018,-0.9678011347443537,-0.38570949921116737,-1.1465001092572733,-1.4984354862403921,-0.79225229017435583,-0.7568184628373974,-0.63495095316344841,-0.98580431645135991,-0.54388623897531918,-0.81677470796692864,-0.81719757696637774,-0.83283140430334346,-0.26957561369431138,-0.64118964136179324,-0.64953629957588455,-0.49243079274340251,-0.47896725213228286,-0.95985938616943411,-1.5662665775891014,-0.80784214683473055,-1.137103559299536,-2.0534273627873971,-0.5939564818707801,-0.41465257222205371,-2.1090645842819282,-0.96839775551590201,-1.7925745826727808,-1.0401972754298474,-0.84197174435296296,-1.2308168706303597,-0.43765329746644338,-0.24625522211212109,-0.99852024275319196,-0.67639406763146515,-0.75663204334088952,-1.4044918566089379,-2.7607153357419945,-1.1108383615046489,-1.3742874581640037,-0.42079610731115386,-1.8402447653555851,-1.0734828862143329,-0.39017632179489053,-1.9623157952623633,-0.70026894489442804,-1.5546973140644424,-0.8986294254606394,-1.0759780509809922,-2.4439056312611842,-0.79691180269546535,-1.9997036224313698,-1.4698583105989671,-0.61998231167602458,-1.8426355019238487,-0.49124690522646908,-1.8102528910445712,-1.5022643539640297,-1.2654253776094759,-0.5860986802686603,-1.5680832991270142,-1.6780130758286989,-0.51236513700773412,-1.0785695792502945,-1.4495621197770547,-1.1948126776056534,-2.2765169176356768,-1.055838898978589,-1.062681324056197,-0.71730130585315544,-0.7916211276240751,-0.53815753423006996,-0.93729228576517876,-0.49129271427819837,-1.0089512932489701,-1.0587519907738931,-0.42830788417389237,-1.3144416326921842,-0.86086047236447849,-1.0690287776598868,-0.74428590922113214,-0.93781605944140645,-0.89990662147788147,-0.55948802141345555,-0.52180559904699308,-0.92412404770770795,-1.0018146507588528,-0.34477134394027525,-1.4545187317309387,-1.1520957817791055,-0.7719459733925047,-1.5046725667947509,-1.1464683042926975,-0.76595039549474264,-0.85525331235816715,-1.5057216938587039,-1.9172642214455373,-0.73396036820880761,-0.32120724615193669,-1.0625308283792392,-1.2777453174600533,-0.84074089944544783,-1.2913712855006998,-0.22651145047592786,-0.7003274244097758,-0.82717355692732619,-0.15312032366288528,-1.1530073509982468,-0.7255930286503165,-1.1298773944183018,-1.4880048045605587,-1.3411213589911068,-0.69180538914575029,-1.6283880967177444,-1.7784521423391246,-1.9335177955321963,-1.5168564016205635,-0.50896297105438537,-1.0601552565240393,-1.1112883561815856,-1.2526709582740438,-0.33899940438091103,-1.2841390904635828,-0.59431881512417395,-1.5555076726964794,-2.4489628015217599,-1.9460213096902401,-2.0969653310992045,-0.78439141756550201,-1.3525265334886358,-1.7031539824599207,-0.94726441881973467,-2.0920392438967115,-1.1963551763786284,-2.3441517718304903,-1.4567076227782858,-0.56069712698548269,-1.4369063911953832,-1.5516441336006757,-0.6186919304642654,-1.5046097617115228,-1.7751518766017056,-0.78455027002984901,-1.129313872006841,-1.0502437846665369,-1.0006708933068957,-2.4183714359907613,-0.69947812544054333,-1.6172332967757184,-1.2484315429349804,-1.1882349698326833,-1.508578097682258,-2.1154989318826276,-1.5484124569234097,-1.7151413624182994,-1.1046577791253958,-1.2227713510986691,-1.8298957407830676,-1.6319572753581082,-1.143947163407552,-0.26730489787195566,-0.70054151624565508,-1.4169269482278131,-0.60435194952653104,-1.5190894701939508,-2.0312835239281997,-0.83442825169401458,-1.1727470750465423,-1.2346431814904026,-0.75121786300257276,-0.41633472972823188,-0.88257396845829317,-0.75197880182548293,-1.2533195782168749,-1.8294472664940276,-1.2271741131457992,-1.6275522058978511,-1.4259300876223762,-0.36512668959854105,-1.4163273760827129,-1.1757547876428054,-1.128815089781791,-1.3135681423950245,-2.0642525337415321,-0.89868286856347479,-0.58709074717121756,-1.1266978139028747,-0.95153283521406584,-1.6734587011054209,-0.79089939705185019,-1.5013337519411392,-1.6281610339905856,-1.7942968670994561,-1.5710894897371321,-0.69427266292461332,-0.5569467429108903,-0.88532604539375404,-0.97896938099998021,-1.0913279322079386,-1.658082695793283,-1.1547305867522837,-2.3034035621242972,-1.3651075339344914,-1.2607089529052184,-1.3289751858990659,-1.7449572595100959,-0.66958803372206532,-1.6006102981934314,-1.3068074433079055,-0.60166005493615649,-0.92397281498603467,-0.45992606545849246,-0.4021219381244982,-1.561727978926599,-1.2453939355867019,-0.94168015734119703,-1.7840866190467903,-1.8634674779890534,-0.86376081501786428,-0.47797389598965873,-1.3360210349663035,-1.1513050166525589,-1.0515100603370324],\"text\":[\"Country: COL<br>Decade: 1960\",\"Country: DOM<br>Decade: 1970\",\"Country: BOL<br>Decade: 1980\",\"Country: BRA<br>Decade: 1980\",\"Country: CRI<br>Decade: 1980\",\"Country: GTM<br>Decade: 1980\",\"Country: SLV<br>Decade: 1980\",\"Country: AND<br>Decade: 1990\",\"Country: BLZ<br>Decade: 1990\",\"Country: COL<br>Decade: 1990\",\"Country: CRI<br>Decade: 1990\",\"Country: ECU<br>Decade: 1990\",\"Country: GEO<br>Decade: 1990\",\"Country: HTI<br>Decade: 1990\",\"Country: IND<br>Decade: 1990\",\"Country: ISL<br>Decade: 1990\",\"Country: KNA<br>Decade: 1990\",\"Country: MHL<br>Decade: 1990\",\"Country: PER<br>Decade: 1990\",\"Country: PRY<br>Decade: 1990\",\"Country: SYC<br>Decade: 1990\",\"Country: TTO<br>Decade: 1990\",\"Country: VEN<br>Decade: 1990\",\"Country: ARM<br>Decade: 2000\",\"Country: AUT<br>Decade: 2000\",\"Country: BEN<br>Decade: 2000\",\"Country: BGD<br>Decade: 2000\",\"Country: BHS<br>Decade: 2000\",\"Country: BOL<br>Decade: 2000\",\"Country: BRA<br>Decade: 2000\",\"Country: BRB<br>Decade: 2000\",\"Country: CAN<br>Decade: 2000\",\"Country: CHL<br>Decade: 2000\",\"Country: CPV<br>Decade: 2000\",\"Country: CRI<br>Decade: 2000\",\"Country: DEU<br>Decade: 2000\",\"Country: DOM<br>Decade: 2000\",\"Country: ECU<br>Decade: 2000\",\"Country: ERI<br>Decade: 2000\",\"Country: FIN<br>Decade: 2000\",\"Country: GMB<br>Decade: 2000\",\"Country: GNQ<br>Decade: 2000\",\"Country: GRD<br>Decade: 2000\",\"Country: GUY<br>Decade: 2000\",\"Country: HND<br>Decade: 2000\",\"Country: HRV<br>Decade: 2000\",\"Country: HTI<br>Decade: 2000\",\"Country: IND<br>Decade: 2000\",\"Country: IRL<br>Decade: 2000\",\"Country: ISL<br>Decade: 2000\",\"Country: KHM<br>Decade: 2000\",\"Country: KIR<br>Decade: 2000\",\"Country: KNA<br>Decade: 2000\",\"Country: KOR<br>Decade: 2000\",\"Country: LTU<br>Decade: 2000\",\"Country: MEX<br>Decade: 2000\",\"Country: MNE<br>Decade: 2000\",\"Country: MNG<br>Decade: 2000\",\"Country: MWI<br>Decade: 2000\",\"Country: NPL<br>Decade: 2000\",\"Country: NRU<br>Decade: 2000\",\"Country: PAN<br>Decade: 2000\",\"Country: PLW<br>Decade: 2000\",\"Country: PNG<br>Decade: 2000\",\"Country: PRY<br>Decade: 2000\",\"Country: RWA<br>Decade: 2000\",\"Country: SGP<br>Decade: 2000\",\"Country: SLB<br>Decade: 2000\",\"Country: SLV<br>Decade: 2000\",\"Country: SWZ<br>Decade: 2000\",\"Country: TON<br>Decade: 2000\",\"Country: TTO<br>Decade: 2000\",\"Country: TUV<br>Decade: 2000\",\"Country: UGA<br>Decade: 2000\",\"Country: USA<br>Decade: 2000\",\"Country: VCT<br>Decade: 2000\",\"Country: VEN<br>Decade: 2000\",\"Country: VUT<br>Decade: 2000\",\"Country: WSM<br>Decade: 2000\",\"Country: ARG<br>Decade: 2010\",\"Country: ARM<br>Decade: 2010\",\"Country: ATG<br>Decade: 2010\",\"Country: AUS<br>Decade: 2010\",\"Country: BDI<br>Decade: 2010\",\"Country: BEL<br>Decade: 2010\",\"Country: BEN<br>Decade: 2010\",\"Country: BFA<br>Decade: 2010\",\"Country: BGD<br>Decade: 2010\",\"Country: BHS<br>Decade: 2010\",\"Country: BLR<br>Decade: 2010\",\"Country: BLZ<br>Decade: 2010\",\"Country: BOL<br>Decade: 2010\",\"Country: BRA<br>Decade: 2010\",\"Country: BRN<br>Decade: 2010\",\"Country: BWA<br>Decade: 2010\",\"Country: CAN<br>Decade: 2010\",\"Country: CHL<br>Decade: 2010\",\"Country: CIV<br>Decade: 2010\",\"Country: COL<br>Decade: 2010\",\"Country: CPV<br>Decade: 2010\",\"Country: CRI<br>Decade: 2010\",\"Country: CUB<br>Decade: 2010\",\"Country: CZE<br>Decade: 2010\",\"Country: DMA<br>Decade: 2010\",\"Country: DNK<br>Decade: 2010\",\"Country: DOM<br>Decade: 2010\",\"Country: ECU<br>Decade: 2010\",\"Country: ERI<br>Decade: 2010\",\"Country: EST<br>Decade: 2010\",\"Country: FIN<br>Decade: 2010\",\"Country: FJI<br>Decade: 2010\",\"Country: FRA<br>Decade: 2010\",\"Country: FSM<br>Decade: 2010\",\"Country: GAB<br>Decade: 2010\",\"Country: GBR<br>Decade: 2010\",\"Country: GHA<br>Decade: 2010\",\"Country: GMB<br>Decade: 2010\",\"Country: GRD<br>Decade: 2010\",\"Country: GTM<br>Decade: 2010\",\"Country: GUY<br>Decade: 2010\",\"Country: HND<br>Decade: 2010\",\"Country: HRV<br>Decade: 2010\",\"Country: HTI<br>Decade: 2010\",\"Country: ITA<br>Decade: 2010\",\"Country: JAM<br>Decade: 2010\",\"Country: KGZ<br>Decade: 2010\",\"Country: KNA<br>Decade: 2010\",\"Country: LAO<br>Decade: 2010\",\"Country: LBR<br>Decade: 2010\",\"Country: LIE<br>Decade: 2010\",\"Country: LSO<br>Decade: 2010\",\"Country: LTU<br>Decade: 2010\",\"Country: MCO<br>Decade: 2010\",\"Country: MDG<br>Decade: 2010\",\"Country: MDV<br>Decade: 2010\",\"Country: MMR<br>Decade: 2010\",\"Country: MNG<br>Decade: 2010\",\"Country: NER<br>Decade: 2010\",\"Country: NGA<br>Decade: 2010\",\"Country: NIC<br>Decade: 2010\",\"Country: NOR<br>Decade: 2010\",\"Country: NPL<br>Decade: 2010\",\"Country: NRU<br>Decade: 2010\",\"Country: NZL<br>Decade: 2010\",\"Country: PHL<br>Decade: 2010\",\"Country: PLW<br>Decade: 2010\",\"Country: PNG<br>Decade: 2010\",\"Country: PRY<br>Decade: 2010\",\"Country: RWA<br>Decade: 2010\",\"Country: SLE<br>Decade: 2010\",\"Country: SLV<br>Decade: 2010\",\"Country: SMR<br>Decade: 2010\",\"Country: SOM<br>Decade: 2010\",\"Country: SUR<br>Decade: 2010\",\"Country: SWE<br>Decade: 2010\",\"Country: SWZ<br>Decade: 2010\",\"Country: SYC<br>Decade: 2010\",\"Country: TCD<br>Decade: 2010\",\"Country: TGO<br>Decade: 2010\",\"Country: THA<br>Decade: 2010\",\"Country: TJK<br>Decade: 2010\",\"Country: TTO<br>Decade: 2010\",\"Country: UGA<br>Decade: 2010\",\"Country: USA<br>Decade: 2010\",\"Country: VCT<br>Decade: 2010\",\"Country: VEN<br>Decade: 2010\",\"Country: ZMB<br>Decade: 2010\",\"Country: AND<br>Decade: 2020\",\"Country: ATG<br>Decade: 2020\",\"Country: AUS<br>Decade: 2020\",\"Country: AUT<br>Decade: 2020\",\"Country: AZE<br>Decade: 2020\",\"Country: BDI<br>Decade: 2020\",\"Country: BEN<br>Decade: 2020\",\"Country: BGD<br>Decade: 2020\",\"Country: BGR<br>Decade: 2020\",\"Country: BHS<br>Decade: 2020\",\"Country: BIH<br>Decade: 2020\",\"Country: BLZ<br>Decade: 2020\",\"Country: BOL<br>Decade: 2020\",\"Country: BRA<br>Decade: 2020\",\"Country: BRB<br>Decade: 2020\",\"Country: BRN<br>Decade: 2020\",\"Country: BTN<br>Decade: 2020\",\"Country: CAN<br>Decade: 2020\",\"Country: CHE<br>Decade: 2020\",\"Country: CHL<br>Decade: 2020\",\"Country: COG<br>Decade: 2020\",\"Country: COL<br>Decade: 2020\",\"Country: CRI<br>Decade: 2020\",\"Country: DJI<br>Decade: 2020\",\"Country: DMA<br>Decade: 2020\",\"Country: DOM<br>Decade: 2020\",\"Country: ERI<br>Decade: 2020\",\"Country: ESP<br>Decade: 2020\",\"Country: EST<br>Decade: 2020\",\"Country: ETH<br>Decade: 2020\",\"Country: FIN<br>Decade: 2020\",\"Country: FRA<br>Decade: 2020\",\"Country: GAB<br>Decade: 2020\",\"Country: GBR<br>Decade: 2020\",\"Country: GEO<br>Decade: 2020\",\"Country: GHA<br>Decade: 2020\",\"Country: GMB<br>Decade: 2020\",\"Country: GNB<br>Decade: 2020\",\"Country: GRD<br>Decade: 2020\",\"Country: GTM<br>Decade: 2020\",\"Country: GUY<br>Decade: 2020\",\"Country: HND<br>Decade: 2020\",\"Country: HRV<br>Decade: 2020\",\"Country: HTI<br>Decade: 2020\",\"Country: IND<br>Decade: 2020\",\"Country: ISL<br>Decade: 2020\",\"Country: JAM<br>Decade: 2020\",\"Country: JPN<br>Decade: 2020\",\"Country: KAZ<br>Decade: 2020\",\"Country: KEN<br>Decade: 2020\",\"Country: KHM<br>Decade: 2020\",\"Country: KIR<br>Decade: 2020\",\"Country: KNA<br>Decade: 2020\",\"Country: KOR<br>Decade: 2020\",\"Country: LBR<br>Decade: 2020\",\"Country: LIE<br>Decade: 2020\",\"Country: LKA<br>Decade: 2020\",\"Country: LSO<br>Decade: 2020\",\"Country: LTU<br>Decade: 2020\",\"Country: LVA<br>Decade: 2020\",\"Country: MCO<br>Decade: 2020\",\"Country: MDG<br>Decade: 2020\",\"Country: MDV<br>Decade: 2020\",\"Country: MEX<br>Decade: 2020\",\"Country: MKD<br>Decade: 2020\",\"Country: MLI<br>Decade: 2020\",\"Country: MLT<br>Decade: 2020\",\"Country: MNE<br>Decade: 2020\",\"Country: MNG<br>Decade: 2020\",\"Country: MUS<br>Decade: 2020\",\"Country: MWI<br>Decade: 2020\",\"Country: MYS<br>Decade: 2020\",\"Country: NER<br>Decade: 2020\",\"Country: NGA<br>Decade: 2020\",\"Country: NIC<br>Decade: 2020\",\"Country: NLD<br>Decade: 2020\",\"Country: NPL<br>Decade: 2020\",\"Country: NRU<br>Decade: 2020\",\"Country: NZL<br>Decade: 2020\",\"Country: PAN<br>Decade: 2020\",\"Country: PNG<br>Decade: 2020\",\"Country: POL<br>Decade: 2020\",\"Country: PRT<br>Decade: 2020\",\"Country: ROU<br>Decade: 2020\",\"Country: RWA<br>Decade: 2020\",\"Country: SEN<br>Decade: 2020\",\"Country: SGP<br>Decade: 2020\",\"Country: SLE<br>Decade: 2020\",\"Country: SLV<br>Decade: 2020\",\"Country: SMR<br>Decade: 2020\",\"Country: SOM<br>Decade: 2020\",\"Country: SUR<br>Decade: 2020\",\"Country: SVK<br>Decade: 2020\",\"Country: SVN<br>Decade: 2020\",\"Country: SWZ<br>Decade: 2020\",\"Country: SYC<br>Decade: 2020\",\"Country: TCD<br>Decade: 2020\",\"Country: THA<br>Decade: 2020\",\"Country: TJK<br>Decade: 2020\",\"Country: TLS<br>Decade: 2020\",\"Country: TON<br>Decade: 2020\",\"Country: TTO<br>Decade: 2020\",\"Country: UKR<br>Decade: 2020\",\"Country: URY<br>Decade: 2020\",\"Country: USA<br>Decade: 2020\",\"Country: VAT<br>Decade: 2020\",\"Country: VEN<br>Decade: 2020\",\"Country: WSM<br>Decade: 2020\",\"Country: ZMB<br>Decade: 2020\",\"Country: ZWE<br>Decade: 2020\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(199,124,255,1)\",\"opacity\":0.80000000000000004,\"size\":7.559055118110237,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(199,124,255,1)\"}},\"hoveron\":\"points\",\"name\":\"4\",\"legendgroup\":\"4\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":40.840182648401829,\"r\":7.3059360730593621,\"b\":37.260273972602747,\"l\":37.260273972602747},\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"title\":{\"text\":\"Country–Decade Thematic Clusters in PCA Space\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":17.534246575342465},\"x\":0,\"xref\":\"paper\"},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-3.4130136626563656,3.0348456527746936],\"tickmode\":\"array\",\"ticktext\":[\"-3\",\"-2\",\"-1\",\"0\",\"1\",\"2\",\"3\"],\"tickvals\":[-3,-2,-1,-4.4408920985006262e-16,1,2,3],\"categoryorder\":\"array\",\"categoryarray\":[\"-3\",\"-2\",\"-1\",\"0\",\"1\",\"2\",\"3\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Principal Component 1\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-3.0539065642076131,3.3963004620359949],\"tickmode\":\"array\",\"ticktext\":[\"-3\",\"-2\",\"-1\",\"0\",\"1\",\"2\",\"3\"],\"tickvals\":[-3,-2,-1,0,1.0000000000000004,2.0000000000000004,3.0000000000000004],\"categoryorder\":\"array\",\"categoryarray\":[\"-3\",\"-2\",\"-1\",\"0\",\"1\",\"2\",\"3\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Principal Component 2\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"layer\":\"below\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":true,\"legend\":{\"bgcolor\":null,\"bordercolor\":null,\"borderwidth\":0,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498},\"title\":{\"text\":\"Cluster\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"89792e341f67\":{\"x\":{},\"y\":{},\"colour\":{},\"text\":{},\"type\":\"scatter\"}},\"cur_data\":\"89792e341f67\",\"visdat\":{\"89792e341f67\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\nThis interactive PCA plot visualises country–decade thematic profiles, with points coloured by hierarchical cluster membership. The clusters form clearly separated regions in the low-dimensional space, indicating distinct combinations of dominant themes across country–decade units.\n\nAt the same time, the interactive view reveals a small number of atypical cases within each cluster. For example, **ISR (2010)** in Cluster 1, **DNK (1940)** in Cluster 2, and **COL (1960)** in Cluster 4 appear temporally distant from most other members of their respective clusters. These observations, suggest that individual countries can exhibit decade-specific thematic profiles that diverge from the dominant temporal pattern.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncluster_summary <- pca_cd_df %>%\n  group_by(cluster) %>%\n  summarise(\n    n_units = n(),\n    mean_PC1 = mean(PC1),\n    mean_PC2 = mean(PC2),\n    decades  = paste(sort(unique(decade)), collapse = \", \")\n  )\n\ncluster_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  cluster n_units mean_PC1 mean_PC2 decades                                     \n  <fct>     <int>    <dbl>    <dbl> <chr>                                       \n1 1           248   -1.97    -0.459 1940, 1950, 1960, 1970, 1980, 1990, 2010, 2…\n2 2           258    0.950    0.403 1940, 1960, 1970, 1980, 1990, 2000, 2010, 2…\n3 3           178   -0.330    1.77  1950, 1960, 1970, 1980, 1990, 2000, 2010    \n4 4           277    1.09    -1.10  1960, 1970, 1980, 1990, 2000, 2010, 2020    \n```\n\n\n:::\n:::\n\n\nThis summary characterises each cluster by its size and its average position in the PCA space. Clusters differ clearly in their mean PC1 and PC2 scores, indicating distinct thematic orientations, while all clusters span multiple decades rather than being confined to a single period. This reinforces the interpretation that clustering captures recurring thematic configurations that cut across time, even though their prevalence shifts across decades.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npca_cd_df <- as_tibble(pca_cd$x[, 1:2], rownames = \"unit\") %>%\n  mutate(cluster = factor(cutree(hc_cd, k = 4)))\n\ncountry_decade_with_cluster <- country_decade_mat %>%\n  as_tibble(rownames = \"unit\") %>%\n  left_join(\n    pca_cd_df %>% select(unit, cluster),\n    by = \"unit\"\n  )\n\n\ncluster_topic_profiles <- country_decade_with_cluster %>%\n  group_by(cluster) %>%\n  summarise(across(`1`:`8`, mean))\n\ncluster_topic_profiles\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 9\n  cluster    `1`    `2`    `3`    `4`    `5`    `6`    `7`    `8`\n  <fct>    <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>\n1 1       0.124  0.259  0.100  0.0696 0.0294 0.204  0.0729 0.141 \n2 2       0.0971 0.0832 0.0895 0.103  0.209  0.0830 0.278  0.0572\n3 3       0.0756 0.102  0.272  0.143  0.0481 0.0873 0.178  0.0945\n4 4       0.142  0.0590 0.0448 0.0541 0.406  0.114  0.138  0.0427\n```\n\n\n:::\n:::\n\n\n\nThis table reports the average topic composition within each cluster, obtained by averaging country–decade topic proportions across all units assigned to the same cluster. The clusters exhibit clear thematic profiles. **Cluster 1** emphasises multilateral institutions and security-related discourse, **Cluster 2** governance and legal–environmental themes, **Cluster 3** decolonisation and regional conflict, and **Cluster 4** climate change and sustainable development. \n\nWhile clusters are broadly aligned with temporal shifts, notable exceptions highlight meaningful country-specific patterns. For example, **ISR in 2010** remains focused on institution and security relative to other countries in the same decade, reflecting persistent geopolitical constraints, whereas **DNK in the 1940s** already aligns with governance-oriented themes, consistent with a long-standing normative diplomatic tradition. These cases suggest that the clusters capture not only global temporal change but also enduring national orientations that shape how countries engage with evolving international agendas.\n\n\n## Limitations and Ethical Considerations\n\nThe findings presented here should be interpreted in light of several **methodological** and **ethical constraints** inherent in the analytical design.\n\nFrom a **methodological** standpoint, the decade-level sampling and aggregation strategy necessarily smooths over within-decade variation and may obscure short-term rhetorical shifts linked to specific geopolitical events. Topic modeling outcomes are also sensitive to preprocessing decisions and to the number of topics specified, meaning that alternative specifications could yield somewhat different thematic delineations. Moreover, aggregation at the country–decade level abstracts from leadership turnover and internal political change, so the analysis captures dominant discursive orientations rather than the full heterogeneity of national speechmaking.\n\n**Ethical** and interpretive considerations call for caution. Because topic modeling and clustering are inductive, topic labels and cluster interpretations necessarily reflect researcher judgment and should not be read as fixed national characteristics. The analysis is therefore descriptive rather than evaluative. More broadly, clustering functions as a heuristic tool, and uncritical interpretation risks reinforcing essentialised or stereotypical readings of national discourse, underscoring the need for careful contextualisation.\n\n\n## Conclusion: Long-Run Thematic Shifts and Cross-National Variation in UN Discourse\n\nThis study examined how the thematic composition of UN General Debate speeches has evolved over time and how these changes vary across countries. Using unsupervised learning methods, the analysis combined topic modeling, dimensionality reduction, and clustering to trace long-run patterns in multilateral discourse while accounting for cross-national heterogeneity.\n\nThe results point to a clear reorientation of the international agenda. Early decades are dominated by multilateral institutions, Cold War rivalry, and security concerns, whereas later periods increasingly foreground development, governance, and sustainability. PCA-based analyses show that this shift follows a gradual and cumulative trajectory rather than abrupt breaks, with mid-period peaks reflecting the salience of decolonisation and regional conflict.\n\nAt the same time, the country–decade analysis demonstrates that states do not move uniformly through thematic space. While temporal dynamics structure the overall pattern, hierarchical clustering reveals recurring thematic configurations and notable country-specific deviations. These findings suggest that enduring national orientations and geopolitical constraints mediate how countries engage with evolving global priorities.\n\nTaken together, the analysis shows that changes in UN General Debate discourse reflect both systemic temporal shifts and persistent cross-national differences. Unsupervised learning provides a coherent framework for capturing this dual structure, offering insight into how the international agenda evolves while remaining unevenly articulated across states.\n\n# Use of AI Tools\n\nChatGPT was used to clarify methodological concepts discussed in the course and to assist with minor coding issues.\n\n",
    "supporting": [
      "62751_2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../../site_libs/plotly-binding-4.11.0/plotly.js\"></script>\n<script src=\"../../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.2/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.2/js/crosstalk.min.js\"></script>\n<link href=\"../../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}