{
  "hash": "b3db2c212b51b71adc60634d7e52c94b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Survival Analysis and Factor Analysis\"\nauthor: \"Shuhei Kuwabara\"\nformat: html\nself-contained: true\ntoc: true\ntoc-location: left\ncode-fold: show\ncode-copy: true\neditor:\n  render-on-save: true\n  preview: true\n---\n\n# Part1. Survival Analysis\n\n## 1. Preparation for Subsequent Analyses\n\n### 1.1 Loading the Dataset\n\nThe workspace is initialized by clearing all existing objects to ensure a reproducible environment. Subsequently, the dataset (`chapter_09_churn_data.csv`) is loaded from the `data/` directory. The `head()` outcome verifies that the data structure has been imported correctly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(list = ls())\n\ndata_chap09_churn <- read.csv(\"data/chapter_09_churn_data.csv\", header = TRUE)\n\nhead(data_chap09_churn)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Cid Duration Event DM Sex Age Freq Amount\n1   1       27     1  0   1  38    2   8.53\n2   2       31     1  1   0  47    2   8.37\n3   3       36     1  1   0  54    4   8.28\n4   4       35     1  1   1  65    2   8.50\n5   5       31     1  0   0  17    2   8.28\n6   6       27     1  1   1  41    4   8.25\n```\n\n\n:::\n:::\n\n\n### 1.2 Loading Required Packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#install.packages(c(\"survival\", \"flexsurv\", \"survminer\",\"dplyr\",\"stargazer\",\"broom\",\"readr\"))\nlibrary(survival)    \nlibrary(flexsurv)\nlibrary(survminer)  \nlibrary(dplyr)       \nlibrary(stargazer)\nlibrary(broom)      \nlibrary(readr)      \n```\n:::\n\n\n## 2. Effect of Direct Mail (PHM)\n\n### 2.1 Exploratory Data Analysis\n\nPrior to utilizing the proportional hazards model to estimate the differences in churn duration based on DM status, a preliminary analysis is performed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(subset(data_chap09_churn, Event == 0))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 23\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(data_chap09_churn[data_chap09_churn$Event == 1,]$Duration)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   3.00   23.00   31.00   30.79   39.00   54.00 \n```\n\n\n:::\n\n```{.r .cell-code}\nhist(data_chap09_churn$Duration, main = '',\n     xlab = \"Duration\", ylab = \"Number of Customers\")\n```\n\n::: {.cell-output-display}\n![](report_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n\n```{.r .cell-code}\ndur_DM <- data_chap09_churn[data_chap09_churn$DM == 1,2]\ndur_no_DM <- data_chap09_churn[data_chap09_churn$DM == 0,2]\n\nboxplot(dur_DM,dur_no_DM,\n        names = c(\"DM\", \"No DM\"), ylab = \"Duration\")\n```\n\n::: {.cell-output-display}\n![](report_files/figure-html/unnamed-chunk-2-2.png){width=672}\n:::\n:::\n\n\nThe `summary` statistics reveal that **23** customers remained active throughout the observation period. Out of the total **1,000** customers, **977** churn events were observed, ranging from day **3** to day **54**. The median survival time was identified as **31** days, indicating a concentration of customer attrition around this point.\n\nFurthermore, the data was stratified by Direct Mail (DM) reception status to visualize the distribution via a boxplot. The analysis indicates that the group receiving DM exhibits **slightly higher** median and quartile values compared to the non-recipient group. This observation suggests that *receiving DM may be associated with prolonged customer retention*.\n\n### 2.2 Estimation of the Proportional Hazards Model\n\nThe **Cox proportional hazards model (PHM)** is utilized to quantify the relationship between the reception of Direct Mail (DM) and customer churn duration.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_DM <- flexsurvreg(\n  Surv(Duration, Event) ~ DM,\n  data = data_chap09_churn,\n  dist = \"weibullPH\"\n)\n\ncoef_tbl_DM <- as.data.frame(fit_DM$res) %>%\n  tibble::rownames_to_column(\"variable\") %>%\n  filter(variable %in% names(coef(fit_DM)))\n\ncoef_tbl_DM <- coef_tbl_DM %>%\n  mutate(\n    HR = exp(est),\n    HR_se = HR*se,\n    HR_L95 = exp(est - 1.96 * se),\n    HR_U95 = exp(est + 1.96 * se)\n  ) %>%\n  select(variable, coef = est, se.coef=se, HR, HR_se, HR_L95, HR_U95)\nprint(coef_tbl_DM, digits = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  variable      coef  se.coef     HR    HR_se HR_L95 HR_U95\n1    shape  3.04e+00 7.79e-02 20.832 1.62e+00 17.883 24.268\n2    scale  2.24e-05 6.45e-06  1.000 6.45e-06  1.000  1.000\n3       DM -1.97e-01 6.41e-02  0.821 5.26e-02  0.724  0.931\n```\n\n\n:::\n:::\n\n\nThe results indicate that the Hazard Ratio for DM recipients is **0.821** (95% CI: **0.724**–**0.931**). Since the 95% confidence interval excludes 1, a statistically significant effect is observed. This estimate implies that the instantaneous risk of churn for customers who received DM is approximately **18%** lower than for those who did not, assuming other conditions remain constant.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(fit_DM, type = \"hazard\", ci = TRUE,\n     newdata = data.frame(DM = 1),\n     col = \"blue\", lwd = 2,\n     xlab = \"Duration\", ylab = \"Hazard\",\n     main = \"\")\n\nplot(fit_DM, type = \"hazard\", ci = TRUE,\n     newdata = data.frame(DM = 0),\n     col = \"red\", lwd = 2, add = TRUE)\nlegend(\"topleft\", legend = c(\"DM\", \"no DM\"),\n       col = c(\"blue\", \"red\"), lwd = 2)\n```\n\n::: {.cell-output-display}\n![](report_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nThe figure above illustrates the estimated hazard functions stratified by the status of DM reception. The hazard for customers who received DM is observed to be consistently lower than that for customers who did not receive DM across the entire timeline.\n\nNotably, the divergence between the two groups widens progressively during the latter half of the observation period (after day 30). This trend suggests that the receipt of DM exerts a suppressive effect on the risk of churn. Furthermore, the distinct separation of the 95% confidence intervals indicates that the difference between the two hazard functions is statistically significant.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(fit_DM, type = \"survival\", ci = TRUE,\n     newdata = data.frame(DM = 1), col = \"blue\")\nplot(fit_DM, type = \"survival\", ci = TRUE,\n     newdata = data.frame(DM = 0), col = \"red\", add = TRUE)\n\nlegend(\"bottomleft\", c(\"DM\", \"No DM\"), lwd = 1, col = c(\"blue\",\"red\"))\n```\n\n::: {.cell-output-display}\n![](report_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nThis figure depicts the estimated survival functions stratified by the presence or absence of DM reception. The survival probability for DM recipients remains consistently higher than that for non-recipients, indicating that customers who received DM exhibit a stronger tendency for prolonged service retention.\n\nA marked divergence between the two groups becomes particularly apparent around the 30 to 40-day interval, suggesting that DM reception contributes to the mitigation of customer churn. Furthermore, the limited overlap between the 95% confidence intervals supports the conclusion that the observed difference in survival probabilities is statistically significant.\n\n## 3. Demographic and Behavioral Characteristics PHM\n\nIn the following code, a proportional hazards model based on the Weibull distribution is estimated, utilizing customer demographic attributes (`Sex`, `Age`) and behavioral characteristics (`Freq`, `Amount`) as explanatory variables. Subsequent to the model estimation, the influence of varying levels of variables that exhibited particularly significant hazard ratios on the survival and hazard functions is visualized.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_full <- flexsurvreg(\n  Surv(Duration, Event) ~  Sex + Age + Freq + Amount,\n  data = data_chap09_churn,\n  dist = \"weibullPH\"\n)\n\ncoef_tbl_full <- as.data.frame(fit_full$res) %>%\n  tibble::rownames_to_column(\"variable\") %>%\n  filter(variable %in% names(coef(fit_full)))\ncoef_tbl_full <- coef_tbl_full %>%\n  mutate(\n    HR = exp(est),\n    HR_se = HR*se,\n    HR_L95 = exp(est - 1.96 * se),\n    HR_U95 = exp(est + 1.96 * se)\n  ) %>%\n  select(variable, coef = est, se.coef=se, HR, HR_se, HR_L95, HR_U95)\nprint(coef_tbl_full, digits = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  variable      coef  se.coef     HR    HR_se HR_L95 HR_U95\n1    shape  3.25e+00 8.25e-02 25.820 2.13e+00 21.964 30.353\n2    scale  8.59e-05 8.46e-05  1.000 8.46e-05  1.000  1.000\n3      Sex -5.04e-02 6.75e-02  0.951 6.42e-02  0.833  1.085\n4      Age -2.46e-02 2.06e-03  0.976 2.01e-03  0.972  0.980\n5     Freq -1.54e-01 2.64e-02  0.857 2.26e-02  0.814  0.903\n6   Amount -8.66e-02 1.14e-01  0.917 1.05e-01  0.733  1.147\n```\n\n\n:::\n:::\n\n\nBoth age(`Age`) and purchase frequency(`Freq`) were identified as statistically significant factors influencing churn risk. Specifically, the Hazard Ratio (HR) for `Age` was estimated at **0.976** (95% CI: **0.972**–**0.980**), implying that each additional year of age corresponds to an approximate **2.4% reduction** in the instantaneous risk of churn. Similarly, the HR for `Freq` was calculated as **0.857** (95% CI: **0.814**–**0.903**), indicating that a single unit increase in purchase frequency is associated with a **14.3% decrease** in churn risk. Since the 95% confidence intervals for both variables exclude the null value of 1, these effects are confirmed to be statistically significant. Conversely, the HR for gender(`Sex`) was **0.951** (95% CI: **0.833–1.085**), and for purchase amount(`Amount`) was **0.917** (95% CI: **0.733**–**1.147**). As these intervals encompass 1, no statistically significant impact was observed for these variables, suggesting that their influence on customer churn is limited within the context of this model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(fit_full, type = \"survival\", ci = TRUE,\n     newdata = data.frame(Sex = mean(data_chap09_churn$Sex),\n                          Age = 20,\n                          Freq = mean(data_chap09_churn$Freq),\n                          Amount = mean(data_chap09_churn$Amount)),\n     col = \"blue\", lwd = 2,\n     xlab = \"Duration\", ylab = \"Survival Probability\",\n     main = \"Survival Function (age)\")\n\nplot(fit_full, type = \"survival\", ci = TRUE,\n     newdata = data.frame(Sex = mean(data_chap09_churn$Sex),\n                          Age = 40,\n                          Freq = mean(data_chap09_churn$Freq),\n                          Amount = mean(data_chap09_churn$Amount)),\n     col = \"red\", lwd = 2, add = TRUE)\n\nlegend(\"bottomleft\", legend = c(\"age:20\", \"age:40\"), \n       col = c(\"blue\", \"red\"), lwd = 2)\n```\n\n::: {.cell-output-display}\n![](report_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(fit_full, type = \"hazard\", ci = TRUE,\n     newdata = data.frame(Sex = mean(data_chap09_churn$Sex),\n                          Age = 20,\n                          Freq = mean(data_chap09_churn$Freq),\n                          Amount = mean(data_chap09_churn$Amount)),\n     col = \"blue\", lwd = 2,\n     xlab = \"Duration\", ylab = \"Hazard\",\n     main = \"Hazard Function (age)\")\n\nplot(fit_full, type = \"hazard\", ci = TRUE,\n     newdata = data.frame(Sex = mean(data_chap09_churn$Sex),\n                          Age = 40,\n                          Freq = mean(data_chap09_churn$Freq),\n                          Amount = mean(data_chap09_churn$Amount)),\n     col = \"red\", lwd = 2, add = TRUE)\n\nlegend(\"bottomright\", legend = c(\"age:20\", \"age:40\"), \n       col = c(\"blue\", \"red\"), lwd = 2)\n```\n\n::: {.cell-output-display}\n![](report_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nThese graphs illustrate the estimated survival functions and the hazard functions for customers aged **20** (representing the younger demographic) and **40** (representing the middle-aged demographic). A comparative analysis of these indicates that the younger demographic exhibits a consistently higher risk of churn and a correspondingly lower survival probability at any given time point.\n\nNotably, the divergence between the two cohorts expands during the latter half of the observation period, providing visual confirmation that the tendency for customer attrition becomes more moderate as age increases. This observation is fully consistent with the estimated Hazard Ratio (HR = **0.976**, 95% CI: **0.972**–**0.980**), thereby corroborating the conclusion that advancing age serves as a significant factor in suppressing churn risk.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolors <- c(\"red\", \"orange\", \"green\", \"blue\", \"purple\")\nlabels <- paste(\"Freq =\", 1:5)\n\nplot(fit_full, type = \"hazard\", ci = FALSE,\n     newdata = data.frame(Sex = mean(data_chap09_churn$Sex),\n                          Age = mean(data_chap09_churn$Age),\n                          Freq = 1,\n                          Amount = mean(data_chap09_churn$Amount)),\n     col = colors[1], lwd = 2,\n     xlab = \"Duration\", ylab = \"Hazard\",\n     main = \"Hazard Function (Freq)\")\nfor (i in 2:5) {\n  plot(fit_full, type = \"hazard\", ci = FALSE,\n       newdata = data.frame(Sex = mean(data_chap09_churn$Sex),\n                            Age = mean(data_chap09_churn$Age),\n                            Freq = i,\n                            Amount = mean(data_chap09_churn$Amount)),\n       col = colors[i], lwd = 2, add = TRUE)\n}\n\nlegend(\"bottomright\", legend = labels, col = colors, lwd = 2)\n```\n\n::: {.cell-output-display}\n![](report_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(fit_full, type = \"survival\", ci = FALSE,\n     newdata = data.frame(Sex = mean(data_chap09_churn$Sex),\n                          Age = mean(data_chap09_churn$Age),\n                          Freq = 1,\n                          Amount = mean(data_chap09_churn$Amount)),\n     col = colors[1], lwd = 2,\n     xlab = \"Duration\", ylab = \"Survival Probability\",\n     main = \"Survival Function (Freq)\")\nfor (i in 2:5) {\n  plot(fit_full, type = \"survival\", ci = FALSE,\n       newdata = data.frame(Sex = mean(data_chap09_churn$Sex),\n                            Age = mean(data_chap09_churn$Age),\n                            Freq = i,\n                            Amount = mean(data_chap09_churn$Amount)),\n       col = colors[i], lwd = 2, add = TRUE)\n}\nlegend(\"bottomleft\", legend = labels, col = colors, lwd = 2)\n```\n\n::: {.cell-output-display}\n![](report_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nThe figures above visualize the hazard and survival functions for customers with usage frequencies(`Freq`) ranging from 1 to 5. A comparative analysis of the survival functions reveals that customers with higher usage frequencies maintain consistently higher survival probabilities, indicating a tendency for prolonged service retention.\n\nSimilarly, the hazard functions demonstrate that groups with higher frequencies experience lower churn hazards at any arbitrary time point, evidencing a suppressive effect on churn risk. This observation aligns with the previously estimated hazard ratios, suggesting that usage frequency serves as a proxy for customer loyalty and acts as a significant determinant in mitigating customer attrition.\n\n# Part2. Factor Analysis\n\n## 1. Preparation for Subsequent Analyses\n\n### 1.1 Loading the Dataset\n\nThe dataset (`chapter_11.csv`) is loaded from the `data/` directory. The `head()` outcome verifies that the data structure has been imported correctly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(list = ls())　\n\ndata_chap11 <- read.csv(\"data/chapter_11.csv\", header = TRUE)\nhead(data_chap11)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  LOV1 LOV2 LOV3 LOV4 LOV5 LOV6 LOV7 LOV8 LOV9 LUAT1 LUAT2 LUAT3 LUBE1 LUBE2\n1    5    4    5    6    5    7    7    6    6     5     5     5     3     3\n2    5    5    6    6    6    6    7    6    6     2     1     1     2     5\n3    5    6    6    6    6    6    6    6    6     3     3     3     3     3\n4    6    5    6    5    4    7    7    6    6     2     2     2     2     2\n5    2    3    2    2    2    6    6    6    3     3     2     4     5     4\n6    5    5    6    5    5    6    7    6    5     3     2     6     6     5\n  LUBE3 LUBE4 LUBE5 NFC1 NFC2 NFC3 NFC4 gen age\n1     6     6     4    6    6    7    7   0   1\n2     5     5     5    7    7    7    7   0   1\n3     3     6     6    5    6    6    6   0   0\n4     2     5     5    3    3    5    5   1   1\n5     4     4     5    5    5    5    5   1   1\n6     6     6     4    5    7    7    6   0   1\n```\n\n\n:::\n:::\n\n\n### 1.2 Loading Required Packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#install.packages(c(\"lavaan\", \"lavaanPlot\", \"psych\", \"dplyr\", \"semTools\"))\n\nlibrary(lavaan) \nlibrary(lavaanPlot)\nlibrary(psych)\nlibrary(dplyr)\nlibrary(semTools)\n```\n:::\n\n\n### 1.3 Calculation Methods for Reliability and Validity Metrics\n\nTo facilitate the subsequent computation of **Cronbach's alpha**, Composite Reliability (**CR**), and Average Variance Extracted (**AVE**), the necessary functions are defined in advance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha.coef <- function(x){\n  z <- (ncol(x) / (ncol(x) - 1)) * \n    (1 - sum(diag(var(x))) / var(rowSums(x)))\n  return(z)\n}\n\ncr_ave <- function(Flab, StdEst){\n  FL <- StdEst[(StdEst[\"lhs\"] == Flab) & (StdEst[\"op\"] == \"=~\"),3]　\n  FLlist <- colSums(apply(StdEst[\"rhs\"], 1, \n                          function(x,fl){x==fl},FL)) > 0\n  Lm <- StdEst[FLlist & (StdEst[\"op\"] == \"=~\"), 4]\n  e <-  StdEst[FLlist & (StdEst[\"op\"] == \"~~\"), 4]\n  \n  CR <- sum(Lm)^2 / (sum(Lm)^2 + sum(e))\n  AVE <- sum(Lm^2) / (sum(Lm^2) + sum(e))\n  return(c(CR,AVE))\n}\n```\n:::\n\n\n## 2. Confirmatory Factor Analysis (One-Factor Model)\n\n### 2.1 One-Factor CFA\n\nA Confirmatory Factor Analysis (CFA) is conducted on a total of eight items, ranging from `LUAT1` to `LUBE5`, under the assumption that these variables are explained by a **single** latent factor, `LU`. The dataset `dat_lu` is constructed by extracting the target items (columns 10 through 17) from data_chap11. Estimation was performed utilizing the sem function from the lavaan package. Subsequently, model fit indices are generated using `fitMeasures`, and detailed parameter estimates were obtained via the `summary` function. Finally, the analysis proceeded to the visualization of results and the evaluation of both reliability and convergent validity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_lu <- data_chap11[,10:17]　\n\ncor(dat_lu)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          LUAT1     LUAT2     LUAT3     LUBE1     LUBE2     LUBE3     LUBE4\nLUAT1 1.0000000 0.6863097 0.6530632 0.4216778 0.4153562 0.2854687 0.2182564\nLUAT2 0.6863097 1.0000000 0.7031984 0.3998382 0.4011859 0.3186372 0.1806116\nLUAT3 0.6530632 0.7031984 1.0000000 0.4230186 0.4658564 0.3360935 0.1492323\nLUBE1 0.4216778 0.3998382 0.4230186 1.0000000 0.8293229 0.6718840 0.3731311\nLUBE2 0.4153562 0.4011859 0.4658564 0.8293229 1.0000000 0.6780064 0.3638658\nLUBE3 0.2854687 0.3186372 0.3360935 0.6718840 0.6780064 1.0000000 0.4973186\nLUBE4 0.2182564 0.1806116 0.1492323 0.3731311 0.3638658 0.4973186 1.0000000\nLUBE5 0.4580084 0.4108389 0.4266380 0.4730922 0.5001806 0.4537937 0.4267252\n          LUBE5\nLUAT1 0.4580084\nLUAT2 0.4108389\nLUAT3 0.4266380\nLUBE1 0.4730922\nLUBE2 0.5001806\nLUBE3 0.4537937\nLUBE4 0.4267252\nLUBE5 1.0000000\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(eigen(cor(dat_lu))$values, type = \"b\")\nabline(h = 1)\n```\n\n::: {.cell-output-display}\n![](report_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\n## Factor Determination\n\nThe scree plot indicates that the first two eigenvalues exceed 1.0, suggesting that a **two-factor structure** might be statistically more appropriate for this dataset. However, as the assignment explicitly requires the implementation of a one-factor model, the following analysis proceeds under the assumption of a single latent factor.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_cfa_1F <- '\n  LU =~ LUAT1 + LUAT2 + LUAT3 +\n       LUBE1 + LUBE2 + LUBE3 + LUBE4 + LUBE5\n'\nresult_cfa_1F <- lavaan::sem(model_cfa_1F, data = dat_lu)\nfitMeasures(result_cfa_1F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 npar                  fmin                 chisq \n               16.000                 0.623               401.286 \n                   df                pvalue        baseline.chisq \n               20.000                 0.000              1420.329 \n          baseline.df       baseline.pvalue                   cfi \n               28.000                 0.000                 0.726 \n                  tli                  nnfi                   rfi \n                0.617                 0.617                 0.604 \n                  nfi                  pnfi                   ifi \n                0.717                 0.512                 0.728 \n                  rni                  logl     unrestricted.logl \n                0.726             -4425.045             -4224.402 \n                  aic                   bic                ntotal \n             8882.090              8942.483               322.000 \n                 bic2                 rmsea        rmsea.ci.lower \n             8891.733                 0.243                 0.223 \n       rmsea.ci.upper        rmsea.ci.level          rmsea.pvalue \n                0.264                 0.900                 0.000 \n       rmsea.close.h0 rmsea.notclose.pvalue     rmsea.notclose.h0 \n                0.050                 1.000                 0.080 \n                  rmr            rmr_nomean                  srmr \n                0.336                 0.336                 0.130 \n         srmr_bentler   srmr_bentler_nomean                  crmr \n                0.130                 0.130                 0.147 \n          crmr_nomean            srmr_mplus     srmr_mplus_nomean \n                0.147                 0.130                 0.130 \n                cn_05                 cn_01                   gfi \n               26.204                31.144                 0.734 \n                 agfi                  pgfi                   mfi \n                0.521                 0.408                 0.553 \n                 ecvi \n                1.346 \n```\n\n\n:::\n:::\n\n\nAn examination of the model fit indices reveals that both `GFI` (0.734) and `AGFI` (0.521) fall below their respective recommended thresholds of 0.90 and 0.85, indicating that the overall model fit is inadequate. Furthermore, error metrics such as `RMSEA` (0.243) and `SRMR` (0.130) also fail to meet the established criteria. Consequently, it is concluded that the one-factor model does **not** demonstrate a satisfactory fit to the data, suggesting that a re-examination of the model structure is necessary.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(result_cfa_1F, standardized = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlavaan 0.6-21 ended normally after 30 iterations\n\n  Estimator                                         ML\n  Optimization method                           NLMINB\n  Number of model parameters                        16\n\n  Number of observations                           322\n\nModel Test User Model:\n                                                      \n  Test statistic                               401.286\n  Degrees of freedom                                20\n  P-value (Chi-square)                           0.000\n\nParameter Estimates:\n\n  Standard errors                             Standard\n  Information                                 Expected\n  Information saturated (h1) model          Structured\n\nLatent Variables:\n                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all\n  LU =~                                                                 \n    LUAT1             1.000                               0.861    0.538\n    LUAT2             0.953    0.125    7.619    0.000    0.821    0.528\n    LUAT3             1.069    0.134    7.962    0.000    0.921    0.562\n    LUBE1             1.802    0.175   10.271    0.000    1.552    0.881\n    LUBE2             1.738    0.168   10.325    0.000    1.497    0.894\n    LUBE3             1.452    0.153    9.467    0.000    1.251    0.745\n    LUBE4             0.810    0.119    6.784    0.000    0.698    0.451\n    LUBE5             1.178    0.142    8.282    0.000    1.015    0.596\n\nVariances:\n                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all\n   .LUAT1             1.818    0.149   12.203    0.000    1.818    0.710\n   .LUAT2             1.747    0.143   12.230    0.000    1.747    0.722\n   .LUAT3             1.835    0.151   12.138    0.000    1.835    0.684\n   .LUBE1             0.692    0.084    8.234    0.000    0.692    0.223\n   .LUBE2             0.565    0.074    7.670    0.000    0.565    0.201\n   .LUBE3             1.251    0.112   11.170    0.000    1.251    0.444\n   .LUBE4             1.906    0.154   12.386    0.000    1.906    0.797\n   .LUBE5             1.866    0.155   12.030    0.000    1.866    0.644\n    LU                0.742    0.148    5.020    0.000    1.000    1.000\n```\n\n\n:::\n:::\n\n\nWhile factor `LU` demonstrates strong associations with certain observed variables, notably `LUBE1` (0.881) and `LUBE2` (0.894), it exhibits weaker associations with others, such as `LUBE4` (0.451) and `LUAT2` (0.528). Furthermore, all three items in the `LUAT` series display moderate factor loadings of approximately 0.5, necessitating a cautious interpretation regarding measurement validity. Overall, the analysis reveals a notable disparity in the contribution of individual items to the underlying factor structure.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_1F <- cfa(model_cfa_1F, data = dat_lu)\nlavaanPlot(model = fit_1F,\n           edge_options = list(color = \"grey20\"),\n           coefs = T, covs = T, stand = TRUE)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"grViz html-widget html-fill-item\" id=\"htmlwidget-ef88dcf51cd0cee4ac59\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-ef88dcf51cd0cee4ac59\">{\"x\":{\"diagram\":\" digraph plot { \\n graph [ overlap = true, fontsize = 10 ] \\n node [ shape = box ] \\n node [shape = box] \\n LUAT1; LUAT2; LUAT3; LUBE1; LUBE2; LUBE3; LUBE4; LUBE5 \\n node [shape = oval] \\n LU \\n \\n edge [ color = grey20 ] \\n  LU->LUAT1 [label = \\\"0.54\\\"] LU->LUAT2 [label = \\\"0.53\\\"] LU->LUAT3 [label = \\\"0.56\\\"] LU->LUBE1 [label = \\\"0.88\\\"] LU->LUBE2 [label = \\\"0.89\\\"] LU->LUBE3 [label = \\\"0.75\\\"] LU->LUBE4 [label = \\\"0.45\\\"] LU->LUBE5 [label = \\\"0.6\\\"] \\n}\",\"config\":{\"engine\":\"dot\",\"options\":null}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\nThe figure above presents the path diagram of the one-factor CFA model, where `LU` serves as the single latent factor. In this structure, all eight items comprising the LUAT and LUBE series are modeled as being explained by factor loadings deriving from LU. The values annotating each arrow denote the standardized factor loadings (`Std.all`). Visual inspection confirms that while items such as LUBE1 and LUBE2 exhibit high loadings, the loading for LUBE4 is relatively low in comparison.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha.coef(dat_lu)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8690795\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstandardizedSolution(result_cfa_1F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     lhs op   rhs est.std    se      z pvalue ci.lower ci.upper\n1     LU =~ LUAT1   0.538 0.042 12.741      0    0.456    0.621\n2     LU =~ LUAT2   0.528 0.043 12.305      0    0.444    0.612\n3     LU =~ LUAT3   0.562 0.041 13.777      0    0.482    0.642\n4     LU =~ LUBE1   0.881 0.017 51.607      0    0.848    0.915\n5     LU =~ LUBE2   0.894 0.016 55.159      0    0.862    0.925\n6     LU =~ LUBE3   0.745 0.028 26.809      0    0.691    0.800\n7     LU =~ LUBE4   0.451 0.047  9.592      0    0.359    0.543\n8     LU =~ LUBE5   0.596 0.039 15.437      0    0.521    0.672\n9  LUAT1 ~~ LUAT1   0.710 0.045 15.609      0    0.621    0.799\n10 LUAT2 ~~ LUAT2   0.722 0.045 15.944      0    0.633    0.810\n11 LUAT3 ~~ LUAT3   0.684 0.046 14.902      0    0.594    0.774\n12 LUBE1 ~~ LUBE1   0.223 0.030  7.415      0    0.164    0.282\n13 LUBE2 ~~ LUBE2   0.201 0.029  6.949      0    0.144    0.258\n14 LUBE3 ~~ LUBE3   0.444 0.041 10.717      0    0.363    0.526\n15 LUBE4 ~~ LUBE4   0.797 0.042 18.786      0    0.714    0.880\n16 LUBE5 ~~ LUBE5   0.644 0.046 13.977      0    0.554    0.735\n17    LU ~~    LU   1.000 0.000     NA     NA    1.000    1.000\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstd_est_1F <- standardizedSolution(result_cfa_1F)\ncr_ave(\"LU\", std_est_1F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8591867 0.4468463\n```\n\n\n:::\n:::\n\n\n**Cronbach’s alpha** coefficient was **0.869**, significantly exceeding the generally accepted reliability threshold of 0.70; thus, the internal consistency among items is determined to be sufficiently high. Similarly, **Composite Reliability (CR)** was **0.859**, also surpassing the benchmark of 0.70, which demonstrates that the observed variables are stably explained by the common latent factor. Conversely, the **Average Variance Extracted (AVE)** was **0.447**, falling slightly below the standard cutoff of **0.50**. This result presents a concern regarding convergent validity, and it is possible that the low factor loading of `LUBE4` specifically contributed to this reduction in the AVE value.\n\n### 2.2 Two-Factor CFA\n\nFor the purpose of comparison, a Confirmatory Factor Analysis was conducted under the assumption of a two-factor structure, following the exact same procedure.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_cfa_2F <- '\n  AT =~ LUAT1 + LUAT2 + LUAT3\n  BE =~ LUBE1 + LUBE2 + LUBE3 + LUBE4 + LUBE5\n'\nresult_cfa_2F <- lavaan::sem(model_cfa_2F, data = dat_lu)\nfitMeasures(result_cfa_2F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 npar                  fmin                 chisq \n               17.000                 0.153                98.591 \n                   df                pvalue        baseline.chisq \n               19.000                 0.000              1420.329 \n          baseline.df       baseline.pvalue                   cfi \n               28.000                 0.000                 0.943 \n                  tli                  nnfi                   rfi \n                0.916                 0.916                 0.898 \n                  nfi                  pnfi                   ifi \n                0.931                 0.631                 0.943 \n                  rni                  logl     unrestricted.logl \n                0.943             -4273.697             -4224.402 \n                  aic                   bic                ntotal \n             8581.394              8645.561               322.000 \n                 bic2                 rmsea        rmsea.ci.lower \n             8591.640                 0.114                 0.092 \n       rmsea.ci.upper        rmsea.ci.level          rmsea.pvalue \n                0.137                 0.900                 0.000 \n       rmsea.close.h0 rmsea.notclose.pvalue     rmsea.notclose.h0 \n                0.050                 0.994                 0.080 \n                  rmr            rmr_nomean                  srmr \n                0.177                 0.177                 0.066 \n         srmr_bentler   srmr_bentler_nomean                  crmr \n                0.066                 0.066                 0.075 \n          crmr_nomean            srmr_mplus     srmr_mplus_nomean \n                0.075                 0.066                 0.066 \n                cn_05                 cn_01                   gfi \n               99.450               119.201                 0.931 \n                 agfi                  pgfi                   mfi \n                0.869                 0.491                 0.884 \n                 ecvi \n                0.412 \n```\n\n\n:::\n:::\n\n\nThe goodness-of-fit indices for the two-factor model—`GFI` = 0.931 (≥ 0.90), `AGFI` = 0.869 (≥ 0.85), and `SRMR` = 0.066 (≤ 0.08)—satisfied the established criteria, indicating that the overall model fit is satisfactory. Conversely, the `RMSEA` value of 0.114 exceeded the recommended limit (≤ 0.1), which warrants caution. However, given that the other indices are generally favorable, this model is evaluated as exhibiting a **superior fit** compared to the one-factor model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(result_cfa_2F, standardized = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlavaan 0.6-21 ended normally after 30 iterations\n\n  Estimator                                         ML\n  Optimization method                           NLMINB\n  Number of model parameters                        17\n\n  Number of observations                           322\n\nModel Test User Model:\n                                                      \n  Test statistic                                98.591\n  Degrees of freedom                                19\n  P-value (Chi-square)                           0.000\n\nParameter Estimates:\n\n  Standard errors                             Standard\n  Information                                 Expected\n  Information saturated (h1) model          Structured\n\nLatent Variables:\n                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all\n  AT =~                                                                 \n    LUAT1             1.000                               1.284    0.802\n    LUAT2             1.026    0.065   15.670    0.000    1.317    0.847\n    LUAT3             1.056    0.068   15.415    0.000    1.356    0.828\n  BE =~                                                                 \n    LUBE1             1.000                               1.581    0.897\n    LUBE2             0.965    0.043   22.562    0.000    1.524    0.910\n    LUBE3             0.802    0.048   16.729    0.000    1.267    0.755\n    LUBE4             0.441    0.053    8.382    0.000    0.698    0.451\n    LUBE5             0.613    0.055   11.148    0.000    0.969    0.570\n\nCovariances:\n                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all\n  AT ~~                                                                 \n    BE                1.154    0.153    7.563    0.000    0.569    0.569\n\nVariances:\n                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all\n   .LUAT1             0.912    0.100    9.125    0.000    0.912    0.356\n   .LUAT2             0.686    0.089    7.663    0.000    0.686    0.283\n   .LUAT3             0.845    0.101    8.346    0.000    0.845    0.315\n   .LUBE1             0.604    0.082    7.344    0.000    0.604    0.195\n   .LUBE2             0.483    0.073    6.650    0.000    0.483    0.172\n   .LUBE3             1.210    0.109   11.151    0.000    1.210    0.430\n   .LUBE4             1.906    0.154   12.402    0.000    1.906    0.797\n   .LUBE5             1.956    0.161   12.147    0.000    1.956    0.676\n    AT                1.649    0.201    8.205    0.000    1.000    1.000\n    BE                2.498    0.249   10.034    0.000    1.000    1.000\n```\n\n\n:::\n:::\n\n\nFactor `AT` exhibited high factor loadings (ranging from approximately 0.80 to 0.85) for all three items (LUAT1–LUAT3), confirming a sufficient association. Regarding the `BE` factor, while LUBE1–LUBE3 displayed high factor loadings, the loading for `LUBE4` was marginally low at **0.451**. Similar to the one-factor model, this necessitates a cautious evaluation regarding validity. Conversely, `LUBE2` and `LUBE1` demonstrated extremely high factor loadings (**0.910** and **0.897**, respectively), suggesting they can be interpreted as the core observed variables constituting the `BE` factor.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_2F <- cfa(model_cfa_2F, data = dat_lu)\nlavaanPlot(model = fit_2F,\n           edge_options = list(color = \"grey20\"),\n           coefs = T, covs = T, stand = TRUE)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"grViz html-widget html-fill-item\" id=\"htmlwidget-0e809862d2ef26df6c67\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-0e809862d2ef26df6c67\">{\"x\":{\"diagram\":\" digraph plot { \\n graph [ overlap = true, fontsize = 10 ] \\n node [ shape = box ] \\n node [shape = box] \\n LUAT1; LUAT2; LUAT3; LUBE1; LUBE2; LUBE3; LUBE4; LUBE5 \\n node [shape = oval] \\n AT; BE \\n \\n edge [ color = grey20 ] \\n  AT->LUAT1 [label = \\\"0.8\\\"] AT->LUAT2 [label = \\\"0.85\\\"] AT->LUAT3 [label = \\\"0.83\\\"] BE->LUBE1 [label = \\\"0.9\\\"] BE->LUBE2 [label = \\\"0.91\\\"] BE->LUBE3 [label = \\\"0.76\\\"] BE->LUBE4 [label = \\\"0.45\\\"] BE->LUBE5 [label = \\\"0.57\\\"] BE -> AT [label = \\\"0.57\\\", dir = \\\"both\\\"]\\n}\",\"config\":{\"engine\":\"dot\",\"options\":null}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\nThis figure presents the path diagram of the measurement model in which two latent factors, `AT` and `BE`, correspond to the eight items in the `LUAT` and `LUBE` series. In this model, the three items LUAT1 through LUAT3 are mapped to the AT factor, while the five items LUBE1 through LUBE5 are mapped to the BE factor. The values on each arrow represent the standardized factor loadings (`Std.all`). For the `BE` factor, `LUBE1` (0.90), `LUBE2` (0.91), and `LUBE3` (0.76) exhibit **high** loadings, indicating that they represent BE well. Conversely, `LUBE4` shows a somewhat **low** loading of 0.45, suggesting a weak association with `BE`. `LUBE5` also shows a relatively lower loading of 0.57, though this is considered within the acceptable range.\n\nRegarding the `AT` factor, all three items (LUAT1–LUAT3) demonstrate **high** factor loadings exceeding 0.80, confirming that AT is measured as a consistent construct. Furthermore, a correlation of approximately **0.57** exists between `AT` and `BE`, visually demonstrating that the two factors share a moderate positive association.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha.coef(dat_lu[,1:3])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8644639\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha.coef(dat_lu[,4:8])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8493303\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstandardizedSolution(result_cfa_2F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     lhs op   rhs est.std    se      z pvalue ci.lower ci.upper\n1     AT =~ LUAT1   0.802 0.026 30.791      0    0.751    0.854\n2     AT =~ LUAT2   0.847 0.023 36.036      0    0.801    0.893\n3     AT =~ LUAT3   0.828 0.025 33.720      0    0.780    0.876\n4     BE =~ LUBE1   0.897 0.016 55.385      0    0.866    0.929\n5     BE =~ LUBE2   0.910 0.015 58.892      0    0.880    0.940\n6     BE =~ LUBE3   0.755 0.027 28.112      0    0.703    0.808\n7     BE =~ LUBE4   0.451 0.047  9.625      0    0.359    0.543\n8     BE =~ LUBE5   0.570 0.040 14.168      0    0.491    0.648\n9  LUAT1 ~~ LUAT1   0.356 0.042  8.513      0    0.274    0.438\n10 LUAT2 ~~ LUAT2   0.283 0.040  7.121      0    0.205    0.361\n11 LUAT3 ~~ LUAT3   0.315 0.041  7.748      0    0.235    0.395\n12 LUBE1 ~~ LUBE1   0.195 0.029  6.691      0    0.138    0.252\n13 LUBE2 ~~ LUBE2   0.172 0.028  6.122      0    0.117    0.227\n14 LUBE3 ~~ LUBE3   0.430 0.041 10.591      0    0.350    0.509\n15 LUBE4 ~~ LUBE4   0.797 0.042 18.838      0    0.714    0.879\n16 LUBE5 ~~ LUBE5   0.676 0.046 14.749      0    0.586    0.765\n17    AT ~~    AT   1.000 0.000     NA     NA    1.000    1.000\n18    BE ~~    BE   1.000 0.000     NA     NA    1.000    1.000\n19    AT ~~    BE   0.569 0.045 12.706      0    0.481    0.656\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstd_est_2F <- standardizedSolution(result_cfa_2F)\ncr_ave(\"AT\", std_est_2F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8653893 0.6819309\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncr_ave(\"BE\", std_est_2F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8498482 0.5463049\n```\n\n\n:::\n:::\n\n\nFor both latent factors `AT` and `BE`, **Cronbach's alpha** coefficients and **Composite Reliability (CR)** were high, at approximately 0.85, well exceeding the threshold (≥ 0.70). This demonstrates that the observed variables within each factor possess high internal consistency and stably measure the same construct.\n\nRegarding convergent validity, the **Average Variance Extracted (AVE)** was 0.682 for `AT` and 0.546 for `BE`, both surpassing the benchmark of 0.50. In particular, `AT` exhibited a notably high value of 0.682, indicating that the observed variables strongly reflect the latent factor. Similarly, the `AVE` for `BE` (0.546) met the criterion, suggesting that convergent validity is maintained.\n\nBased on these results, it can be concluded that both `AT` and `BE` in the two-factor model satisfy sufficient standards in terms of both reliability and validity.\n\n## 2.3 Comparison of Models\n\nBased on the results obtained, the one-factor and two-factor models are compared. First, as indicated in the previous sections, the two-factor model demonstrates a substantial improvement in goodness-of-fit indices. These comparisons are summarized in the table below.\n\n| Index | 1-Factor Model | 2-Factor Model | Criteria | Comments |\n|:---|:--:|:--:|:--:|:---|\n| **GFI** | 0.734 | **0.931** | $\\ge$ 0.90 | Improved in 2-Factor |\n| **AGFI** | 0.521 | **0.869** | $\\ge$ 0.85 | Improved in 2-Factor |\n| **RMSEA** | 0.243 | **0.114** | $\\le$ 0.10 | High in both, but improved |\n| **SRMR** | 0.130 | **0.066** | $\\le$ 0.08 | Clearly improved |\n\nRegarding factor loadings, the one-factor model exhibited some low values, particularly for `LUBE4` (0.451) and the `LUAT` items, indicating variation in the factor structure. In contrast, the two-factor model showed high factor loadings ($\\ge$ 0.80) for `LUAT1`–`3` on the `AT` factor, and `LUBE1`–`3` were also strongly linked to `BE`. However, `LUBE4` remained somewhat low (0.451) even in the two-factor model, suggesting room for improvement.\n\nThe comparison of reliability and validity metrics is presented in the following table.\n\n| Factor | Model | $\\alpha$ | CR | AVE | Comments |\n|:---|:--:|:--:|:--:|:--:|:---|\n| **LU** | 1-Factor | 0.869 | 0.859 | 0.447 | AVE below threshold; concern for convergent validity |\n| **AT** | 2-Factor | 0.864 | 0.865 | 0.682 | All indices are good |\n| **BE** | 2-Factor | 0.849 | 0.850 | 0.546 | All indices within acceptable range |\n\nAs indicated in the table above, both CR and AVE improved in the two-factor model. Notably, the AVE for the `AT` factor is very high at 0.682, reflecting an improvement in measurement precision.\n\nIn conclusion, the two-factor model is evaluated as superior to the one-factor model across all dimensions: model fit indices, factor loading structure, reliability, and convergent validity. Specifically, structuring the `LUAT` series and `LUBE` series as separate factors (`AT` and `BE`) yields a more valid and interpretable measurement model.\n\n## 3. Confirmatory Factor Analysis with Two Factors Excluding LUBE4\n\nFollowing the same procedure as in the previous section, the model construction, estimation, assessment of goodness-of-fit indices, visualization of results, and evaluation of reliability and validity are conducted. Subsequently, a comparison with the original two-factor CFA and an interpretation of the results are performed.\n\n### 3.1 Two-Factor CFA Excluding LUBE4\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_cfa_2F_trim <- '\n  AT =~ LUAT1 + LUAT2 + LUAT3\n  BE =~ LUBE1 + LUBE2 + LUBE3 + LUBE5   \n'\n\nresult_cfa_2F_trim <- lavaan::sem(model_cfa_2F_trim, data = dat_lu)\nfitMeasures(result_cfa_2F_trim)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 npar                  fmin                 chisq \n               15.000                 0.069                44.168 \n                   df                pvalue        baseline.chisq \n               13.000                 0.000              1300.060 \n          baseline.df       baseline.pvalue                   cfi \n               21.000                 0.000                 0.976 \n                  tli                  nnfi                   rfi \n                0.961                 0.961                 0.945 \n                  nfi                  pnfi                   ifi \n                0.966                 0.598                 0.976 \n                  rni                  logl     unrestricted.logl \n                0.976             -3709.274             -3687.191 \n                  aic                   bic                ntotal \n             7448.549              7505.167               322.000 \n                 bic2                 rmsea        rmsea.ci.lower \n             7457.589                 0.086                 0.059 \n       rmsea.ci.upper        rmsea.ci.level          rmsea.pvalue \n                0.115                 0.900                 0.016 \n       rmsea.close.h0 rmsea.notclose.pvalue     rmsea.notclose.h0 \n                0.050                 0.673                 0.080 \n                  rmr            rmr_nomean                  srmr \n                0.163                 0.163                 0.060 \n         srmr_bentler   srmr_bentler_nomean                  crmr \n                0.060                 0.060                 0.069 \n          crmr_nomean            srmr_mplus     srmr_mplus_nomean \n                0.069                 0.060                 0.060 \n                cn_05                 cn_01                   gfi \n              164.028               202.858                 0.965 \n                 agfi                  pgfi                   mfi \n                0.924                 0.448                 0.953 \n                 ecvi \n                0.230 \n```\n\n\n:::\n:::\n\n\nThe model fit indices—`GFI` = 0.965 (≥ 0.90), `AGFI` = 0.924 (≥ 0.85), `RMSEA` = 0.086 (≤ 0.1), and `SRMR` = 0.06 (≤ 0.08)—all satisfy the established criteria. Consequently, it can be concluded that the overall model fit is excellent.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(result_cfa_2F_trim, standardized = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlavaan 0.6-21 ended normally after 30 iterations\n\n  Estimator                                         ML\n  Optimization method                           NLMINB\n  Number of model parameters                        15\n\n  Number of observations                           322\n\nModel Test User Model:\n                                                      \n  Test statistic                                44.168\n  Degrees of freedom                                13\n  P-value (Chi-square)                           0.000\n\nParameter Estimates:\n\n  Standard errors                             Standard\n  Information                                 Expected\n  Information saturated (h1) model          Structured\n\nLatent Variables:\n                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all\n  AT =~                                                                 \n    LUAT1             1.000                               1.283    0.802\n    LUAT2             1.026    0.066   15.656    0.000    1.317    0.846\n    LUAT3             1.058    0.069   15.419    0.000    1.357    0.829\n  BE =~                                                                 \n    LUBE1             1.000                               1.584    0.899\n    LUBE2             0.971    0.043   22.630    0.000    1.537    0.918\n    LUBE3             0.787    0.048   16.335    0.000    1.247    0.743\n    LUBE5             0.600    0.055   10.874    0.000    0.950    0.558\n\nCovariances:\n                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all\n  AT ~~                                                                 \n    BE                1.157    0.153    7.567    0.000    0.569    0.569\n\nVariances:\n                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all\n   .LUAT1             0.914    0.100    9.141    0.000    0.914    0.357\n   .LUAT2             0.687    0.090    7.680    0.000    0.687    0.284\n   .LUAT3             0.841    0.101    8.318    0.000    0.841    0.313\n   .LUBE1             0.594    0.084    7.075    0.000    0.594    0.192\n   .LUBE2             0.444    0.074    5.998    0.000    0.444    0.158\n   .LUBE3             1.262    0.112   11.284    0.000    1.262    0.448\n   .LUBE5             1.994    0.164   12.187    0.000    1.994    0.689\n    AT                1.647    0.201    8.198    0.000    1.000    1.000\n    BE                2.508    0.250   10.037    0.000    1.000    1.000\n```\n\n\n:::\n:::\n\n\nFactor `AT` exhibited high factor loadings (ranging from approximately 0.80 to 0.85) for all three items (`LUAT1`–`LUAT3`), confirming a sufficient association. Regarding the `BE` factor, while `LUBE1`–`LUBE3` displayed high factor loadings, the loading for LUBE5 was marginally low at 0.558. Similar to previous models, this necessitates a cautious evaluation regarding validity. However, regarding the other variables, even the lowest value observed was `LUBE3` (0.743), which maintains a favorable level; thus, the variables demonstrate a sufficient association with the two factors.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_2F_trim <- cfa(model_cfa_2F_trim, data = dat_lu)\nlavaanPlot(model = fit_2F_trim,\n           edge_options = list(color = \"grey20\"),\n           coefs = T, covs = T, stand = TRUE)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"grViz html-widget html-fill-item\" id=\"htmlwidget-d4bd9e5e95e3e5ff31d9\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-d4bd9e5e95e3e5ff31d9\">{\"x\":{\"diagram\":\" digraph plot { \\n graph [ overlap = true, fontsize = 10 ] \\n node [ shape = box ] \\n node [shape = box] \\n LUAT1; LUAT2; LUAT3; LUBE1; LUBE2; LUBE3; LUBE5 \\n node [shape = oval] \\n AT; BE \\n \\n edge [ color = grey20 ] \\n  AT->LUAT1 [label = \\\"0.8\\\"] AT->LUAT2 [label = \\\"0.85\\\"] AT->LUAT3 [label = \\\"0.83\\\"] BE->LUBE1 [label = \\\"0.9\\\"] BE->LUBE2 [label = \\\"0.92\\\"] BE->LUBE3 [label = \\\"0.74\\\"] BE->LUBE5 [label = \\\"0.56\\\"] BE -> AT [label = \\\"0.57\\\", dir = \\\"both\\\"]\\n}\",\"config\":{\"engine\":\"dot\",\"options\":null}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\nThis structure indicates that the three items `LUAT1`–`LUAT3` correspond to the `AT` factor, while the items from the `LUBE` series (`LUBE1`–`LUBE5`) correspond to the `BE` factor. Consistent with the original two-factor model, `LUBE1` (0.90), `LUBE2` (0.92), and `LUBE3` (0.74) exhibit high loadings on the `BE` factor, indicating that they represent the construct well. Conversely, `LUBE5` shows a somewhat lower loading of 0.56. Regarding the `AT` factor, all three items (`LUAT1`–`LUAT3`) demonstrate high factor loadings exceeding 0.80, confirming that `AT` is measured as a consistent construct. Furthermore, a correlation of approximately 0.57 exists between `AT` and `BE`, remaining similar to the original two-factor model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha.coef(dat_lu[,1:3])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8644639\n```\n\n\n:::\n\n```{.r .cell-code}\nalpha.coef(dat_lu[, c(\"LUBE1\", \"LUBE2\", \"LUBE3\", \"LUBE5\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8577357\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(dat_lu)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  LUAT1 LUAT2 LUAT3 LUBE1 LUBE2 LUBE3 LUBE4 LUBE5\n1     5     5     5     3     3     6     6     4\n2     2     1     1     2     5     5     5     5\n3     3     3     3     3     3     3     6     6\n4     2     2     2     2     2     2     5     5\n5     3     2     4     5     4     4     4     5\n6     3     2     6     6     5     6     6     4\n```\n\n\n:::\n\n```{.r .cell-code}\nstandardizedSolution(result_cfa_2F_trim)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     lhs op   rhs est.std    se      z pvalue ci.lower ci.upper\n1     AT =~ LUAT1   0.802 0.026 30.735      0    0.751    0.853\n2     AT =~ LUAT2   0.846 0.024 35.992      0    0.800    0.892\n3     AT =~ LUAT3   0.829 0.024 33.830      0    0.781    0.877\n4     BE =~ LUBE1   0.899 0.016 54.715      0    0.867    0.931\n5     BE =~ LUBE2   0.918 0.015 59.517      0    0.887    0.948\n6     BE =~ LUBE3   0.743 0.028 26.719      0    0.688    0.797\n7     BE =~ LUBE5   0.558 0.041 13.650      0    0.478    0.638\n8  LUAT1 ~~ LUAT1   0.357 0.042  8.529      0    0.275    0.439\n9  LUAT2 ~~ LUAT2   0.284 0.040  7.136      0    0.206    0.362\n10 LUAT3 ~~ LUAT3   0.313 0.041  7.722      0    0.234    0.393\n11 LUBE1 ~~ LUBE1   0.192 0.030  6.481      0    0.134    0.249\n12 LUBE2 ~~ LUBE2   0.158 0.028  5.587      0    0.103    0.214\n13 LUBE3 ~~ LUBE3   0.448 0.041 10.848      0    0.367    0.529\n14 LUBE5 ~~ LUBE5   0.689 0.046 15.094      0    0.599    0.778\n15    AT ~~    AT   1.000 0.000     NA     NA    1.000    1.000\n16    BE ~~    BE   1.000 0.000     NA     NA    1.000    1.000\n17    AT ~~    BE   0.569 0.045 12.742      0    0.482    0.657\n```\n\n\n:::\n\n```{.r .cell-code}\nstd_est_2F_trim <- standardizedSolution(result_cfa_2F_trim)\ncr_ave(\"AT\", std_est_2F_trim)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8653737 0.6819034\n```\n\n\n:::\n\n```{.r .cell-code}\ncr_ave(\"BE\", std_est_2F_trim)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8673646 0.6284229\n```\n\n\n:::\n:::\n\n\nFor both latent factors `AT` and `BE`, **Cronbach's alpha** coefficients and **Composite Reliability (CR)** were high, at approximately 0.85, well exceeding the threshold (≥ 0.70). This demonstrates that the observed variables within each factor possess high internal consistency and stably measure the same construct.\n\nRegarding convergent validity, the **Average Variance Extracted (AVE)** was 0.682 for `AT` and 0.546 for `BE`, both surpassing the benchmark of 0.50. In particular, `AT` exhibited a notably high value of 0.682, indicating that the observed variables strongly reflect the latent factor. Similarly, the **AVE** for `BE` (0.546) met the criterion, suggesting that convergent validity is maintained.\n\nBased on these results, it can be concluded that both `AT` and `BE` in the two-factor model satisfy sufficient standards in terms of both reliability and validity.\n\n### 3.2 Comparison of the Two-Factor Models\n\nBased on the results obtained, the two-factor models (with and without `LUBE4`) are compared. First, as indicated in the previous sections, the latter model demonstrates an improvement in goodness-of-fit indices. These comparisons are summarized in the table below.\n\n| Index | Original Model | Model w/o LUBE4 | Criteria | Comments |\n|:---|:--:|:--:|:--:|:---|\n| **GFI** | 0.931 | **0.965** | $\\ge$ 0.90 | Improved by removing LUBE4 |\n| **AGFI** | 0.869 | **0.924** | $\\ge$ 0.85 | Improved by removing LUBE4 |\n| **RMSEA** | 0.114 | **0.086** | $\\le$ 0.10 | Clearly improved and cleared criteria |\n| **SRMR** | 0.066 | **0.060** | $\\le$ 0.08 | Slightly improved |\n\nRegarding factor loadings, in the original model, `LUBE4` was the lowest (0.451), introducing variability to the factor structure. However, by removing this item, `LUBE5` became the lowest loading (0.558), while all other items maintained high values of 0.74 or above.\n\nThe comparison of reliability and validity metrics is presented in the following table.\n\n| Factor | Model | $\\alpha$ | CR | AVE | Comments |\n|:---|:--:|:--:|:--:|:--:|:---|\n| **AT** | Before Removal | 0.864 | 0.865 | 0.682 | All indices are favorable |\n| **BE** | Before Removal | 0.849 | 0.850 | 0.546 | All indices within acceptable range |\n| **AT** | After Removal | 0.864 | 0.865 | 0.682 | All indices are favorable |\n| **BE** | After Removal | 0.858 | 0.867 | 0.628 | All indices are favorable |\n\nAs shown in the table above, in the model excluding `LUBE4`, the Average Variance Extracted (AVE) for the `BE` factor improved significantly, confirming an enhancement in measurement precision. Consequently, values satisfying the established criteria were obtained for all aspects: fit indices, factor loading structure, reliability metrics, and convergent validity.\n\nIn conclusion, it is evaluated that a valid CFA model has been successfully constructed, which adequately explains the seven observed variables (excluding `LUBE4`) using two latent factors, `AT` and `BE`.\n",
    "supporting": [
      "report_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../../site_libs/viz-1.8.2/viz.js\"></script>\n<link href=\"../../site_libs/DiagrammeR-styles-0.2/styles.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/grViz-binding-1.0.11/grViz.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}