{
  "hash": "88fd12daebbaafb03dd7001b0c367476",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"DS202A - W08 Summative\"\nauthor: \"62751\"\ndate: \"2026-01-23\"\nformat:\n  html:\n    self-contained: true\n    toc: true\n    toc-location: left-body\n    code-fold: show\n    code-copy: true\n---\n\nFirst, several R packages are loaded to support data cleaning, exploration, and visualisation. Then, consistent minimal theme is also set for all ggplot2 figures to improve readability throughout the analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(janitor)   \nlibrary(skimr)     \nlibrary(naniar)    \nlibrary(GGally)    \nlibrary(patchwork) \nlibrary(reshape2)\nlibrary(vip)\nlibrary(ranger)\n\ntheme_set(theme_minimal(base_size = 12))\n```\n:::\n\n\n# Part 1: Data Exploration\n\n## Q1.1 Load the dataset into a DataFrame\n\nThe dataset file was first moved to the Desktop. It is then loaded into R using the `read.csv` function and stored in a DataFrame named `sleep`. Immediately after loading, `glimpse` is used to inspect the structure, confirming that all variables were imported correctly and providing a quick overview of their variable types and values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsleep <- read.csv(\"data/Sleep_health_and_lifestyle_dataset.csv\")\nglimpse(sleep)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 374\nColumns: 13\n$ Person.ID               <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,…\n$ Gender                  <chr> \"Male\", \"Male\", \"Male\", \"Male\", \"Male\", \"Male\"…\n$ Age                     <int> 27, 28, 28, 28, 28, 28, 29, 29, 29, 29, 29, 29…\n$ Occupation              <chr> \"Software Engineer\", \"Doctor\", \"Doctor\", \"Sale…\n$ Sleep.Duration          <dbl> 6.1, 6.2, 6.2, 5.9, 5.9, 5.9, 6.3, 7.8, 7.8, 7…\n$ Quality.of.Sleep        <int> 6, 6, 6, 4, 4, 4, 6, 7, 7, 7, 6, 7, 6, 6, 6, 6…\n$ Physical.Activity.Level <int> 42, 60, 60, 30, 30, 30, 40, 75, 75, 75, 30, 75…\n$ Stress.Level            <int> 6, 8, 8, 8, 8, 8, 7, 6, 6, 6, 8, 6, 8, 8, 8, 8…\n$ BMI.Category            <chr> \"Overweight\", \"Normal\", \"Normal\", \"Obese\", \"Ob…\n$ Blood.Pressure          <chr> \"126/83\", \"125/80\", \"125/80\", \"140/90\", \"140/9…\n$ Heart.Rate              <int> 77, 75, 75, 85, 85, 85, 82, 70, 70, 70, 70, 70…\n$ Daily.Steps             <int> 4200, 10000, 10000, 3000, 3000, 3000, 3500, 80…\n$ Sleep.Disorder          <chr> \"None\", \"None\", \"None\", \"Sleep Apnea\", \"Sleep …\n```\n\n\n:::\n:::\n\n\nThe `glimpse` output shows the dataset contains **374 observations** and **13 variables**. The variable types have been imported correctly, as summarized below. This confirms the dataset is structured appropriately for subsequent data cleaning, visualisation, and modelling.\n\n| Variable Type | Examples |\n|:-----------------------------------|:-----------------------------------|\n| Numeric (int/double) | `Age`, `Sleep.Duration`, `Physical.Activity.Level`, `Heart.Rate`,etc. |\n| Categorical (character) | `Gender`, `Occupation`, `BMI.Category`, `Sleep.Disorder`,etc. |\n\n## Q1.2 Explore and visualise the data\n\n### Checking for missing data and potential anomalies\n\n::: callout-note\n## Note\n\nAlthough the identification of missing values and anomalies is listed at the end of Q1.2, it is practical to perform these checks at the beginning of the exploratory analysis to ensure that subsequent visualisations and summaries are based on a reliable dataset.\n:::\n\nThe commands below provide an overview of the completeness of the data using `skim()`, followed by calculations of total and column-wise missing values. These checks help determine whether any preprocessing steps such as imputation, removal, or transformation are required before proceeding with further exploration and modelling.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nskim(sleep)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |      |\n|:------------------------|:-----|\n|Name                     |sleep |\n|Number of rows           |374   |\n|Number of columns        |13    |\n|_______________________  |      |\n|Column type frequency:   |      |\n|character                |5     |\n|numeric                  |8     |\n|________________________ |      |\n|Group variables          |None  |\n\n\n**Variable type: character**\n\n|skim_variable  | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:--------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|Gender         |         0|             1|   4|   6|     0|        2|          0|\n|Occupation     |         0|             1|   5|  20|     0|       11|          0|\n|BMI.Category   |         0|             1|   5|  13|     0|        4|          0|\n|Blood.Pressure |         0|             1|   6|   6|     0|       25|          0|\n|Sleep.Disorder |         0|             1|   4|  11|     0|        3|          0|\n\n\n**Variable type: numeric**\n\n|skim_variable           | n_missing| complete_rate|    mean|      sd|     p0|     p25|    p50|     p75|    p100|hist  |\n|:-----------------------|---------:|-------------:|-------:|-------:|------:|-------:|------:|-------:|-------:|:-----|\n|Person.ID               |         0|             1|  187.50|  108.11|    1.0|   94.25|  187.5|  280.75|   374.0|▇▇▇▇▇ |\n|Age                     |         0|             1|   42.18|    8.67|   27.0|   35.25|   43.0|   50.00|    59.0|▆▆▇▃▅ |\n|Sleep.Duration          |         0|             1|    7.13|    0.80|    5.8|    6.40|    7.2|    7.80|     8.5|▇▆▇▇▆ |\n|Quality.of.Sleep        |         0|             1|    7.31|    1.20|    4.0|    6.00|    7.0|    8.00|     9.0|▁▇▆▇▅ |\n|Physical.Activity.Level |         0|             1|   59.17|   20.83|   30.0|   45.00|   60.0|   75.00|    90.0|▇▇▇▇▇ |\n|Stress.Level            |         0|             1|    5.39|    1.77|    3.0|    4.00|    5.0|    7.00|     8.0|▇▃▂▃▃ |\n|Heart.Rate              |         0|             1|   70.17|    4.14|   65.0|   68.00|   70.0|   72.00|    86.0|▇▇▂▁▁ |\n|Daily.Steps             |         0|             1| 6816.84| 1617.92| 3000.0| 5600.00| 7000.0| 8000.00| 10000.0|▁▅▇▆▂ |\n\n\n:::\n\n```{.r .cell-code}\nsum(is.na(sleep))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\ncolSums(is.na(sleep)) #just in case\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Person.ID                  Gender                     Age \n                      0                       0                       0 \n             Occupation          Sleep.Duration        Quality.of.Sleep \n                      0                       0                       0 \nPhysical.Activity.Level            Stress.Level            BMI.Category \n                      0                       0                       0 \n         Blood.Pressure              Heart.Rate             Daily.Steps \n                      0                       0                       0 \n         Sleep.Disorder \n                      0 \n```\n\n\n:::\n:::\n\n\nThe summary indicates that the dataset contains 374 observations and 13 variables, with a mix of numeric and categorical fields(consistent with the `glimpse` outcome). The missing-value checks show that there are **no missing entries** in any column. This confirms that the dataset is fully complete, requiring no imputation or removal of incomplete observations.\n\n### Data Cleaning\n\nTo prepare the data for regression modeling, several preprocessing steps are first applied to create a new `sleep_clean` dataframe. This involves standardizing column names to **snake_case**, removing the non-predictive person_id column, separating the blood_pressure string into numeric *bp_systolic* and *bp_diastolic* columns, and converting all character-based columns to factors for correct model interpretation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsleep_clean <- sleep |>\n  janitor::clean_names() |>\n  select(-person_id) |>\n  separate(\n    blood_pressure,\n    into = c(\"bp_systolic\", \"bp_diastolic\"),\n    sep = \"/\",\n    convert = TRUE \n  ) |>\n  mutate(\n    across(where(is.character), as.factor)\n  )\nglimpse(sleep_clean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 374\nColumns: 13\n$ gender                  <fct> Male, Male, Male, Male, Male, Male, Male, Male…\n$ age                     <int> 27, 28, 28, 28, 28, 28, 29, 29, 29, 29, 29, 29…\n$ occupation              <fct> Software Engineer, Doctor, Doctor, Sales Repre…\n$ sleep_duration          <dbl> 6.1, 6.2, 6.2, 5.9, 5.9, 5.9, 6.3, 7.8, 7.8, 7…\n$ quality_of_sleep        <int> 6, 6, 6, 4, 4, 4, 6, 7, 7, 7, 6, 7, 6, 6, 6, 6…\n$ physical_activity_level <int> 42, 60, 60, 30, 30, 30, 40, 75, 75, 75, 30, 75…\n$ stress_level            <int> 6, 8, 8, 8, 8, 8, 7, 6, 6, 6, 8, 6, 8, 8, 8, 8…\n$ bmi_category            <fct> Overweight, Normal, Normal, Obese, Obese, Obes…\n$ bp_systolic             <int> 126, 125, 125, 140, 140, 140, 140, 120, 120, 1…\n$ bp_diastolic            <int> 83, 80, 80, 90, 90, 90, 90, 80, 80, 80, 80, 80…\n$ heart_rate              <int> 77, 75, 75, 85, 85, 85, 82, 70, 70, 70, 70, 70…\n$ daily_steps             <int> 4200, 10000, 10000, 3000, 3000, 3000, 3500, 80…\n$ sleep_disorder          <fct> None, None, None, Sleep Apnea, Sleep Apnea, In…\n```\n\n\n:::\n:::\n\n\n::: callout-note\n## Data Cleaning Summary\n\n-   All column names are now in **snake_case** (e.g., sleep_duration).\n\n-   The original blood_pressure string has been successfully separated into two new numeric columns, `bp_systolic` and `bp_diastolic`.\n\n-   All categorical variables, such as `gender` and `occupation`, have been converted from text (`<chr>`) to factors (`<fct>`).\n\n-   The `person_id` column has also been removed, and the data is now ready for analysis.\n:::\n\n### Distribution of Numeric Predictors\n\nTo ensure the reliability of regression models (Part 2), it is important to check the **distribution** of the numeric predictors. Models like linear and regularized regression perform optimally when predictors are (approximately) **normally distributed**. The following histograms visualize the distribution of each numeric variable cleaned in Q2.1 (excluding sleep_duration itself).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnumeric_predictors <- sleep_clean |>\n  select(where(is.numeric), -sleep_duration)\n\nnumeric_predictors |>\n  pivot_longer(everything(), names_to = \"variable\", values_to = \"value\") |>\n  \n  ggplot(aes(x = value)) +\n  geom_histogram(bins = 20, fill = \"steelblue\", alpha = 0.8) +\n  facet_wrap(~ variable, scales = \"free\") +\n  labs(\n    title = \"Distributions of Numeric Predictors\",\n    x = \"Value\",\n    y = \"Count\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](62751_files/figure-html/skewness-1.png){width=672}\n:::\n:::\n\n\nThe histograms reveal that several key predictors are not normally distributed, which could impact regression performance. While `quality_of_sleep` exhibits a clear left-skew, other important predictors like `physical_activity_level` and `daily_steps` do not show a simple, smooth skew. Instead, their distributions are visibly multi-modal, with data clustered around a few distinct peaks (e.g., 30, 45, 60 minutes of activity, or 5000, 8000 steps), suggesting they behave more like discrete or ordinal variables. This discrete and **non-bell-shaped** nature of the predictors can violate the assumptions of linear-based models like Elastic Net. Therefore, in the Part 2 modeling recipe, applying a transformation like the **Yeo-Johnson transformation** will be considered as a critical strategy to help normalize these distributions and improve potential model performance.\n\n::: callout-note\n## A Methodological Note on Data Leakage\n\nIdeally, these predictor distributions would be assessed *only* on the `train_data` after splitting to prevent any data leakage. However, given the small sample size (n=374), the full dataset was used for this initial EDA to gain a more stable understanding of the underlying distributions. This knowledge is crucial for informing the modeling approach (e.g., the need for `step_YeoJohnson`), representing a pragmatic tradeoff. The transformation parameters themselves will, of course, be learned *only* from the `train_data` during the `prep()` step in **Part 2**.\n:::\n\n### Correlations with Sleep Duration\n\nTo assess how numerical features relate to `sleep_duration`, a correlation matrix is computed and the correlations specific to `sleep_duration` are examined. To complement this analysis, **a full correlation heatmap** is also produced, providing a clearer overview of how all numeric variables relate to one another.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsleep_numeric <- sleep_clean |>\nselect(where(is.numeric))\n\ncor_matrix <- cor(sleep_numeric, use = \"complete.obs\")\ncor_sleep_duration <- cor_matrix[\"sleep_duration\", ] |>\nsort(decreasing = TRUE)\ncor_sleep_duration\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         sleep_duration        quality_of_sleep                     age \n             1.00000000              0.88321300              0.34470936 \nphysical_activity_level             daily_steps            bp_diastolic \n             0.21236031             -0.03953254             -0.16656987 \n            bp_systolic              heart_rate            stress_level \n            -0.18040628             -0.51645489             -0.81102303 \n```\n\n\n:::\n\n```{.r .cell-code}\ntibble(\nvariable = names(cor_sleep_duration),\ncorrelation = as.numeric(cor_sleep_duration)\n) |>\nggplot(aes(x = reorder(variable, correlation), y = correlation)) +\ngeom_col() +\ncoord_flip() +\nlabs(\nx = \"Variable\",\ny = \"Correlation with Sleep Duration\",\ntitle = \"Correlation of Numeric Features with Sleep Duration\"\n)\n```\n\n::: {.cell-output-display}\n![](62751_files/figure-html/selection-1.png){width=672}\n:::\n:::\n\n\n| `sleep_duration` | `quality_of_sleep` | `age` | `physical_activity_level` | `daily_steps` | `bp_diastolic` | `bp_systolic` | `heart_rate` | `stress_level` |\n|:------:|:------:|:------:|:------:|:------:|:------:|:------:|:------:|:------:|\n| 1.00 | 0.88 | 0.34 | 0.21 | -0.040 | -0.17 | -0.18 | -0.52 | -0.81 |\n\n::: callout-note\n## Correlation summary\n\nThe table highlights several key relationships with `sleep_duration`:\n\n-   **Strong Positive:** `quality_of_sleep` (0.88)\n-   **Strong Negative:** `stress_level` (-0.81)\\\n-   **Moderate Associations:** `heart_rate` (-0.52) has a moderate negative association, while `age` (0.34) has a moderate positive one.\n-   **Weak Associations:** `physical_activity_level` (0.21), `daily_steps` (-0.04), and the blood pressure metrics show weak relationships.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor_m <- cor(sleep_numeric, use = \"complete.obs\")\nggplot(melt(cor_m), aes(Var1, Var2, fill = value)) +\n  geom_tile() +\n  scale_fill_gradient2(low = \"blue\", high = \"red\", mid = \"white\", midpoint = 0) +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +\n  labs(\n    title = \"Correlation Heatmap of Numeric Variables\",\n    x = \"\",\n    y = \"\",\n    fill = \"Correlation\"\n  )\n```\n\n::: {.cell-output-display}\n![](62751_files/figure-html/matrix-1.png){width=672}\n:::\n:::\n\n\nThe accompanying correlation heatmap reinforces these patterns, illustrating the strong positive block between `sleep_duration`, `sleep_quality`, and `age`, alongside the contrasting negative cluster centred on `stress_level` and `heart_rate`. The heatmap also reveals limited connections among the remaining variables, confirming that only a subset of features display meaningful linear associations. Taken together, these results highlight `sleep_quality` and `stress_level` as the most influential numeric predictors of `sleep_duration` within the broader correlation structure of the dataset.\n\n::: callout-note\n## Potential of Multicollinearity\n\nThe strong negative correlation between `quality_of_sleep` and `stress_level`, as well as the pronounced positive correlation between `bp_diastolic` and `bp_systolic`, indicates potential multicollinearity. In subsequent modelling, these pairs may provide overlapping information.\n:::\n\n### Creating multi-variable plots\n\nTo further explore the relationships between `sleep_duration` and multiple lifestyle or demographic factors, several multi-variable visualisations are constructed. These plots combine two or more predictors in a single figure through colour, faceting, or categorical grouping, allowing the joint patterns between `physical_activity`, `heart_rate`, `stress_level`, `gender`, `sleep_disorder` status, and `age_groups` to be examined simultaneously.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot(sleep_clean, aes(\n  x = physical_activity_level,\n  y = sleep_duration,\n  colour = heart_rate\n)) +\n  geom_point(alpha = 0.7, size = 2.5) +\n  labs(\n    x = \"Physical Activity Level (min/day)\",\n    y = \"Sleep Duration (hours)\",\n    colour = \"Heart Rate (bpm)\"\n  ) +\n  theme(plot.title = element_text(size = 10))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np2 <- ggplot(sleep_clean, aes(\n  x = physical_activity_level,\n  y = sleep_duration,\n  colour = gender\n)) +\n  geom_point(alpha = 0.7, size = 2.5) +\n  labs(\n    x = \"Physical Activity Level (min/day)\",\n    y = \"Sleep Duration (hours)\",\n    colour = \"Gender\"\n  ) +\n  theme(plot.title = element_text(size = 10))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np3 <- ggplot(sleep_clean, aes(\n  x = physical_activity_level,\n  y = sleep_duration,\n  colour = stress_level\n)) +\n  geom_point(alpha = 0.7, size = 2) +\n  facet_wrap(~ sleep_disorder) +\n  labs(\n    x = \"Physical Activity Level (min/day)\",\n    y = \"Sleep Duration (hours)\",\n    colour = \"Stress Level\",\n    title = \"Sleep Duration by Activity and Stress Level\\nFaceted by Sleep Disorder\"\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np4 <- ggplot(sleep_clean, aes(\n  x = heart_rate,\n  y = sleep_duration,\n  colour = stress_level\n)) +\n  geom_point(alpha = 0.7, size = 2.5) +\n  labs(\n    x = \"Heart Rate (bpm)\",\n    y = \"Sleep Duration (hours)\",\n    colour = \"Stress Level\"\n  ) +\n  theme(plot.title = element_text(size = 10))\n\np1  \n```\n\n::: {.cell-output-display}\n![](62751_files/figure-html/multi-variate4-1.png){width=672}\n:::\n\n```{.r .cell-code}\np2\n```\n\n::: {.cell-output-display}\n![](62751_files/figure-html/multi-variate4-2.png){width=672}\n:::\n\n```{.r .cell-code}\np3  \n```\n\n::: {.cell-output-display}\n![](62751_files/figure-html/multi-variate4-3.png){width=672}\n:::\n\n```{.r .cell-code}\np4\n```\n\n::: {.cell-output-display}\n![](62751_files/figure-html/multi-variate4-4.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsleep_clean <- sleep_clean |>\nmutate(\nage_group = cut(\nage,\nbreaks = c(0, 30, 45, 60, Inf),\nlabels = c(\"≤30\", \"31–45\", \"46–60\", \"60+\")\n)\n)\n\np_age_gender <- ggplot(sleep_clean, aes(x = age_group, y = sleep_duration, fill = gender)) +\ngeom_boxplot(position = position_dodge(width = 0.8)) +\nlabs(\ntitle = \"Sleep Duration by Age Group and Gender\",\nx = \"Age Group\",\ny = \"Sleep Duration (hours)\",\nfill = \"Gender\"\n)\n\np_occ_disorder <- ggplot(sleep_clean, aes(\nx = forcats::fct_reorder(occupation, sleep_duration, .fun = median),\ny = sleep_duration,\nfill = sleep_disorder\n)) +\ngeom_boxplot(outlier.alpha = 0.4) +\ncoord_flip() +\nlabs(\ntitle = \"Sleep Duration by Occupation and Sleep Disorder\",\nx = \"Occupation\",\ny = \"Sleep Duration (hours)\",\nfill = \"Sleep Disorder\"\n)\n\np_age_gender \n```\n\n::: {.cell-output-display}\n![](62751_files/figure-html/multi-variate5-1.png){width=672}\n:::\n\n```{.r .cell-code}\np_occ_disorder\n```\n\n::: {.cell-output-display}\n![](62751_files/figure-html/multi-variate5-2.png){width=672}\n:::\n:::\n\n\nAcross the set of multi-variable plots, several consistent patterns emerge. Higher levels of `physical_activity` are generally associated with longer `sleep_duration`, a relationship that remains visible when colour-coded by `heart_rate` or `gender`. When `stress_level` is introduced as a secondary predictor, higher stress corresponds to shorter sleep, and this trend is further clarified when stratifying the plot by `sleep_disorder` status. Notably, this stratification also mitigates the overplotting observed in the aggregate figures (p1 and p2), revealing that many participants share identical values for activity and sleep. This visual separation highlights the discrete nature of the lifestyle measurements and provides a clearer view of data density within each group. The distributional plots also reveal notable subgroup differences. `sleep_duration` varies across `age_groups` and shows distinct patterns for men and women, while the occupation-based plot demonstrates that both job type and the presence of sleep disorders contribute to variability in `sleep_duration`. Taken together, these visualisations highlight the multifaceted nature of sleep behaviour and illustrate how lifestyle, demographic, and health-related factors interact to influence `sleep_duration`.\n\n# Part 2: Create regression models\n\nThis part focuses on predicting the continuous variable `sleep_duration` (hours) using regression models.\n\n## Q2.1 Splitting the data into training and test sets\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\n\ndata_split <- initial_split(\n  sleep_clean,       \n  prop = 0.75,         \n  strata = sleep_duration \n)\n\ntrain_data <- training(data_split)\ntest_data <- testing(data_split)\n\ncat(dim(train_data))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n279 14\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(dim(test_data))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95 14\n```\n\n\n:::\n:::\n\n\nThe outputs **279 14** for the training set and **95 14** for the test set show that the stratified 75/25 split was carried out correctly. The row counts sum to the original 374 observations, and both datasets retain the same **14-column** structure, confirming that the cleaned data has been partitioned consistently and is ready for subsequent model building.\n\n::: callout-note\n## Note\n\nStratifying the split by `sleep_duration` is preferable to a purely random split in this context. Because the dataset is relatively small, a random split could easily produce `train_data` and `test_data` with meaningfully different `sleep_duration` distributions, which would bias coefficient estimates and produce unstable performance metrics. The stratified split preserves the shape of the outcome distribution across both subsets, leading to more reliable model fitting and more representative out-of-sample evaluation.\n:::\n\n## Q2.2 Fitting a baseline linear regression model\n\nThe next step is to fit the baseline linear regression model. This serves as a reference point for performance and is typically constructed by including all available predictors. A tidymodels workflow is established for this purpose. First, a `linear_reg()` specification is defined using the **\"lm\"** engine. A corresponding recipe is created, using the formula `sleep_duration ~` . to designate `sleep_duration` as the outcome and all other variables as predictors. Within this recipe, `step_rm(age_group)` is used to prevent multicollinearity with the age variable, and `step_dummy(all_nominal_predictors())` is applied to convert all factor variables into binary indicators for the regression. This model and recipe are bundled into a workflow and then fitted to the `train_data` to create thebaseline_fit\\` object.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_spec <- linear_reg() |>\n  set_engine(\"lm\")\n\nlm_recipe <- recipe(sleep_duration ~ ., data = train_data) |>\n  step_rm(age_group) |> \n  step_dummy(all_nominal_predictors())\n\nlm_workflow <- workflow() |>\n  add_model(lm_spec) |>\n  add_recipe(lm_recipe)\n\nbaseline_fit <- fit(lm_workflow, data = train_data)\n\ntidy(baseline_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 25 × 5\n   term                     estimate std.error statistic     p.value\n   <chr>                       <dbl>     <dbl>     <dbl>       <dbl>\n 1 (Intercept)              5.08     1.48          3.44  0.000681   \n 2 age                      0.0262   0.00807       3.24  0.00134    \n 3 quality_of_sleep         0.336    0.0634        5.29  0.000000258\n 4 physical_activity_level  0.00905  0.00170       5.31  0.000000235\n 5 stress_level            -0.166    0.0389       -4.27  0.0000281  \n 6 bp_systolic             -0.114    0.0222       -5.13  0.000000575\n 7 bp_diastolic             0.129    0.0288        4.47  0.0000118  \n 8 heart_rate               0.0441   0.0129        3.41  0.000754   \n 9 daily_steps             -0.000119 0.0000282    -4.22  0.0000347  \n10 gender_Male             -0.0143   0.0978       -0.147 0.884      \n# ℹ 15 more rows\n```\n\n\n:::\n:::\n\n\nThe `tidy()` output confirms the baseline model was successfully fitted and provides a detailed summary of its coefficients, standard errors, and statistical significance on the training data. The estimate column quantifies the association of each predictor; for instance, the coefficient for `quality_of_sleep (0.336)` suggests that a one-point increase in sleep quality is associated with an increase of 0.336 hour in sleep duration, holding all other variables constant. Conversely, `stress_level (-0.166)` and `bp_systolic (-0.114)` show strong negative associations. The p.value column indicates statistical significance, with most predictors like `quality_of_sleep`, `physical_activity_level`, and `stress_level` showing very low p-values (e.g., \\< 0.0001), suggesting strong evidence for their relationship with `sleep_duration`. Notably, `gender_Male (p-value 0.884)` is not statistically significant in this model. This detailed table establishes the baseline coefficients, which will be evaluated for predictive accuracy in the next section.\n\n## Q2.3 Evaluating the model performance\n\nTo assess the model's predictive power, the evaluation is performed exclusively on the `test_data`. This provides an honest and unbiased estimate of the model's generalization ability, or how well it will perform on new data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredictions_test <- predict(baseline_fit, new_data = test_data) |>\n  bind_cols(test_data |> select(sleep_duration))\n\nhead(predictions_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  .pred sleep_duration\n  <dbl>          <dbl>\n1  6.72            6.1\n2  5.96            6.2\n3  5.96            6.2\n4  7.38            7.8\n5  7.38            7.8\n6  7.38            7.8\n```\n\n\n:::\n\n```{.r .cell-code}\nbaseline_metrics <- metrics(predictions_test,\n                            truth = sleep_duration,\n                            estimate = .pred)\nprint(baseline_metrics)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  .metric .estimator .estimate\n  <chr>   <chr>          <dbl>\n1 rmse    standard       0.295\n2 rsq     standard       0.870\n3 mae     standard       0.208\n```\n\n\n:::\n:::\n\n\nThe output table shows the baseline model's performance on the test set, yielding an **R-squared** `(rsq)` of **0.870** and an **RMSE** of **0.295**. These two metrics were chosen to provide a comprehensive view of performance. The R-squared indicates that the model explains **87.0%** of the variance in sleep duration, which is a very strong measure of \"goodness of fit.\" **The Root Mean Squared Error (RMSE)** is arguably the most important metric here, as it quantifies the typical prediction error in the original units of the outcome. An RMSE of 0.295 means that, on average, the model's predictions for sleep duration are off by about 0.295 hours (or approximately 18 minutes).\n\n## Q2.4 Exploring ways to improve the model\n\nTo improve on the baseline linear regression model, an **Elastic Net regression** is implemented.\n\n::: callout-note\n## Note\n\nElastic Net is a regularised model that combines both Lasso and Ridge penalties, allowing it to perform variable selection while reducing multicollinearity and overfitting. This approach is particularly suitable for this dataset, as several predictors exhibit non-normal distributions and strong pairwise correlations.\n:::\n\nTo prepare the data appropriately for regularised modelling, the recipe applies dummy encoding to categorical variables, removes the manually constructed `age_group` variable to avoid redundancy, and uses the **Yeo–Johnson transformation** followed by **normalisation** to stabilise variance and place all predictors on a comparable scale. The penalty and mixture hyperparameters are tuned using 10-fold **cross-validation** with stratification on the outcome variable to maintain balanced folds. The best-performing parameter combination (based on **RMSE**) is then selected and used to fit the final Elastic Net model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nenet_spec <- linear_reg(penalty = tune(), mixture = tune()) |>\n  set_engine(\"glmnet\")\n\nenet_recipe <- recipe(sleep_duration ~ ., data = train_data) |>\n  step_rm(age_group) |>\n  step_dummy(all_nominal_predictors()) |>\n  step_YeoJohnson(all_numeric_predictors()) |>　# important!\n  step_normalize(all_numeric_predictors())\n\nenet_workflow <- workflow() |>\n  add_model(enet_spec) |>\n  add_recipe(enet_recipe)\n\nset.seed(234) \ntrain_folds <- vfold_cv(train_data, v = 10, strata = sleep_duration)\n\nset.seed(345)\nenet_tune_results <- tune_grid(\n  enet_workflow,\n  resamples = train_folds, \n  grid = 20                \n)\n\ncollect_metrics(enet_tune_results) |>\n  filter(.metric == \"rmse\") |>\n  arrange(mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 20 × 8\n    penalty mixture .metric .estimator  mean     n std_err .config         \n      <dbl>   <dbl> <chr>   <chr>      <dbl> <int>   <dbl> <chr>           \n 1 2.07e- 4    1    rmse    standard   0.259    10 0.0155  pre0_mod13_post0\n 2 1.44e- 7    0.95 rmse    standard   0.259    10 0.0154  pre0_mod07_post0\n 3 1.13e- 9    0.85 rmse    standard   0.259    10 0.0154  pre0_mod03_post0\n 4 1.83e- 5    0.8  rmse    standard   0.259    10 0.0154  pre0_mod11_post0\n 5 4.28e- 8    0.7  rmse    standard   0.259    10 0.0154  pre0_mod06_post0\n 6 3.36e-10    0.6  rmse    standard   0.259    10 0.0154  pre0_mod02_post0\n 7 5.46e- 6    0.55 rmse    standard   0.259    10 0.0155  pre0_mod10_post0\n 8 1.27e- 8    0.45 rmse    standard   0.259    10 0.0155  pre0_mod05_post0\n 9 1   e-10    0.35 rmse    standard   0.259    10 0.0157  pre0_mod01_post0\n10 4.83e- 7    0.3  rmse    standard   0.259    10 0.0158  pre0_mod08_post0\n11 6.16e- 5    0.2  rmse    standard   0.260    10 0.0161  pre0_mod12_post0\n12 6.95e- 4    0.4  rmse    standard   0.260    10 0.0168  pre0_mod14_post0\n13 3.79e- 9    0.15 rmse    standard   0.260    10 0.0164  pre0_mod04_post0\n14 2.34e- 3    0.65 rmse    standard   0.263    10 0.0207  pre0_mod15_post0\n15 1.62e- 6    0.05 rmse    standard   0.263    10 0.0184  pre0_mod09_post0\n16 7.85e- 3    0.1  rmse    standard   0.265    10 0.0217  pre0_mod16_post0\n17 2.64e- 2    0.9  rmse    standard   0.296    10 0.0120  pre0_mod17_post0\n18 8.86e- 2    0.5  rmse    standard   0.319    10 0.0118  pre0_mod18_post0\n19 2.98e- 1    0.25 rmse    standard   0.371    10 0.00965 pre0_mod19_post0\n20 1   e+ 0    0.75 rmse    standard   0.794    10 0.0101  pre0_mod20_post0\n```\n\n\n:::\n:::\n\n\nThe Elastic Net tuning procedure produced a model with a **very small penalty (0.000207)** and **a mixture value of 1**, meaning that the optimal model effectively collapses to a **pure Lasso regression**. This indicates that the best-performing model requires only minimal regularisation and benefits primarily from Lasso’s ability to shrink less-informative coefficients toward zero. The **cross-validation** results show that a wide range of mixture values produced nearly **identical RMSE values (0.259)**, suggesting that the model is relatively *insensitive* to the balance between L1 and L2 penalties. The selection of **mixture = 1** therefore reflects a slight advantage for sparsity rather than a structural dependence on ridge-style regularisation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbest_params <- select_best(enet_tune_results, metric = \"rmse\")\nprint(best_params)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n   penalty mixture .config         \n     <dbl>   <dbl> <chr>           \n1 0.000207       1 pre0_mod13_post0\n```\n\n\n:::\n\n```{.r .cell-code}\nfinal_enet_workflow <- finalize_workflow(\n  enet_workflow,\n  best_params\n)\n\nimproved_fit <- fit(final_enet_workflow, data = train_data)\n\ntidy(improved_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 25 × 3\n   term                    estimate  penalty\n   <chr>                      <dbl>    <dbl>\n 1 (Intercept)               7.13   0.000207\n 2 age                       0.166  0.000207\n 3 quality_of_sleep          0.547  0.000207\n 4 physical_activity_level   0.208  0.000207\n 5 stress_level             -0.150  0.000207\n 6 bp_systolic              -1.05   0.000207\n 7 bp_diastolic              0.940  0.000207\n 8 heart_rate                0.126  0.000207\n 9 daily_steps              -0.204  0.000207\n10 gender_Male              -0.0499 0.000207\n# ℹ 15 more rows\n```\n\n\n:::\n:::\n\n\nBecause the Elastic Net recipe applies both a Yeo–Johnson transformation and normalization to all numeric predictors, the resulting coefficients are on a fundamentally **different scale** from the baseline OLS model. As a result, some predictors such as `heart_rate` and `daily_steps` appear to have larger coefficients, but this reflects the rescaled predictors rather than the absence of shrinkage. In contrast, `stress_level` shows a clear reduction in magnitude **(−0.166 → −0.150)**, representing genuine coefficient shrinkage. Most other predictors retain similar relative importance, consistent with the fact that the selected penalty value is very small.\n\n## Q2.5 Interpretation\n\nTo evaluate whether the Elastic Net model provides an improvement over the baseline linear regression, both models are assessed on the same held-out test set. Predicted values from each model are compared against the true `sleep_duration` values, and three standard regression metrics **RMSE**, **MAE**, and **R-squared** are computed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredictions_improved <- predict(improved_fit, new_data = test_data) |>\n  bind_cols(test_data |> select(sleep_duration))\n\nimproved_metrics <- metrics(predictions_improved,\n                            truth = sleep_duration,\n                            estimate = .pred)\n\ncomparison_table <- bind_rows(\n  baseline_metrics |> mutate(model = \"Baseline (Q2.2)\"),\n  improved_metrics |> mutate(model = \"Improved - Elastic Net (Q2.4)\")\n) |>\n  select(model, .metric, .estimate) |>\n  arrange(.metric, .estimate)\n\nprint(comparison_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  model                         .metric .estimate\n  <chr>                         <chr>       <dbl>\n1 Improved - Elastic Net (Q2.4) mae         0.194\n2 Baseline (Q2.2)               mae         0.208\n3 Improved - Elastic Net (Q2.4) rmse        0.285\n4 Baseline (Q2.2)               rmse        0.295\n5 Baseline (Q2.2)               rsq         0.870\n6 Improved - Elastic Net (Q2.4) rsq         0.879\n```\n\n\n:::\n:::\n\n\nThe performance comparison shows that the Elastic Net model provides a small but consistent **improvement** over the baseline linear regression. Both RMSE and MAE decrease slightly (**RMSE: 0.295 → 0.285**, **MAE: 0.208 → 0.194**), indicating that the Elastic Net produces more **accurate** predictions on average. The R-squared values for the two models are almost identical (**0.870 → 0.879**), suggesting that both models explain a similar proportion of variance in `sleep_duration`. Overall, the gains are modest, which is expected because the baseline model was already performing strongly. Nevertheless, the reduced error metrics demonstrate that introducing regularization and tuning the penalty parameters helps improve generalization, even in a relatively small dataset.\n\n# Part 3: Classification\n\nThis part focuses on predicting whether a participant achieves adequate or inadequate sleep using **classification** models.\n\n## Q3.1 Splitting the data into training and test sets\n\nTo begin the classification task, the continuous outcome `sleep_duration` must be converted into a **binary** variable indicating whether a participant achieves **adequate** or **inadequate** sleep. Following common recommendations in sleep research, a threshold of **7 hours** per night is used to define *adequate sleep*. A new factor variable, `adequate_sleep`, is therefore created, coded as \"adequate\" for durations ≥ 7 hours and \"inadequate\" otherwise.\n\n::: callout-note\n## Stratified Sampling\n\nAs in the regression analysis in **Part 2**, the data is split into training (75%) and test (25%) sets using **stratified sampling**. Here, stratification is applied to the new binary sleep outcome to maintain a similar proportion of adequate and inadequate sleepers in both subsets, ensuring a fair and reliable foundation for the classification models that follow.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsleep_class <- sleep_clean |>\n  mutate(\n    adequate_sleep = if_else(\n      sleep_duration >= 7,\n      \"adequate\",\n      \"inadequate\"\n    ) |> factor(levels = c(\"inadequate\", \"adequate\"))\n  )\n\nset.seed(456)\n\nclass_split <- initial_split(\n  sleep_class,\n  prop   = 0.75,\n  strata = adequate_sleep  \n)\n\ntrain_class <- training(class_split)\ntest_class  <- testing(class_split)\n\ntrain_class |> count(adequate_sleep)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  adequate_sleep   n\n1     inadequate 116\n2       adequate 164\n```\n\n\n:::\n\n```{.r .cell-code}\ntest_class  |> count(adequate_sleep)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  adequate_sleep  n\n1     inadequate 39\n2       adequate 55\n```\n\n\n:::\n\n```{.r .cell-code}\ndim(train_class)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 280  15\n```\n\n\n:::\n\n```{.r .cell-code}\ndim(test_class)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 94 15\n```\n\n\n:::\n:::\n\n\nThe output confirms that the stratified 75/25 split was executed correctly. `train_class` contains **280 rows** and `test_class` **94 rows**, which together sum to the original 374 observations. Importantly, the class distribution is well preserved in the test set, with **55 adequate sleepers** and **39 inadequate sleepers**, closely reflecting the proportions in the full dataset, which reduces the risk of biased model training or misleading performance estimates.\n\n## Q3.2 Fitting a baseline logistic regression classifier\n\nDiverging from the comprehensive approach used in the regression analysis, a parsimonious strategy was adopted for the baseline classifier to ensure numerical stability. Preliminary diagnostics indicated that including `quality_of_sleep` caused complete separation; thus, it was excluded to prevent unstable coefficient estimates. Consequently, the baseline model was restricted to `stress_level` and `age`, establishing a clear, interpretable benchmark and minimizing overfitting given the limited sample size.\n\n::: callout-note\n## Variable Selection\n\n`stress_level` and `age` were selected based on both statistical evidence and practical interpretability. Exploratory analysis (**Part 1**) identified `stress_level` as the strongest predictor of `sleep_duration` (r=**−0.81**) after excluding `sleep_quality`, while `age` showed a moderate but distinct positive association (r=**0.34**). By combining a modifiable lifestyle factor (**stress**) with a fixed demographic attribute (**age**), this baseline model captures two fundamental dimensions of sleep behavior while minimizing multicollinearity issues often found with physiological metrics like `heart_rate`.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlog_spec_baseline <- logistic_reg() |> \n  set_engine(\"glm\")\n\nlog_recipe_baseline <- recipe(\n  adequate_sleep ~ stress_level + age,  \n  data = train_class\n) |> \n  step_normalize(all_predictors())\n\nlog_workflow_baseline <- workflow() |> \n  add_model(log_spec_baseline) |> \n  add_recipe(log_recipe_baseline)\n\nlog_fit_baseline <- fit(log_workflow_baseline, data = train_class)\n\ntidy(log_fit_baseline)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term         estimate std.error statistic  p.value\n  <chr>           <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)     0.317     0.197      1.61 1.07e- 1\n2 stress_level   -2.92      0.348     -8.40 4.32e-17\n3 age            -1.19      0.275     -4.34 1.43e- 5\n```\n\n\n:::\n:::\n\n\nThe baseline logistic regression reveals highly significant associations for both predictors (p\\<0.001). Specifically, `stress_level` exhibits a strong **negative** coefficient (**−2.92**), indicating that as stress increases, the likelihood of achieving adequate sleep diminishes substantially. Similarly, `age` shows a **negative** association (**-1.19**), suggesting that older participants are statistically less likely to meet the adequate sleep threshold, holding stress levels constant.\n\n::: callout-note\n## Age Coefficient\n\nA notable finding in this baseline model is the **negative** coefficient for `Age` (**−1.19**), which contradicts the positive correlation observed in the exploratory analysis and linear regression. The logistic regression suggests that, when holding `stress_level` constant, older participants are **less** likely to cross the specific threshold of 7 hours defined for \"adequate\" sleep. This discrepancy may arise from the specific distribution of `sleep_duration` around the cutoff point or potential interactions between age and stress. For instance, while older adults might sleep longer on average, they may cluster just below the 7-hour threshold or have a different relationship with stress compared to younger cohorts, leading to a reversal in the conditional probability of adequacy.\n:::\n\n## Q3.3 Model evaluation\n\nTo comprehensively assess predictive capability, model performance is evaluated using a multi-faceted approach. Specifically, the **Confusion Matrix** is examined to visualize misclassifications, while **Sensitivity** and **Specificity** are calculated to ensure balanced identification of both adequate and inadequate sleepers. Furthermore, the **ROC AUC** is utilized as the primary metric for model discrimination, providing a robust measure of performance independent of the classification threshold.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlog_results_baseline <- augment(log_fit_baseline, new_data = test_class)\n\nlog_results_baseline |> \n  conf_mat(truth = adequate_sleep, estimate = .pred_class)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Truth\nPrediction   inadequate adequate\n  inadequate         33        2\n  adequate            6       53\n```\n\n\n:::\n\n```{.r .cell-code}\neval_metrics_extended <- metric_set(\n  accuracy, sensitivity, specificity, precision, f_meas, roc_auc\n)\n\nmetrics_results <- log_results_baseline |> \n  eval_metrics_extended(\n    truth = adequate_sleep, \n    estimate = .pred_class, \n    .pred_adequate,        \n    event_level = \"second\" \n  )\n\nprint(metrics_results)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  .metric     .estimator .estimate\n  <chr>       <chr>          <dbl>\n1 accuracy    binary         0.915\n2 sensitivity binary         0.964\n3 specificity binary         0.846\n4 precision   binary         0.898\n5 f_meas      binary         0.930\n6 roc_auc     binary         0.907\n```\n\n\n:::\n\n```{.r .cell-code}\nlog_results_baseline |> \n  roc_curve(truth = adequate_sleep, .pred_adequate, event_level = \"second\") |> \n  autoplot() +\n  labs(\n    title = \"ROC Curve: Baseline Logistic Regression\",\n    subtitle = \"Predictors: Stress Level + Age\"\n  )\n```\n\n::: {.cell-output-display}\n![](62751_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nThe baseline logistic regression model demonstrates robust predictive capability on the `test_class`. The model achieved an overall **accuracy** of **91.5%**, supported by a remarkably high **ROC AUC** of **0.907**, which indicates excellent discrimination between adequate and inadequate sleepers. Regarding class-specific performance, the model exhibits a sensitivity of **96.4%** and a specificity of **84.6%**. This profile suggests that while the classifier is effective overall, it is slightly more proficient at correctly identifying adequate sleepers than detecting inadequate ones. Nevertheless, this outcome confirms that these two factors act as powerful drivers of sleep adequacy.\n\n## Q3.4 Exploring ways to improve the classifier\n\nA more sophisticated modeling approach is explored to maximize predictive performance. While the baseline logistic regression provided interpretability, it relies on linear assumptions that may oversimplify complex lifestyle interactions(e.g., physical activity × stress). To address this, a **Random Forest classifier** is introduced.\n\n::: callout-note\n## Model Selection Summary\n\nA Random Forest classifier was chosen as the improved model because\n\n(i) it naturally handles nonlinear relationships\n\n(ii) it is robust to multicollinearity\n\n(iii) it allows the inclusion of all predictors without risking complete separation.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrf_spec <- rand_forest(\n  mtry = tune(),\n  trees = 500,\n  min_n = tune()\n) |> \n  set_engine(\"ranger\", importance = \"impurity\") |> \n  set_mode(\"classification\")\n\nrf_recipe <- recipe(\n  adequate_sleep ~ ., \n  data = train_class\n) |> \n  step_rm(sleep_duration) |> \n  step_rm(quality_of_sleep) |>\n  step_dummy(all_nominal_predictors()) \n\nrf_workflow <- workflow() |> \n  add_model(rf_spec) |> \n  add_recipe(rf_recipe)\n\nset.seed(789)\ncv_folds_class <- vfold_cv(train_class, v = 10, strata = adequate_sleep)\n\nrf_grid <- grid_regular(\n  mtry(range = c(2, 10)),\n  min_n(range = c(2, 20)),\n  levels = 5\n)\n\nrf_tune_res <- tune_grid(\n  rf_workflow,\n  resamples = cv_folds_class,\n  grid = rf_grid,\n  metrics = metric_set(roc_auc, accuracy)\n)\n\nbest_rf <- select_best(rf_tune_res, metric = \"roc_auc\")\n\nfinal_rf_workflow <- finalize_workflow(rf_workflow, best_rf)\nfinal_rf_fit <- last_fit(final_rf_workflow, class_split)\n\ncollect_metrics(final_rf_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  .metric     .estimator .estimate .config        \n  <chr>       <chr>          <dbl> <chr>          \n1 accuracy    binary        0.989  pre0_mod0_post0\n2 roc_auc     binary        1.000  pre0_mod0_post0\n3 brier_class binary        0.0167 pre0_mod0_post0\n```\n\n\n:::\n\n```{.r .cell-code}\nfinal_rf_fit |> \n  extract_fit_parsnip() |> \n  vip(num_features = 10)\n```\n\n::: {.cell-output-display}\n![](62751_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nThe Random Forest model achieved superior predictive performance, yielding an **ROC AUC** of **1.000** and an accuracy of **98.9%** on the test set. This represents a substantial improvement over the baseline logistic regression (**AUC 0.907**), confirming the value of incorporating non-linear interactions and the full set of predictors (though critical assessment is required).\n\n## Q3.5 Interpretation\n\nThe comparison between the baseline logistic regression and the Random Forest classifier provides decisive insights into the determinants of sleep adequacy. The Random Forest model achieved near-perfect predictive performance, indicating that when non-linear interactions and the full spectrum of lifestyle variables are accounted for, the distinction between adequate and inadequate sleepers becomes almost deterministic **within this dataset**.\n\nAnalysis of the Variable Importance Plot reveals a clear hierarchy of influence. Both `stress_level` and `physical_activity_level` emerged as the most critical drivers of sleep outcomes, reinforcing the conclusion that sleep adequacy is governed by a **dual mechanism** of `psychological` state and `physiological` activity. Notably, age ranked sixth in importance within the non-linear model. This lower ranking, combined with the model's superior performance, helps resolve the paradoxical negative coefficient observed in the linear baseline (Q3.2). It suggests that age itself is less of a direct determinant and more of a confounding factor, whose influence is better explained by its complex interactions with **activity levels** and **stress**, which the Random Forest successfully disentangled.\n\nThese findings offer **actionable strategies** for public health and individual sleep management. The dominance of `stress_level` and `physical_activity_level` suggests that interventions should prioritize a holistic approach: promoting active lifestyles while simultaneously implementing stress-reduction techniques. Targeting these two modifiable levers is likely to be the most effective strategy for improving sleep duration across the population.\n\n# Part 4: Reflection\n\n## Q4.1 Ethical considerations of predicting sleep outcomes from lifestyle data\n\nSeveral ethical concerns arise when building predictive models using **lifestyle and health-related data**. First, such data are inherently **sensitive**, meaning that participants may face **privacy risks** if information about stress levels, heart rate, or sleep patterns is **misused** or **inadequately protected**. Because lifestyle indicators can be linked to mental or physical health, improper handling may lead to stigmatization or discrimination. For example, by employers or insurers inferring reduced productivity or increased risk. Second, predictions about “adequate sleep” could be interpreted as normative judgments about personal habits, potentially reinforcing **harmful stereotypes** about age, gender, occupation, or socioeconomic status. Third, algorithmic predictions may influence behaviour: individuals who receive unfavourable classifications might experience **anxiety** or adopt counterproductive health behaviours. Therefore, sleep-prediction models should be developed and deployed with a **clear commitment to privacy**, **informed consent**, and **respect for individual autonomy**, ensuring that predictions are used to **support** well-being rather than **surveillance** or **evaluation**.\n\n## Q4.2 Potential sources of bias or confounding\n\nPredictive modelling in this context is vulnerable to several forms of bias and confounding. For example, `stress_level` is strongly associated with both `sleep_duration` and many unobserved factors such as work demands, caregiving responsibilities, or socioeconomic disadvantage. Without proper adjustment, the model may attribute differences in sleep adequacy to lifestyle choices when they are partly driven by structural or environmental conditions. Similarly, variables such as `physical_activity_level` or `daily_steps` may act as proxies for access to safe outdoor spaces, free time, or general health status, embedding **social inequalities** into model predictions. **Sampling bias** is also a concern: if participants in the dataset are healthier, younger, or more technologically engaged than the general population, the model’s performance will not generalise well. Measurement confounding is another issue. Self-reported sleep quality or stress may reflect **personality traits** rather than objective conditions, potentially **distorting** relationships between predictors and outcomes. These sources of bias highlight the need for **cautious interpretation** and underscore that statistical associations do **not** necessarily imply direct causal effects.\n\n## Q4.3 Additional variables or modelling approaches that could strengthen predictions\n\nPredictive performance could be enhanced by incorporating additional variables that capture structural and behavioural influences on sleep. **Environmental factors** such as noise exposure, work hours, shift patterns, commuting time, bedroom light levels, or access to green spaces may provide substantial explanatory power. Data on mental health (e.g., anxiety or depression scores), medication use, alcohol consumption, and digital-device screen time are also strongly linked to sleep behaviour and would likely improve classification accuracy. From a methodological perspective, more flexible models such as **gradient-boosted trees** or **Bayesian additive regression trees** could capture complex nonlinear structures and interactions that are difficult to model using logistic regression alone. **Time-series** or **longitudinal** modelling would allow sleep patterns to be understood as **dynamic processes** rather than static snapshots. Finally, **causal-inference frameworks** such as propensity-score methods or structural equation modelling could help separate predictive associations from underlying mechanisms, providing richer insight into how lifestyle factors **influence** sleep.\n\n## Q4.4 Communicating findings responsibly to a non-technical audience\n\nCommunicating sleep-prediction findings to **non-technical** audiences requires an emphasis on clarity, humility, and responsible interpretation. Technical details such as model architecture or tuning should be **simplified** into **intuitive explanations**.\n\n> “The model looks for patterns across lifestyle factors to estimate the likelihood of achieving sufficient sleep.”\n\nIt is crucial to distinguish **correlations** from **causation** and explicitly state that the model identifies statistical associations, **not deterministic rules**. Uncertainty should be highlighted by explaining that predictions may be inaccurate for some individuals and **should not** be used as medical diagnoses or performance evaluations. To avoid reinforcing stereotypes, model outputs should be framed in terms of general tendencies rather than inherent characteristics of specific groups. Most importantly, communication should focus on actionable, **supportive insights**.\n\n> “Higher stress levels were consistently associated with shorter sleep in this dataset.”\n\nrather than\n\n> “People with high stress do not sleep adequately”.\n\nBy foregrounding transparency and empowerment, the findings can be communicated in a way that promotes understanding **without overstating the model’s capabilities**.\n",
    "supporting": [
      "62751_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}